// svelte-kit/src/routes/(logged-in)/scan/ScanResults.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { fade } from "svelte/transition";
  import { quadIn } from "svelte/easing";

  import BookCover from "$lib/components/ui/BookCover.svelte";
  import useReducer from "$lib/state/useReducer";
  import SlideAnimate from "$lib/util/SlideAnimate.svelte";

  function scanReducer(state: any, [type, payload]: any) {
    switch (type) {
      case "pendingCountSet":
      case "bookQueued":
        return { ...state, pending: payload };
      case "scanResults":
        const newItems = payload.results.map((result: any) => ({ success: result.success, ...result.item }));
        return { ...state, booksSaved: newItems.concat(state.booksSaved).slice(0, 25) };
    }
    return state;
  }

  type StateType = { pending: any; booksSaved: any[] };
  let [state, dispatch] = useReducer<StateType>(scanReducer, { pending: 0, booksSaved: [] });
  $: ({ pending, booksSaved } = $state);

  let showIncomingQueue = false;
  const toggleIncomingQueue = () => (showIncomingQueue = !showIncomingQueue);

  $: toggleClass = showIncomingQueue ? "fa-angle-double-up" : "fa-angle-double-down";

  $: toggleShow = booksSaved.length || pending;
  $: labelScanStatusStyles = !!toggleShow ? `display: inline-block; width: 30ch` : "";

  onMount(() => {
    function sendIt({ detail }: any) {
      dispatch([detail.type, detail.pendingCount ?? detail.packet]);
    }

    window.addEventListener("ws-info", sendIt);
    window.dispatchEvent(new CustomEvent("sync-ws"));

    return () => window.removeEventListener("ws-info", sendIt);
  });
</script>

<div style="flex: 1">
  <div>
    {#if pending}
      <span class="label label-info">
        <span style={labelScanStatusStyles}>
          {pending}
          Book{pending === 1 ? "" : "s"}
          currently outstanding
        </span>
        {#if toggleShow}
          <button on:click={toggleIncomingQueue} class="raw-button margin-left-xs">
            <i style="color: white" class="far fa-white {toggleClass}" />
          </button>
        {/if}
      </span>
    {:else if pending != null}
      <span class="label label-success">
        <span style={labelScanStatusStyles}> All pending books saved </span>
        {#if toggleShow}
          <button on:click={toggleIncomingQueue} class="margin-left-xs">
            <i style="color: white" class="far fa-white {toggleClass}" />
          </button>
        {/if}
      </span>
    {/if}
  </div>

  <div style="margin-top: 10px">
    <SlideAnimate open={showIncomingQueue} stiffDown={true}>
      <div class="alert alert-info alert-slim" style="margin-bottom: 15px">
        Your entered and failed books will show up here, briefly, although everything is being logged. Eventually there'll be a dedicated place to see
        what's been saved, and what failed to be found.
      </div>

      <div style="margin-bottom: 0">
        {#each booksSaved as book (book)}
          <div transition:fade|local={{ easing: quadIn }} class="margin-bottom">
            <div
              class="border-bottom padding-bottom"
              style="display: flex; flex-direction: row; color: {book.success ? 'var(--neutral-text)' : 'red'}"
            >
              <div style="min-width: 90px">
                <BookCover size="small" url={book.smallImage} />
              </div>
              <span>{book.title}</span>
            </div>
          </div>
        {/each}
      </div>
    </SlideAnimate>
  </div>
</div>

// react/modules/scan/scanResults.tsx
import React, { FunctionComponent, useEffect, useState, useReducer, Suspense } from "react";

import { useTransition, config, animated } from "react-spring";
import { SlideInContents } from "app/animationHelpers";
import { CoverSmall } from "app/components/bookCoverComponent";

function scanReducer(state, [type, payload]) {
  switch (type) {
    case "pendingCountSet":
    case "bookQueued":
      return { ...state, pending: payload };
    case "scanResults":
      const newItems = payload.results.map(result => ({ success: result.success, ...result.item }));
      return { ...state, booksSaved: newItems.concat(state.booksSaved).slice(0, 25) };
  }
  return state;
}

const ScanResults: FunctionComponent<{}> = props => {
  const [showIncomingQueue, setShowIncomingQueue] = useState(false);
  const [{ pending, booksSaved: booksJustSaved }, dispatch] = useReducer(scanReducer, { pending: 0, booksSaved: [] });

  const toggleIncomingQueue = () => setShowIncomingQueue(!showIncomingQueue);

  const toggleClass = showIncomingQueue ? "fa-angle-double-up" : "fa-angle-double-down";

  const toggleShow =
    booksJustSaved.length || pending ? (
      <a onClick={() => toggleIncomingQueue()} className="margin-left-xs">
        <i style={{ color: "white" }} className={`far fa-white ${toggleClass}`} />
      </a>
    ) : null;

  const booksJustSavedTransition = useTransition(booksJustSaved, {
    config: config.stiff,
    enter: { opacity: 1 },
    leave: { opacity: 0 }
  });

  useEffect(() => {
    function sendIt({ detail }: any) {
      dispatch([detail.type, detail.pendingCount ?? detail.packet]);
    }

    window.addEventListener("ws-info", sendIt);
    window.dispatchEvent(new CustomEvent("sync-ws"));
    return () => window.removeEventListener("ws-info", sendIt);
  }, []);

  const labelScanStatusStyles = !!toggleShow ? { display: "inline-block", width: "30ch" } : {};

  return (
    <div style={{ flex: 1 }}>
      <div>
        {pending == null ? null : pending ? (
          <span className="label label-info">
            <span style={labelScanStatusStyles}>{`${pending} Book${pending === 1 ? "" : "s"} currently outstanding`}</span>
            {toggleShow}
          </span>
        ) : (
          <span className="label label-success">
            <span style={labelScanStatusStyles}>All pending books saved&nbsp;</span>
            {toggleShow}
          </span>
        )}
      </div>

      <SlideInContents clamp={true} in={showIncomingQueue} immediateChanges={true} opacity={true} style={{ marginTop: "10px" }}>
        <div className="alert alert-info alert-slim" style={{ marginBottom: "15px" }}>
          Your entered and failed books will show up here, briefly, although everything is being logged. Eventually there'll be a dedicated place to
          see what's been saved, and what failed to be found.
        </div>

        <div style={{ marginBottom: 0 }}>
          {booksJustSavedTransition((styles, book) => (
            <Suspense fallback={null}>
              <div className="auto-fade-in margin-bottom">
                <animated.div
                  className="border-bottom padding-bottom"
                  style={{ display: "flex", flexDirection: "row", color: book.success ? "var(--neutral-text)" : "red", ...styles }}
                >
                  <div style={{ minWidth: "90px" }}>
                    <CoverSmall url={book.smallImage} />
                  </div>
                  <span>{book.title}</span>
                </animated.div>
              </div>
            </Suspense>
          ))}
        </div>
      </SlideInContents>
    </div>
  );
};

export default ScanResults;
