// svelte-kit/src/lib/components/subjectsAndTags/tags/SelectAvailableTags.svelte
<script lang="ts">
  import type { Tag } from "$data/types";
  import { filterTags } from "$lib/state/tagsState";

  import GenericLabelSelect from "../GenericLabelSelect.svelte";

  export let allTags: Tag[];
  export let onSelect: (tag: Tag) => void;
  export let placeholder = "Tags";
  export let currentlySelected: string[] = [];

  let search = "";

  const doSelect = (item: any) => {
    onSelect(item);
    search = "";
  };

  type TagSelectedHash = { [_id: string]: true };

  $: itemHash = currentlySelected.reduce<TagSelectedHash>((hash, _id) => ((hash[_id] = true), hash), {});

  $: eligible = filterTags(
    allTags.filter(s => !itemHash[s._id]),
    search
  );
</script>

<GenericLabelSelect {placeholder} bind:search options={() => eligible} onItemSelected={doSelect} />

// react/app/components/subjectsAndTags/tags/SelectAvailableTags.tsx
import React, { FunctionComponent, useContext, useState } from "react";
import { filterTags, useTagsState } from "app/state/tagsState";
import GenericLabelSelect from "../genericLabelSelect";

type LocalProps = { currentlySelected: string[]; onSelect: any; placeholder?: string };

const SelectAvailableTags: FunctionComponent<LocalProps> = props => {
  const { tags } = useTagsState();
  const [search, setSearchValue] = useState("");

  const setSearch = evt => setSearchValue(evt.target.value);

  const onSelect = item => {
    props.onSelect(item);
    setSearchValue("");
  };

  let { placeholder = "Tags", currentlySelected } = props;
  let itemHash = currentlySelected.reduce((hash, _idOrObj) => ((hash[_idOrObj] = true), hash), {});
  let eligible = filterTags(
    tags.filter(s => !itemHash[s._id]),
    search
  );

  return (
    <GenericLabelSelect inputProps={{ placeholder, value: search, onChange: setSearch }} suggestions={eligible} onSuggestionSelected={onSelect} />
  );
};

export default SelectAvailableTags;
