// svelte/modules/settings/ThemeChooser.svelte
<script lang="ts">
  import classNames from "classnames";
  import { appState, dispatch, SET_THEME, SET_WHITE_BG } from "app/state/appState";

  //import DemoStyles from "./demoStyles";
  import "./theme-chooser.scss";
  import Stack from "app/components/layout/Stack.svelte";

  let x: any = {};

  const { themeChooserRoot, demoContainer, themeChooserList, themeChooserItem, themeChooser } = x;

  const numThemes = 17;

  const themeNames = Array.from({ length: numThemes }, (v, i) => `scheme${i + 1}`);

  const arrayOfTen = Array.from({ length: 10 }, (v, i) => i + 1);

  $: ({ colorTheme, whiteBackground } = $appState);
</script>

<div class="theme-chooser-root">
  <div class="theme-chooser-list">
    <label style="font-size: 16px" class="checkbox margin-bottom">
      <input checked={whiteBackground == "1"} onChange={evt => dispatch({ type: SET_WHITE_BG, value: evt.target.checked })} type="checkbox" />
      White background
    </label>
    {#each themeNames as name, index}
      <Stack
        onClick={() => dispatch({ type: SET_THEME, theme: name })}
        class={classNames("theme-chooser-item", { active: colorTheme == name })}
        tightest={true}
      >
        <div class={classNames(name, "theme-chooser")}>
          {#each arrayOfTen as val}
            <div style={`background-color: var(--primary-${val})`} />
          {/each}
        </div>
      </Stack>
    {/each}
  </div>
  <div class="demo-container">
    <!-- <DemoStyles /> -->
  </div>
</div>

// react-redux/modules/settings/components/themeChooser/main.tsx
import React, { Component, useContext } from "react";
import classNames from "classnames";
import styles from "./styles.module.css";
import { AppContext } from "app/renderUI";
import { SET_THEME } from "app/appState";

import DemoStyles from "./demoStyles";

const { themeChooserRoot, themeChooserList, themeChooser } = styles;

const numThemes = 17;

const themeNames = Array.from({ length: numThemes }, (v, i) => `scheme${i + 1}`);
const arrayOfTen = Array.from({ length: 10 }, (v, i) => i + 1);

const ThemeChooser = props => {
  const [{ colorTheme }, actions, dispatch] = useContext(AppContext);
  return (
    <div className={themeChooserRoot}>
      <div className={themeChooserList}>
        {themeNames.map((name, index) => (
          <>
            <div
              onClick={() => dispatch({ type: SET_THEME, theme: name })}
              className={classNames(name, themeChooser, { active: colorTheme == name })}
            >
              <span>
                {"Theme " + (index + 1)}
                {colorTheme == name ? <i className="far fa-check margin-left" /> : null}
              </span>
              {arrayOfTen.map(val => (
                <div style={{ backgroundColor: `var(--primary-${val})` }} />
              ))}
            </div>
            <br />
          </>
        ))}
      </div>
      <div>
        <DemoStyles />
      </div>
    </div>
  );
};

export default ThemeChooser;
