// svelte/modules/home/BarChart.svelte
<script lang="ts">
  import scaleLinear from "d3-scale/src/linear";
  import scaleBand from "d3-scale/src/band";
  import max from "d3-array/src/max";

  import barCharQuery from "graphQL/home/barChart.graphql";

  import { appState } from "app/state/appState";
  import { subjectsState } from "app/state/subjectsState";
  import { query } from "micro-graphql-svelte";
  import { stackGraphData } from "./stackGraphData";
  import RenderBarChart from "./RenderBarChart.svelte";
  import SvgTooltip from "./SvgTooltip.svelte";
  import Axis from "./Axis.svelte";

  export let drilldown;
  export let subjects;
  export let header;
  export let chartIndex;
  export let maxWidth;
  export let width;
  export let height;

  $: ({ subjectHash } = $subjectsState);

  let excluding = {};

  let { publicUserId } = $appState;

  let el;

  const removeBar = id => (excluding = { ...excluding, [id]: true });
  const restoreBar = id => (excluding = { ...excluding, [id]: false });

  const subjectIds = subjects.map(s => s._id);

  const { queryState } = query(barCharQuery, { initialSearch: { subjectIds, searchChildSubjects: true, publicUserId } });

  $: graphData = stackGraphData(subjectHash, subjectIds, $queryState.data);

  $: {
    let _ = { __: $queryState.data, subjects };
    el && el.scrollIntoView({ behavior: "smooth" });
  }

  const scrollInitial = el => {
    el && el.scrollIntoView({ behavior: "smooth" });
  };

  const margin = { top: 20, right: 10, bottom: 180, left: 0 };
  $: showingDataRaw = graphData?.filter(d => !excluding[d.groupId]);

  let showingData: any[];
  $: {
    showingDataRaw?.forEach((data: any) => {
      data.childSubjects = data.entries.reduce((subjects, { children: theseChildren }) => subjects.concat(theseChildren), []);
    });
    showingData = showingDataRaw as any;
  }

  let hoveredMap = {};
  const hoverBar = groupId => (hoveredMap = { ...hoveredMap, [groupId]: true });
  const unHoverBar = groupId => setTimeout(() => (hoveredMap = { ...hoveredMap, [groupId]: false }), 1);

  $: {
    if (showingData?.length) {
      let x = showingData.length * 110 + 60;
      if (width > x) {
        width = x;
      }
    }
  }
  //$: width = Math.min(width, showingData?.length * 110 + 60);

  $: dataValues = showingData?.map(({ count }) => count) ?? [];
  $: displayValues = showingData?.map(({ display }) => display) ?? [];
  $: chartHeight = height - margin.top - margin.bottom;
  $: dataMax = max(dataValues);
  $: dataScale = scaleLinear()
    .domain([0, dataMax ?? []])
    .range([0, chartHeight]);
  $: scaleX = scaleBand().domain(displayValues).range([0, width]).paddingInner([0.1]).paddingOuter([0.3]).align([0.5]);

  $: svgStyle = "display: block; margin-left: auto; margin-right: auto;";

  $: excludedCount = Object.keys(excluding).filter(k => excluding[k]).length;
  $: offsetY = margin.bottom - height;

  $: totalSvgWidth = width;
  $: delta = maxWidth - width;
  let extraOffsetX = 0;
  $: {
    if (totalSvgWidth < maxWidth) {
      totalSvgWidth = maxWidth;
      extraOffsetX = delta / 2;
    }
  }

  $: transform = `scale(1, -1) translate(${margin.left + extraOffsetX}, ${offsetY})`;
</script>

{#if !graphData || !scaleX.bandwidth()}
  <span>Nothing {scaleX.bandwidth()}</span>
{:else if !graphData.length}
  {#if chartIndex == 0}
    <div class="alert alert-warning inline-flex" style="margin-bottom: 75px">
      It looks like there's nothing to show here. Once you add some books to your library, and add subjects to them, they'll show up here.
    </div>
  {:else}
    <div use:scrollInitial class="alert alert-warning" style="margin: 0 auto 75px auto">
      It looks like the child subjects under
      {header}
      currently have no books assigned
    </div>
  {/if}
{:else}
  <div bind:this={el}>
    <div style="height: {height}px">
      <div>
        <h4 style="display: inline">{header}</h4>
        {#if excludedCount}
          <span style="margin-left: 10px">
            Excluding:&nbsp;
            {#each graphData.filter(d => excluding[d.groupId]) as d}
              <span style="margin-left: 10px">
                {d.display}{' '}
                <a style="color: black" on:click={() => restoreBar(d.groupId)}> <i class="far fa-redo" /> </a>
              </span>
            {/each}
          </span>
        {/if}
      </div>
      <svg style={svgStyle} width={totalSvgWidth} {height}>
        <RenderBarChart {showingData} {excluding} {scaleX} {dataScale} {totalSvgWidth} {hoverBar} {unHoverBar} {transform} />
        <g data-x="x" {transform}>
          {#each showingData.filter(d => !excluding[d.groupId]) as d, i (d.groupId)}
            <SvgTooltip
              data={d}
              srcHeight={dataScale(d.count)}
              srcWidth={scaleX.bandwidth()}
              srcX={scaleX(d.display)}
              count={showingData.length}
              index={i}
              childSubjects={d.childSubjects}
              hovered={hoveredMap[d.groupId]}
              {drilldown}
              {chartIndex}
              {removeBar}
            />
          {/each}
        </g>
        <Axis
          masterTransform={`translate(${margin.left + extraOffsetX}, ${-1 * margin.bottom})`}
          data={showingData}
          {scaleX}
          graphWidth={width}
          scale={scaleX}
          transform={`translate(0, ${height})`}
        />
      </svg>
    </div>
    <hr />
  </div>
{/if}

// react-redux/modules/home/components/barChart.tsx
import React, { Component, PureComponent } from "react";
import { connect } from "react-redux";

import scaleLinear from "d3-scale/src/linear";
import scaleBand from "d3-scale/src/band";
import max from "d3-array/src/max";

import Bar from "./bar";
import Axis from "./axis";

import { getChildSubjectsSorted, computeSubjectParentId, RootApplicationType } from "applicationRoot/rootReducer";
import ajaxUtil from "util/ajaxUtil";

@connect((state: RootApplicationType) => ({
  subjectHash: state.app.subjectHash,
  subjectsLoaded: state.app.subjectsLoaded
}))
export default class BarChart extends PureComponent<any, any> {
  el: any;
  state = { left: 0, excluding: {}, data: null };
  sized = ({ bounds }) => {
    if (bounds.left != this.state.left) {
      this.setState({ left: bounds.left });
    }
  };
  removeBar = id => this.setState((state, props) => ({ excluding: { ...state.excluding, [id]: true } }));
  restoreBar = id => this.setState((state, props) => ({ excluding: { ...state.excluding, [id]: false } }));

  componentDidMount() {
    this.getChart(() => {
      if (this.props.chartIndex > 0) {
        this.el.scrollIntoView({ behavior: "smooth" });
      }
    });
  }
  componentDidUpdate(prevProps, prevState) {
    if (prevProps.subjects != this.props.subjects) {
      this.getChart();
    }
  }

  getChart = (cb?: any) => {
    let { subjects, subjectHash } = this.props;
    let subjectIds = subjects.map(s => s._id);
    let targetSubjectsLookup = new Set(subjectIds);

    let subjectResultsMap = new Map<string, number>([]);

    function getApplicableRootSubject(subject) {
      let parentId = computeSubjectParentId(subject.path);

      if (!parentId) {
        return subject;
      } else if (targetSubjectsLookup.has(parentId)) {
        return subjectHash[parentId];
      } else {
        return getApplicableRootSubject(subjectHash[parentId]);
      }
    }

    return ajaxUtil.post("/book/booksBySubjects", { subjects: subjectIds, gatherToParents: 1 }).then(resp => {
      resp.results.forEach(item => {
        let subjectsHeld = item.subjects
          .filter(_id => subjectHash[_id])
          .map(_id => (targetSubjectsLookup.has(_id) ? _id : getApplicableRootSubject(subjectHash[_id])._id));

        let uniqueSubjects = Array.from(new Set(subjectsHeld));
        let uniqueSubjectString = uniqueSubjects.sort().join(",");

        if (!subjectResultsMap.has(uniqueSubjectString)) {
          subjectResultsMap.set(uniqueSubjectString, 0);
        }
        subjectResultsMap.set(uniqueSubjectString, subjectResultsMap.get(uniqueSubjectString) + 1);
      });

      let data = Array.from(subjectResultsMap).map(([name, count], i) => {
        let _ids = name.split(",").filter(s => s);
        let names = _ids
          .map(_id => subjectHash[_id].name)
          .sort()
          .join(",");

        return {
          groupId: name,
          count,
          display: names,
          entries: _ids.map(_id => {
            let subject = subjectHash[_id];
            return {
              name: subject.name,
              color: subject.backgroundColor,
              children: getChildSubjectsSorted(_id, subjectHash)
            };
          })
        };
      });

      this.setState({ data }, cb);
    });
  };

  width: any;
  render() {
    let margin = { top: 20, right: 10, bottom: 180, left: 0 };
    let { subjectsLoaded, width, height, drilldown, chartIndex, header } = this.props;
    let { data, excluding } = this.state;

    if (!subjectsLoaded || !data || !data.length) {
      return null;
    }
    let fullData = data;

    data = data.filter(d => !excluding[d.groupId]);
    width = Math.min(width, data.length * 110 + 60);

    if (this.width == null) {
      this.width = width;
    }

    let dataValues = data.map(({ count }) => count);
    let displayValues = data.map(({ display }) => display);
    let chartHeight = height - margin.top - margin.bottom;
    let dataMax = max(dataValues);
    let dataScale = scaleLinear()
      .domain([0, dataMax])
      .range([0, chartHeight]);
    let scaleX = scaleBand()
      .domain(displayValues)
      .range([0, width])
      .paddingInner([0.1])
      .paddingOuter([0.3])
      .align([0.5]);
    let svgStyle = { display: "block", marginLeft: "auto", marginRight: "auto" }; //, marginLeft: 'auto', marginRight: 'auto'};

    let excludedCount = Object.keys(excluding).filter(k => excluding[k]).length;
    return (
      <div ref={el => (this.el = el)}>
        <div style={{ ...width, height }}>
          <div>
            <h4 style={{ display: "inline" }}>{header}</h4>
            {excludedCount ? (
              <span style={{ marginLeft: "10px" }}>
                Excluding:{" "}
                {fullData.filter(d => excluding[d.groupId]).map((d, i, arr) => (
                  <span style={{ marginLeft: "10px" }}>
                    {d.display}{" "}
                    <a onClick={() => this.restoreBar(d.groupId)}>
                      <i className="fa fa-fw fa-undo" />
                    </a>
                  </span>
                ))}
              </span>
            ) : null}
          </div>
          <svg style={svgStyle} width={width} height={height}>
            <g transform={`scale(1, -1) translate(${margin.left}, ${margin.bottom - height})`}>
              {data
                .filter(d => !this.state.excluding[d.groupId])
                .map((d, i) => (
                  <Bar
                    drilldown={drilldown}
                    chartIndex={chartIndex}
                    removeBar={this.removeBar}
                    key={d.groupId}
                    index={i}
                    data={d}
                    count={data.length}
                    x={scaleX(d.display)}
                    y={0}
                    width={scaleX.bandwidth()}
                    height={dataScale(d.count)}
                    graphWidth={this.width}
                    adjustTooltip={this.state.left}
                  />
                ))}
            </g>
            <g transform={`translate(${margin.left}, ${-1 * margin.bottom})`}>
              <Axis scale={scaleX} transform={`translate(0, ${height})`} />
            </g>
          </svg>
        </div>
        <hr />
      </div>
    );
  }
}
