// svelte/app/components/editBook/ManageBookCover.svelte
<script lang="ts">
  import { appState } from "app/state/appState";
  import { MutationOf, Mutations } from "graphql-typings";
  import Dropzone from "svelte-file-dropzone/src/components/Dropzone.svelte";

  import ajaxUtil from "util/ajaxUtil";
  import { getCrossOriginAttribute } from "util/corsHelpers";

  import UpdateBook from "graphQL/books/updateBook.graphql";
  import { mutation } from "micro-graphql-svelte";

  import FlowItems from "../layout/FlowItems.svelte";
  import Stack from "../layout/Stack.svelte";

  export let _id;
  export let img;
  export let size;
  export let imgKey;
  export let updateBookObject;

  let currentUrl = img;
  let uploadState = { pendingImg: "", uploadError: "" };

  let uploading = false;
  const { mutationState } = mutation<MutationOf<Mutations["updateBook"]>>(UpdateBook);
  let { runMutation: updateBook } = $mutationState;

  $: ({ loginToken, userId } = $appState);
  $: ({ pendingImg, uploadError } = uploadState);

  let remoteUrl = "";
  let remoteImageSaving = false;

  const keyDown = evt => {
    if (evt.keyCode == 13) {
      doRemoteSave();
    }
  };

  const doRemoteSave = () => {
    remoteImageSaving = true;

    const request = { userId, loginToken, url: remoteUrl, size };
    ajaxUtil
      .postWithCors(process.env.UPLOAD_BOOK_COVER_FROM_URL, request, processUrlResponse, processUrlError)
      .then(() => (remoteImageSaving = false));
  };

  const runSave = () => {
    let newUrl = uploadState.pendingImg;
    if (_id) {
      return updateBook({ _id, book: { [imgKey]: newUrl } }).then(() => {
        currentUrl = newUrl;
        uploadState = { pendingImg: "", uploadError: "" };
      });
    } else {
      currentUrl = newUrl;
      updateBookObject(book => ({ ...book, [imgKey]: newUrl }));
    }
  };

  const processUrlResponse = res => {
    if (res.error) {
      uploadState = { pendingImg: "", uploadError: res.error };
    } else if (!res.url) {
      uploadState = { pendingImg: "", uploadError: "Error uploading" };
    } else {
      uploadState = { pendingImg: res.url, uploadError: "" };
    }
    uploading = false;
  };

  const processUrlError = res => {
    uploadState = { pendingImg: "", uploadError: "Error uploading" };
    uploading = false;
  };

  const onDrop = evt => {
    const { acceptedFiles, fileRejections } = evt.detail;
    if (!acceptedFiles.length) {
      //TODO: ??
      return;
    }
    let request = new FormData();
    request.append("fileUploaded", acceptedFiles[0]);
    request.append("loginToken", loginToken);
    request.append("userId", userId);
    request.append("size", size);

    uploading = true;
    ajaxUtil.postWithFilesCors(process.env.UPLOAD_BOOK_COVER, request, processUrlResponse, processUrlError);
  };

  let dragging = false;
  $: dropAddedStyles = uploading ? "border-color: var(--neutral-6); cursor: wait;" : dragging ? "border-color: var(--primary-8);" : "";
</script>

<style>
  :global(.dropzone-container) {
    border: 3px solid var(--primary-9);
    text-align: center;
    background-color: white;
    padding: 5px;
    color: var(--neutral-text);
    outline: none;
    cursor: pointer;
  }
</style>

<FlowItems pushLast={true}>
  {#if currentUrl}
    <div style="min-width: 110px"><img {...getCrossOriginAttribute(currentUrl)} src={currentUrl} /></div>
  {:else}
    <div style="align-self: flex-start; min-width: 110px;" class="alert alert-warning"><span>No Cover</span></div>
  {/if}

  {#if !pendingImg}
    <div style="min-width: 100px; max-width: 140px; position: relative;">
      <Dropzone
        disableDefaultStyles={true}
        multiple={false}
        on:drop={onDrop}
        on:dragenter={() => (dragging = true)}
        on:dragleave={() => (dragging = false)}
        containerClasses="dropzone-container"
        containerStyles={dropAddedStyles}
      >
        <div>Click or drag to upload a new cover</div>
      </Dropzone>
      {#if uploadError}
        <div style="display: inline-block; margin-top: 2px; margin-bottom: 2px" class="label label-danger">{uploadError}</div>
      {/if}
    </div>
  {/if}
  {#if pendingImg}
    <Stack>
      <img src={pendingImg} {...getCrossOriginAttribute(pendingImg)} />
      <FlowItems pushLast={true}>
        <button on:click={runSave} class="btn btn-xs btn-light btn-square-icon"> <i class="fal fa-check" /> </button>
        <button on:click={() => (uploadState = { pendingImg: '', uploadError: '' })} class="btn btn-xs btn-light btn-square-icon">
          <i class="fal fa-undo" />
        </button>
      </FlowItems>
    </Stack>
  {/if}
  <div>
    <div class="btn-group">
      <input bind:value={remoteUrl} on:keydown={keyDown} style="min-width: 200px" class="form-control" placeholder="New Cover URL" tabIndex={-1} />
      <button class="btn btn-default" disabled={!remoteUrl || remoteImageSaving} on:click={doRemoteSave}>
        <i class="far fa-cloud-upload-alt" />
      </button>
    </div>
  </div>
</FlowItems>

// react-redux/app/components/editBook/manageBookCover.tsx
import React, { Component, useState } from "react";
import Dropzone from "react-dropzone";

import ajaxUtil from "util/ajaxUtil";

import UpdateBook from "graphQL/books/updateBook.graphql";
import { useMutation, buildMutation } from "micro-graphql-react";

const RemoteImageUpload = props => {
  const [url, setUrl] = useState("");
  const [saving, setSaving] = useState(false);

  const keyDown = evt => {
    if (evt.keyCode == 13) {
      doSave();
    }
  };

  const doSave = () => {
    setSaving(true);
    Promise.resolve(props.remoteSave({ _id: props._id, url })).then(({ url, failure }) => {
      setSaving(false);
      if (!failure) {
        props.onUpdate(url);
      }
    });
  };

  return (
    <div className="btn-group">
      <input
        onKeyDown={keyDown}
        value={url}
        style={{ minWidth: "200px" }}
        onChange={e => setUrl(e.target.value)}
        className="form-control"
        placeholder="New Cover URL"
        tabIndex={-1}
      />
      <button className="btn btn-default" disabled={!url || saving} onClick={doSave}>
        <i className="far fa-cloud-upload-alt" />
      </button>
    </div>
  );
};

const ManageBookCover = props => {
  const { _id, img, endpoint, imgKey, remoteSave } = props;
  const [currentUrl, setCurrentUrl] = useState(img);
  const [uploadState, setUploadState] = useState({ pendingImg: "", uploadError: "" });

  const { runMutation: updateBook, running: updateRunning } = useMutation(buildMutation(UpdateBook));

  const runSave = () => {
    if (!uploadState.pendingImg) {
      return;
    }
    let newUrl = uploadState.pendingImg;
    return updateBook({ _id, book: { [imgKey]: uploadState.pendingImg } }).then(() => {
      setCurrentUrl(newUrl);
      setUploadState({ pendingImg: "", uploadError: "" });
    });
  };

  const onDrop = files => {
    let request = new FormData();
    request.append("fileUploaded", files[0]);

    ajaxUtil.postWithFiles(`/react-redux/${endpoint}`, request, res => {
      if (res.error) {
        setUploadState({ pendingImg: "", uploadError: res.error });
      } else {
        setUploadState({ pendingImg: res.url, uploadError: "" });
      }
    });
  };

  const { pendingImg, uploadError } = uploadState;
  return (
    <div style={{ display: "flex", flexFlow: "row wrap" }}>
      <div className="margin-right">
        {img ? <img crossOrigin="anonymous" src={currentUrl} /> : <span className="alert alert-warning">No Cover</span>}
      </div>
      {!pendingImg ? (
        <div className="margin-right" style={{ minWidth: "100px", maxWidth: "140px" }}>
          <Dropzone
            acceptStyle={{ border: "3px solid var(--primary-8)" }}
            rejectStyle={{ border: "3px solid var(--primary-9)" }}
            activeStyle={{ border: "3px solid var(--primary-9)" }}
            disabledStyle={{ border: "3px solid var(--primary-9)" }}
            style={{ border: "3px solid var(--primary-9)", padding: "5px", fontSize: "14px", textAlign: "center", cursor: "pointer" }}
            onDrop={files => onDrop(files)}
            multiple={false}
          >
            <div>Click or drag to upload a new cover</div>
          </Dropzone>
          {uploadError ? (
            <div style={{ display: "inline-block", marginBottom: "2px" }} className="label label-danger">
              {uploadError}
            </div>
          ) : null}
        </div>
      ) : null}
      {pendingImg ? (
        <div className="margin-right">
          <img src={pendingImg} />
          <br />
          <div style={{ display: "flex" }}>
            <button onClick={runSave} className="btn btn-xs btn-light btn-square-icon">
              <i className="fal fa-check" />
            </button>
            <button
              className="btn btn-xs btn-light btn-square-icon"
              style={{ marginLeft: "auto" }}
              onClick={() => setUploadState({ pendingImg: "", uploadError: "" })}
            >
              <i className="fal fa-undo" />
            </button>
          </div>
        </div>
      ) : null}
      <div>
        <RemoteImageUpload _id={_id} remoteSave={remoteSave} onUpdate={setCurrentUrl} />
      </div>
    </div>
  );
};

export default ManageBookCover;
