// svelte-kit/src/lib/components/subjectsAndTags/tags/DisplaySelectedTags.svelte
<script lang="ts">
  import RemovableLabelDisplay from "../RemovableLabelDisplay.svelte";
  import LabelDisplay from "../LabelDisplay.svelte";
  import { tagsState } from "app/state/tagsState";
  import FlowItems from "../../layout/FlowItems.svelte";

  export let onRemove = null;
  export let currentlySelected;

  $: ({ tagHash } = $tagsState);
</script>

<FlowItems tightest={true}>
  {#each currentlySelected.filter(_id => tagHash[_id]).map(_id => tagHash[_id]) as t}
    {#if onRemove}
      <RemovableLabelDisplay item={t} doRemove={() => onRemove(t)} />
    {:else}
      <LabelDisplay item={t} />
    {/if}
  {/each}
</FlowItems>

// compare/react/app/components/displaySelectedTags.tsx
import React, { FunctionComponent, useContext } from "react";
import { RemovableLabelDisplay } from "./labelDisplay";
import { TagsContext } from "app/tagsState";

type LocalProps = { currentlySelected: string[]; onRemove: any };

const DisplaySelectedTags: FunctionComponent<LocalProps> = props => {
  const { tagHash } = useContext(TagsContext);

  return (
    <>
      {props.currentlySelected
        .map(_id => tagHash[_id])
        .map(t => (
          <RemovableLabelDisplay key={t._id} className="margin-right" style={{ marginTop: "5px" }} item={t} doRemove={() => props.onRemove(t)} />
        ))}
    </>
  );
};

export default DisplaySelectedTags;
