// svelte-kit/src/lib/components/Loading.svelte
<svelte:options runes={true} />

<script lang="ts">
  import { fade } from "svelte/transition";
</script>

<div class="fixed top-1/3 left-1/2 z-[99999] -translate-x-1/2 -translate-y-1/2" in:fade={{ delay: 50, duration: 200 }}>
  <i class="far fa-5x fa-spin fa-spinner text-primary-3 opacity-50"></i>
</div>

// react-redux/app/components/loading.tsx
import React from "react";

export default ({ ...rest }) => (
  <div {...rest} className="wait-for-loading">
    <i className="fa fa-5x fa-spin fa-spinner" />
  </div>
);

export const SectionLoading = ({ style = {}, ...rest }) => (
  <i
    style={{ position: "absolute", top: "50%", left: "50%", opacity: 0.2, transform: "translate(-50%,-50%)", ...style }}
    className="fa fa-5x fa-spin fa-spinner"
  />
);
