// svelte-kit/src/routes/(core-data)/books/SubjectEditModal.svelte
<script lang="ts">
  import Button from "$lib/components/buttons/Button.svelte";
  import Modal from "$lib/components/ui/Modal.svelte";

  import EditSubject from "$lib/components/subjectsAndTags/subjects/EditSubject.svelte";
  import SelectAvailableSubjects from "$lib/components/subjectsAndTags/subjects/SelectAvailableSubjects.svelte";
  import type { Color, Subject } from "$data/types";

  export let isOpen = false;
  export let onHide = () => {};

  export let colors: Color[];
  export let subjects: Subject[];

  const emptySubject = {
    id: 0,
    name: "",
    textColor: "",
    backgroundColor: "",
    path: ""
  };

  let editingSubject: Subject | null = null;

  const cancelEdit = () => (editingSubject = null);
  const newSubject = () => (editingSubject = emptySubject);
  const editSubject = (subject: Subject) => (editingSubject = subject);

  let deleteShowing: boolean = false;

  $: {
    if (isOpen) {
      cancelEdit();
    }
  }
</script>

<Modal {isOpen} {onHide} headerCaption="Edit Subjects">
  <div class="flex flex-col gap-3">
    {#if !deleteShowing}
      <div class="flex flex-col-reverse sm:flex-row gap-5">
        <SelectAvailableSubjects {subjects} placeholder="Edit subject" currentlySelected={[]} onSelect={item => editSubject(item)} />

        <Button class="sm:ml-auto flex flex-row gap-1" onClick={newSubject} preset="info-xs">
          <span>Add new subject </span>
          <i class="far fa-fw fa-plus-square" />
        </Button>
      </div>
    {/if}

    {#if editingSubject}
      <EditSubject {colors} allSubjects={subjects} bind:deleteShowing subject={editingSubject} onComplete={cancelEdit} onCancelEdit={cancelEdit} />
    {/if}
  </div>
</Modal>

// react/modules/books/components/subjectEditModal.tsx
import React, { FunctionComponent, useState } from "react";
import {Button} from "app/components/ui/Button";

import Modal from "app/components/ui/Modal";

import EditSubject from "app/components/subjectsAndTags/subjects/EditSubject";
import FlowItems from "app/components/layout/FlowItems";
import Stack from "app/components/layout/Stack";
import SelectAvailableSubjects from "app/components/subjectsAndTags/subjects/SelectAvailableSubjects";

interface ILocalProps {
  editModalOpen: boolean;
  stopEditing: any;
}

const SubjectEditModal: FunctionComponent<ILocalProps> = props => {
  const [editingSubject, setEditingSubject] = useState(null);

  const newSubject = () => startEditing({ name: "" });
  const editSubject = subject => {
    startEditing(subject);
  };
  const startEditing = subject => setEditingSubject(subject);
  const cancelEdit = () => setEditingSubject(null);

  return (
    <Modal isOpen={props.editModalOpen} onHide={props.stopEditing} headerCaption="Edit Subjects">
      <Stack>
        <FlowItems pushLast={true} xsFlowReverse={true}>
          <SelectAvailableSubjects placeholder="Edit subject" currentlySelected={[]} onSelect={item => editSubject(item)} />

          <Button onClick={newSubject} preset="info-xs">
            <span className="visible-xs">Add new subject </span>
            <i className="fa fa-fw fa-plus-square" />
          </Button>
        </FlowItems>

        {editingSubject ? <EditSubject subject={editingSubject} onCancelEdit={cancelEdit} /> : null}
        <hr />
      </Stack>
      <Button onClick={props.stopEditing}>Close</Button>
    </Modal>
  );
};

export default SubjectEditModal;
