// react-redux/modules/admin/components/bookSummaryCovers/coverManager.tsx
import React, { useState } from "react";
import { useQuery, buildQuery } from "micro-graphql-react";

import SummaryQuery from "graphQL/admin/bookSummaryCoverInfo.graphql";
import styles from "./styles.module.css";
const { bookList, bookDisplay, img, title } = styles;

import delve from "dlv";
import ajaxUtil from "util/ajaxUtil";
import { syncUpdates } from "util/graphqlHelpers";

export const updateSmallCover = ({ _id, url }) => {
  return ajaxUtil
    .post("/bookSummary/newSmallImage", { _id, url })
    .then(({ url, failure }) => {
      if (!failure && url) {
        syncUpdates(SummaryQuery, { _id, smallImage: url }, "allBookSummarys", "BookSummarys", { force: true });
      }
      return { url, failure };
    })
    .catch(() => ({ failure: true, url: "" }));
};

const BookSummaryDisplay = props => {
  const { book } = props;
  const [newUrl, setNewUrl] = useState("");

  const changeImg = evt => {
    evt.preventDefault();
    updateSmallCover({ _id: book._id, url: newUrl });
  };

  return (
    <div className={bookDisplay}>
      <div className={img}>
        <img src={book.smallImage} />
      </div>
      <div className={title}>
        <div>{book.title}</div>
        <form onSubmit={changeImg}>
          <div className="btn-group">
            <input className="form-control" placeholder="New Cover URL" onChange={evt => setNewUrl(evt.target.value)} />
            <button disabled={!newUrl} onClick={changeImg} className="btn btn-default">
              <i className="far fa-cloud-upload-alt" />
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default props => {
  const [missingCoversFilter, setMissingCoversFilter] = useState(true);

  const imgFilter = missingCoversFilter ? "nophoto" : void 0;

  const { data, loaded } = useQuery(buildQuery(SummaryQuery, { smallImage: imgFilter }));
  const bookSummaries = delve(data, "allBookSummarys.BookSummarys") || [];

  return (
    <div className={bookList}>
      <label>
        Books missing covers <input type="checkbox" checked={missingCoversFilter} onChange={evt => setMissingCoversFilter(evt.target.checked)} />
      </label>
      <br />
      <br />
      {loaded ? (
        <div>
          {bookSummaries.map(book => (
            <BookSummaryDisplay book={book} />
          ))}
        </div>
      ) : (
        <span>
          Loading ... <i className="fa fa-spinner fa-spin" />
        </span>
      )}
    </div>
  );
};

// svelte/modules/admin/book-covers/CoverManager.svelte
<script lang="ts">
  import { query } from "micro-graphql-svelte";
  import { Queries, QueryOf } from "graphQL/graphql-typings";

  import BookSummaryDisplay from "./BookSummaryDisplay.svelte";

  import SummaryQuery from "graphQL/admin/bookSummaryCoverInfo.graphql";

  import "./styles.scss";

  let missingCoversFilter = true;

  const imgFilter = missingCoversFilter ? "nophoto" : void 0;

  const { queryState, sync } = query<QueryOf<Queries["allBookSummarys"]>>(SummaryQuery);
  $: sync({ smallImage: imgFilter });

  $: ({ loaded, data } = $queryState);
  $: bookSummaries = data?.allBookSummarys?.BookSummarys ?? [];

  const setMissingCoversFilter = evt => (missingCoversFilter = evt.target.checked);
</script>

<div class="book-list">
  <label>
    Books missing covers <input type="checkbox" checked={missingCoversFilter} onChange={setMissingCoversFilter} />
  </label>
  <br />
  <br />
  {#if loaded}
    <div>
      {#each bookSummaries as book}
        <BookSummaryDisplay {book} />
      {/each}
    </div>
  {:else}
    <span>
      Loading ... <i class="far fa-spinner fa-spin" />
    </span>
  {/if}
</div>
