// react-redux/applicationRoot/components/displaySelectedSubjects.tsx
import React, { Component, FunctionComponent, useContext } from "react";
import { RemovableLabelDisplay } from "./labelDisplay";
import { SubjectsContext } from "applicationRoot/renderUI";

type LocalProps = { currentlySelected: string[]; onRemove: any };

const DisplaySelectedSubjects: FunctionComponent<LocalProps> = props => {
  const { subjectHash } = useContext(SubjectsContext);
  return (
    <>
      {props.currentlySelected
        .map(_id => subjectHash[_id])
        .map(t => (
          <RemovableLabelDisplay key={t._id} className="margin-left" item={t} doRemove={() => props.onRemove(t)} />
        ))}
    </>
  );
};

export default DisplaySelectedSubjects;

// svelte/app/components/subjectsAndTags/subjects/DisplaySelectedSubjects.svelte
<script lang="ts">
  import RemovableLabelDisplay from "../RemovableLabelDisplay.svelte";
  import LabelDisplay from "../LabelDisplay.svelte";
  import { subjectsState } from "app/state/subjectsState";
  import FlowItems from "../../layout/FlowItems.svelte";

  export let currentlySelected: any[];
  export let onRemove: any;

  $: ({ subjectHash } = $subjectsState);
</script>

<FlowItems tightest={true}>
  {#each currentlySelected.filter(_id => subjectHash[_id]).map(_id => subjectHash[_id]) as t}
    {#if onRemove}
      <RemovableLabelDisplay item={t} doRemove={() => onRemove(t)} />
    {:else}
      <LabelDisplay item={t} />
    {/if}
  {/each}
</FlowItems>
