// react-redux/modules/settings/components/passwordReset/main.js
import React, { Component } from 'react';
import {connect} from 'react-redux';
import {selector} from '../../reducers/publicUserSettings/reducer';
import * as actionCreators from '../../reducers/passwordReset/actionCreators';
import {AjaxButton} from 'applicationRoot/components/bootstrapButton';

@connect(() => ({}), {...actionCreators})
export default class PublicUserSettings extends Component {
    state = {saving: false, mismatch: false, wrongPassword: false, saved: false};
    resetPassword = () => {
        if (this.newPasswordEl.value != this.confirmPasswordEl.value){
            this.setState({mismatch: true});
            return;
        }
        this.setState({mismatch: false, saving: true, wrongPassword: false});
        Promise
            .resolve(this.props.resetPassword(this.currentPasswordEl.value, this.newPasswordEl.value))
            .then(res => {
                if (res.error == 1){
                    this.setState({wrongPassword: true});
                } else if (res.success) {
                    this.setState({saved: true});
                    setTimeout(() => this.setState({saved: false}), 2000);
                }
                this.setState({saving: false});
            });
    }
    render() {
        return (
            <div className='row' style={{position: 'relative'}}>
                <div className='col-md-6 col-sm-12'>
                    <div style={{padding: '10px'}}>
                        <h2>Reset your password</h2>
                        <div>
                            <div className="form-group">
                                <label htmlFor="existingPasswordInput">Current password</label>
                                <input ref={el => this.currentPasswordEl = el} type="password" className="form-control" id="existingPasswordInput" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="newPasswordInput">New password</label>
                                <input ref={el => this.newPasswordEl = el} type="password" className="form-control" id="newPasswordInput" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="confirmNewPasswordInput">Confirm new password</label>
                                <input ref={el => this.confirmPasswordEl = el} type="password" className="form-control" id="confirmNewPasswordInput" />
                            </div>
                        </div>
                        <AjaxButton onClick={this.resetPassword} disabled={this.state.saved} running={this.state.saving} runningText='Saving' preset='primary'>Save</AjaxButton>
                        {this.state.mismatch ? 
                            <div>
                                <br/>
                                <div className="alert alert-danger">
                                    Passwords must match
                                </div> 
                            </div>: null
                        }
                        {this.state.wrongPassword ? 
                            <div>
                                <br/>
                                <div className="alert alert-danger">
                                    Your existing password does not match
                                </div> 
                            </div>: null
                        }
                        {this.state.saved ? 
                            <div>
                                <br/>
                                <div className="alert alert-success">
                                    Your password has been updated
                                </div> 
                            </div>: null
                        }
                    </div>
                </div>
            </div>
        );
    }
}

// svelte/modules/settings/PasswordReset.svelte
<script lang="ts">
  import ajaxUtil from "util/ajaxUtil";

  import ActionButton from "app/components/buttons/ActionButton.svelte";
  import FlexRow from "app/components/layout/FlexRow.svelte";
  import Stack from "app/components/layout/Stack.svelte";
  import { appState } from "app/state/appState";

  const exectueResetPassword = (oldPassword, newPassword) => {
    return ajaxUtil.postAuth("/resetPassword", { oldPassword, newPassword }, resp => {});
  };

  $: ({ online } = $appState);
  let saving = false;

  let mismatch = false;
  let wrongPassword = false;
  let saved = false;

  let currentPassword = "";
  let newPassword = "";
  let confirmPassword = "";

  const resetPassword = evt => {
    evt?.preventDefault();
    if (newPassword != confirmPassword) {
      mismatch = true;
      return;
    }

    mismatch = false;
    wrongPassword = false;
    saving = true;

    return Promise.resolve(exectueResetPassword(currentPassword, newPassword)).then((res: any) => {
      if (res.error == 1) {
        wrongPassword = true;
      } else if (res.success) {
        currentPassword = "";
        newPassword = "";
        confirmPassword = "";

        saved = true;

        setTimeout(() => (saved = false), 2000);
      }
      saving = false;
    });
  };
</script>

<form on:submit={resetPassword}>
  <FlexRow>
    <div class="col-md-6 col-sm-12">
      <Stack>
        <div class="form-group">
          <label for="existingPasswordInput">Current password</label>
          <input bind:value={currentPassword} type="password" class="form-control" id="existingPasswordInput" />
        </div>
        <div class="form-group">
          <label for="newPasswordInput">New password</label>
          <input bind:value={newPassword} type="password" class="form-control" id="newPasswordInput" />
        </div>
        <div class="form-group">
          <label for="confirmNewPasswordInput">Confirm new password</label>
          <input bind:value={confirmPassword} type="password" class="form-control" id="confirmNewPasswordInput" />
        </div>
        <ActionButton
          style="align-self: flex-start; min-width: 10ch;"
          onClick={resetPassword}
          text="Save"
          disabled={saved}
          runningText="Saving"
          preset="primary"
        />

        {#if mismatch}
          <div>
            <br />
            <div class="alert alert-danger">Passwords must match</div>
          </div>
        {/if}
        {#if wrongPassword}
          <div>
            <br />
            <div class="alert alert-danger">Your existing password does not match</div>
          </div>
        {/if}
        {#if saved}
          <div>
            <br />
            <div class="alert alert-success">Your password has been updated</div>
          </div>
        {/if}
      </Stack>
    </div>
  </FlexRow>
</form>
