// react-redux/modules/home/components/tooltip.tsx
import React, { Component, PureComponent } from "react";

export default class Tooltip extends PureComponent<any, any> {
  render() {
    let { data, count, childSubjects, removeBar, drilldown, chartIndex } = this.props,
      display = data.entries
        .map(e => e.name)
        .sort()
        .join(",");

    return (
      <div style={{ position: "relative", marginLeft: "-5px" }}>
        <h4 className="heading">
          {display}: <span>{data.count}</span>
        </h4>
        <button className="btn btn-xs" onClick={this.props.removeBar}>
          <i className="far fa-undo" />
        </button>
        {childSubjects.length ? (
          <button className="btn btn-xs" style={{ marginLeft: "5px" }} onClick={() => drilldown(chartIndex, childSubjects, display)}>
            <i className="far fa-angle-double-down" />
          </button>
        ) : null}
      </div>
    );
  }
}

// svelte-kit/src/routes/(core-data)/(home)/data-vis/barChart/Tooltip.svelte
<script lang="ts">
  import type { Data, Position } from "./tooltip";

  export let position: Position;
  export let data: Data;
  export let drilldown: any;
  export let removeBar: (id: string) => void;

  const runDrilldown = () => drilldown(data.childSubjects, data.display);
</script>

<div class={"tooltip-root " + position}>
  <div class="content">
    <span class="name">{data.display}: {data.count}</span>
    <button class="raw-button flex" on:click={() => removeBar(data.groupId)}><i class="fad fa-times-circle" /></button>
  </div>

  {#if data.childSubjects?.length}
    <br />

    <button on:click={runDrilldown} class="gap-2 raw-button text-lg">
      <span class="leading-none">View</span>
      <i class="far fa-chart-bar leading-none" />
    </button>
  {/if}

  <div class={"arrow " + position} />
</div>
