// react-redux/modules/home/components/recommend/searchModal.tsx
import React, { FunctionComponent, useState, useContext, useEffect, useRef } from "react";

import Modal from "app/components/modal";
import SelectAvailableTags from "app/components/selectAvailableTags";
import DisplaySelectedTags from "app/components/displaySelectedTags";
import SelectAvailableSubjects from "app/components/selectAvailableSubjects";
import DisplaySelectedSubjects from "app/components/displaySelectedSubjects";

import { TransitionGroup, CSSTransition } from "react-transition-group";
import { SearchContext, ISearchBookRaw } from "modules/home/searchState";

interface LocalProps {
  isOpen: boolean;
  onHide: any;
  setBookSearchState: any;
  searchState: any;
  searchResults: any;
  dispatch: any;
  selectedBooksSet: any;
}

const SearchModal: FunctionComponent<Partial<LocalProps>> = props => {
  const { isOpen, onHide, setBookSearchState, searchState, searchResults, dispatch, selectedBooksSet } = props;

  const [subjects, setSubjects] = useState([]);
  const [tags, setTags] = useState([]);
  const { loading, loaded, data, error } = searchResults;

  useEffect(() => {
    if (props.isOpen) {
      setSubjects(searchState.subjects || []);
      setTags(searchState.tags || []);
    }
  }, [props.isOpen]);

  const selectSubject = subject => setSubjects(subjects.concat(subject._id));
  const selectTag = tag => setTags(tags.concat(tag._id));
  const removeSubject = subject => setSubjects(subjects.filter(_id => _id != subject._id));
  const removeTag = tag => setTags(tags.filter(_id => _id != tag._id));

  const searchEl = useRef(null);
  const childSubEl = useRef(null);
  const isReadE = useRef(null);
  const isRead0 = useRef(null);
  const isRead1 = useRef(null);

  const applyFilters = evt => {
    evt.preventDefault();
    setBookSearchState({
      title: searchEl.current.value || "",
      isRead: isReadE.current.checked ? void 0 : isRead0.current.checked ? false : true,
      subjects: subjects.length ? subjects : null,
      tags: tags.length ? tags : null,
      searchChildSubjects: childSubEl.current.checked
    });
  };
  return (
    <Modal {...{ isOpen, onHide, headerCaption: "Search your books" }}>
      <form onSubmit={applyFilters}>
        <div className="row">
          <div className="col-xs-6">
            <div className="form-group">
              <label>Title</label>
              <input defaultValue={searchState.title} ref={searchEl} placeholder="Search title" className="form-control" />
            </div>
          </div>

          <div className="col-xs-6">
            <label className="form-label">Is read?</label>
            <div className="radio responsive-radios">
              <span>
                <input type="radio" defaultChecked={searchState.isRead == null} ref={isReadE} name="isRead" id="isReadE" />
                <label htmlFor="isReadE">Either</label>
              </span>
              <span>
                <input type="radio" defaultChecked={searchState.isRead == "1"} ref={isRead1} name="isRead" id="isReadY" />
                <label htmlFor="isReadY">Yes</label>
              </span>
              <span>
                <input type="radio" defaultChecked={searchState.isRead == "0"} ref={isRead0} name="isRead" id="isReadN" />
                <label htmlFor="isReadN">No</label>
              </span>
            </div>
          </div>
        </div>
      </form>
      <div className="row" style={{ position: "relative" }}>
        <div className="col-xs-3">
          <SelectAvailableTags currentlySelected={tags} onSelect={selectTag} />
        </div>
        <div className="col-xs-9">
          <div>
            <DisplaySelectedTags currentlySelected={tags} onRemove={removeTag} />
          </div>
        </div>
      </div>
      <br />
      <>
        <div className="row" style={{ position: "relative" }}>
          <div className="col-xs-3">
            <SelectAvailableSubjects currentlySelected={subjects} onSelect={selectSubject} />
          </div>
          <div className="col-xs-9">
            <div>
              <DisplaySelectedSubjects currentlySelected={subjects} onRemove={removeSubject} />
            </div>
          </div>
        </div>
        <br />
        <div className="row" style={{ position: "relative" }}>
          <div className="col-xs-6">
            <div className="checkbox">
              <label>
                <input type="checkbox" ref={childSubEl} defaultChecked={!!searchState.searchChildSubjects} /> Also search child subjects
              </label>
            </div>
          </div>
          <div className="col-xs-12 margin-top">
            {loading ? (
              <button disabled={true} className="btn btn-default">
                <i className="fa fa-fw fa-spin fa-spinner" />
              </button>
            ) : (
              <button onClick={applyFilters} className="btn btn-default">
                <i className="fal fa-search" />
              </button>
            )}
          </div>
        </div>
      </>
      {loaded ? <SearchResults {...{ dispatch, loaded, loading, data, error, selectedBooksSet }} /> : null}
    </Modal>
  );
};

export default SearchModal;

const SearchResults = props => {
  const books = props.data.allBooks.Books;
  const { loading, selectedBooksSet } = props;

  return (
    <div style={{ maxHeight: "300px", overflowY: "auto", marginTop: "5px" }}>
      {books.length ? (
        <table className="table table-condensed table-striped">
          <thead>
            <tr>
              <th />
              <th />
              <th />
            </tr>
          </thead>
          <TransitionGroup component="tbody">
            {books
              .filter(b => !selectedBooksSet.has(b._id))
              .map(book => (
                <CSSTransition appear={false} enter={false} exit={!loading} classNames="fade-transition" timeout={300} key={book._id}>
                  <SearchResult key={book._id} book={book} dispatch={props.dispatch} />
                </CSSTransition>
              ))}
          </TransitionGroup>
        </table>
      ) : (
        <div className="alert alert-warning">No results</div>
      )}
    </div>
  );
};

const SearchResult = props => {
  const [adding, setAdding] = useState(false);

  const selectBook = () => {
    setAdding(true);
    props.dispatch(["selectBook", props.book]);
  };

  let { book } = props;
  return (
    <tr>
      <td>
        <button disabled={adding} onClick={selectBook} style={{ cursor: "pointer", whiteSpace: "nowrap" }} className="btn btn-primary btn-xs">
          Add to list&nbsp;
          <i className="fal fa-plus" />
        </button>
      </td>
      <td>
        <img src={book.smallImage} />
      </td>
      <td>
        {book.title}
        {book.authors && book.authors.length ? (
          <>
            <br />
            <span style={{ fontStyle: "italic" }}>{book.authors.join(", ")}</span>
          </>
        ) : null}
      </td>
    </tr>
  );
};

// svelte/modules/home/recommendations/SearchModal.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Modal from "app/components/ui/Modal.svelte";
  import FlexRow from "app/components/layout/FlexRow.svelte";
  import Stack from "app/components/layout/Stack.svelte";
  import FlowItems from "app/components/layout/FlowItems.svelte";
  import SelectAvailableTags from "app/components/subjectsAndTags/tags/SelectAvailableTags.svelte";
  import SelectAvailableSubjects from "app/components/subjectsAndTags/subjects/SelectAvailableSubjects.svelte";
  import DisplaySelectedTags from "app/components/subjectsAndTags/tags/DisplaySelectedTags.svelte";
  import DisplaySelectedSubjects from "app/components/subjectsAndTags/subjects/DisplaySelectedSubjects.svelte";
  import ActionButton from "app/components/buttons/ActionButton.svelte";
  import SearchResults from "./SearchResults.svelte";

  export let isOpen;
  export let onHide;
  export let dispatch;
  export let selectedBooksSet;
  export let searchState;
  export let queryState;
  export let searchDispatch;

  //const focus = el => { setTimeout(() => el.focus()); } 
  let titleEl;

  $: ({ active } = $searchState);
  let { ...initialSearchState } = $searchState;
  let searchChild = !!initialSearchState.searchChildSubjects;
  let isRead = initialSearchState.isRead === true ? "1" : initialSearchState.isRead === false ? "0" : "null";
  let title = initialSearchState.title;
  let subjects = initialSearchState.subjects ?? [];
  let tags = initialSearchState.tags ?? [];

  $: ({ pageSize, page } = $searchState);

  $: ({ loaded, loading, data, error, currentQuery } = $queryState);

  $: resultCount = data?.allBooks?.Meta?.count ?? 0;
  $: totalPages = Math.ceil(resultCount / pageSize);

  const pageUp = () => searchDispatch({ page: page + 1 });
  const pageDown = () => searchDispatch({ page: page - 1 });
  const pageOne = () => searchDispatch({ page: 1 });
  const pageLast = () => searchDispatch({ page: totalPages });

  $: canPageUp = !loading && page < totalPages;
  $: canPageDown = !loading && page > 1;

  $: allBooks = data?.allBooks?.Books;
  $: noAvailableBooks = allBooks?.length && !allBooks.find(b => !selectedBooksSet.has(b._id));

  const selectSubject = subject => (subjects = subjects.concat(subject._id));
  const selectTag = tag => (tags = tags.concat(tag._id));
  const removeSubject = subject => (subjects = subjects.filter(_id => _id != subject._id));
  const removeTag = tag => (tags = tags.filter(_id => _id != tag._id));

  const applyFilters = () => {
    searchDispatch({
      title,
      isRead: isRead == "null" ? void 0 : isRead == "0" ? false : true,
      subjects: subjects.length ? subjects : null,
      tags: tags.length ? tags : null,
      searchChildSubjects: searchChild
    });
  };
</script>

<Modal onModalMount={() => titleEl.focus()} deferStateChangeOnClose={true} standardFooter={false} {isOpen} {onHide} headerCaption="Search your books">
  <form
    on:submit={evt => {
      evt.preventDefault();
      applyFilters();
    }}
  >
    <FlexRow>
      <div class="col-xs-6">
        <div class="form-group">
          <label>Title</label>
          <input bind:this={titleEl} placeholder="Search title" class="form-control" />
        </div>
      </div>

      <div class="col-xs-6">
        <Stack>
          <label class="form-label">Is read?</label>
          <FlowItems class="radio">
            <FlowItems tightest={true} vCenter={true}>
              <input type="radio" bind:group={isRead} value="null" name="isRead" id="isReadE" />
              <label for="isReadE">Either</label>
            </FlowItems>
            <FlowItems tightest={true} vCenter={true}>
              <input type="radio" bind:group={isRead} value="1" name="isRead" id="isReadY" />
              <label for="isReadY">Yes</label>
            </FlowItems>
            <FlowItems tightest={true} vCenter={true}>
              <input type="radio" bind:group={isRead} value="0" name="isRead" id="isReadN" />
              <label for="isReadN">No</label>
            </FlowItems>
          </FlowItems>
        </Stack>
      </div>

      <div class="col-xs-3">
        <SelectAvailableTags currentlySelected={tags} onSelect={selectTag} />
      </div>
      <div class="col-xs-9">
        <DisplaySelectedTags currentlySelected={tags} onRemove={removeTag} />
      </div>

      <div class="col-xs-3">
        <SelectAvailableSubjects currentlySelected={subjects} onSelect={selectSubject} />
      </div>
      <div class="col-xs-9">
        <DisplaySelectedSubjects currentlySelected={subjects} onRemove={removeSubject} />
      </div>

      <div class="col-xs-6">
        <div class="checkbox"><label> <input type="checkbox" bind:checked={searchChild} /> Also search child subjects </label></div>
      </div>

      <div class="col-xs-12">
        <FlexRow>
          {#if loading}
            <button style="width: 6ch" disabled={true} class="btn btn-default"><i class="fa fa-fw fa-spin fa-spinner" /></button>
          {:else}
            <ActionButton onClick={applyFilters} class="btn btn-default">Go</ActionButton>
            <!-- <SubmitIconButton style={{ width: '6ch' }} key={1} class="btn btn-default"><i class="fal fa-search" /></SubmitIconButton> -->
          {/if}

          {#if noAvailableBooks}
            <div style="font-size: 18px" class="alert alert-info alert-slimmer">You've added all of the books from this page</div>
          {/if}
        </FlexRow>
      </div>

      <div class="col-xs-12">
        <div>
          {#if resultCount}
            <FlowItems tightest={true} containerStyle="align-items: center; font-size: 14px">
              <button on:click={pageOne} disabled={!canPageDown} class="btn btn-default"> <i class="fal fa-angle-double-left" /> </button>
              <button on:click={pageDown} disabled={!canPageDown} class="btn btn-default"> <i class="fal fa-angle-left" /> </button>
              <span style="padding-left: 3px; padding-right: 3px"> {page} of {totalPages} </span>
              <button on:click={pageUp} disabled={!canPageUp} class="btn btn-default"> <i class="fal fa-angle-right" /> </button>
              <button on:click={pageLast} disabled={!canPageUp} class="btn btn-default"> <i class="fal fa-angle-double-right" /> </button>
            </FlowItems>
            <hr />
          {/if}
        </div>
        <SearchResults {dispatch} {data} {selectedBooksSet} {active} />
      </div>
    </FlexRow>
  </form>
</Modal>
