// react/modules/home/components/recommend/searchModal.tsx
import React, { FunctionComponent, useState, useRef, useMemo, useContext, useReducer, useLayoutEffect } from "react";

import Modal from "app/components/ui/Modal";
import SelectAvailableTags from "app/components/subjectsAndTags/tags/SelectAvailableTags";
import DisplaySelectedTags from "app/components/subjectsAndTags/tags/DisplaySelectedTags";
import SelectAvailableSubjects from "app/components/subjectsAndTags/subjects/SelectAvailableSubjects";
import DisplaySelectedSubjects from "app/components/subjectsAndTags/subjects/DisplaySelectedSubjects";

import { TransitionGroup, CSSTransition } from "react-transition-group";
import FlexRow from "app/components/layout/FlexRow";
import Stack from "app/components/layout/Stack";
import FlowItems from "app/components/layout/FlowItems";
import { CoverSmall } from "app/components/bookCoverComponent";
import { Form, SubmitIconButton } from "app/components/ui/Form";
import { SlideInContents } from "app/animationHelpers";

import "./recommend.scss";
import { AppContext } from "app/renderUI";
import { useQuery } from "micro-graphql-react";
import { QueryOf, Queries } from "graphql-typings";

import BooksQuery from "graphQL/home/searchBooks.graphql";

const PAGE_SIZE = 4;

interface LocalProps {
  isOpen: boolean;
  onHide: any;
  setBookSearchState: any;
  dispatch: any;
  selectedBooksSet: any;
}

const initialState = { active: false, page: 1, pageSize: 50, sort: { title: 1 }, tags: [], subjects: [] };
const searchStateReducer = (_oldState, payload) => (payload ? { active: true, page: 1, pageSize: PAGE_SIZE, ...payload } : initialState);

const SearchModal: FunctionComponent<Partial<LocalProps>> = props => {
  const [{ publicUserId }] = useContext(AppContext);
  const [{ active, ...searchState }, searchDispatch] = useReducer(searchStateReducer, initialState);

  const variables = { ...searchState, publicUserId };
  const { page } = variables;

  const { loading, loaded, data, error, currentQuery } = useQuery<QueryOf<Queries["allBooks"]>>(BooksQuery, variables, { active });
  const resultCount = data?.allBooks?.Meta?.count ?? 0;
  const totalPages = Math.ceil(resultCount / PAGE_SIZE);

  const { isOpen, onHide, dispatch, selectedBooksSet } = props;

  const pageUp = () => searchDispatch({ page: page + 1 });
  const pageDown = () => searchDispatch({ page: page - 1 });
  const pageOne = () => searchDispatch({ page: 1 });
  const pageLast = () => searchDispatch({ page: totalPages });

  let canPageUp = page < totalPages;
  let canPageDown = page > 1;
  let canPageOne = page > 1;
  let canPageLast = page < totalPages;

  const [subjects, setSubjects] = useState([]);
  const [tags, setTags] = useState([]);

  const noAvailableBooks = useMemo(() => {
    const allBooks = data?.allBooks?.Books;

    return allBooks?.length && !allBooks.find(b => !selectedBooksSet.has(b._id));
  }, [selectedBooksSet, data]);

  useLayoutEffect(() => {
    if (props.isOpen) {
      setSubjects(searchState.subjects || []);
      setTags(searchState.tags || []);
      searchDispatch(null);
    }
  }, [props.isOpen]);

  const selectSubject = subject => setSubjects(subjects.concat(subject._id));
  const selectTag = tag => setTags(tags.concat(tag._id));
  const removeSubject = subject => setSubjects(subjects.filter(_id => _id != subject._id));
  const removeTag = tag => setTags(tags.filter(_id => _id != tag._id));

  const searchEl = useRef(null);
  const childSubEl = useRef(null);
  const isReadE = useRef(null);
  const isRead0 = useRef(null);
  const isRead1 = useRef(null);

  const applyFilters = () => {
    searchDispatch({
      title: searchEl.current.value || "",
      isRead: isReadE.current.checked ? void 0 : isRead0.current.checked ? false : true,
      subjects: subjects.length ? subjects : null,
      tags: tags.length ? tags : null,
      searchChildSubjects: childSubEl.current.checked
    });
  };

  return (
    <Modal {...{ isOpen, onHide, headerCaption: "Search your books" }}>
      <Form submit={applyFilters}>
        <FlexRow>
          <div className="col-xs-6">
            <div className="form-group">
              <label>Title</label>
              <input defaultValue={searchState.title} ref={searchEl} placeholder="Search title" className="form-control" />
            </div>
          </div>

          <div className="col-xs-6">
            <Stack>
              <label className="form-label">Is read?</label>
              <FlowItems className="radio">
                <FlowItems tightest={true} vCenter={true}>
                  <input type="radio" defaultChecked={searchState.isRead == null} ref={isReadE} name="isRead" id="isReadE" />
                  <label htmlFor="isReadE">Either</label>
                </FlowItems>
                <FlowItems tightest={true} vCenter={true}>
                  <input type="radio" defaultChecked={searchState.isRead == "1"} ref={isRead1} name="isRead" id="isReadY" />
                  <label htmlFor="isReadY">Yes</label>
                </FlowItems>
                <FlowItems tightest={true} vCenter={true}>
                  <input type="radio" defaultChecked={searchState.isRead == "0"} ref={isRead0} name="isRead" id="isReadN" />
                  <label htmlFor="isReadN">No</label>
                </FlowItems>
              </FlowItems>
            </Stack>
          </div>

          <div className="col-xs-3">
            <SelectAvailableTags currentlySelected={tags} onSelect={selectTag} />
          </div>
          <div className="col-xs-9">
            <DisplaySelectedTags currentlySelected={tags} onRemove={removeTag} />
          </div>

          <div className="col-xs-3">
            <SelectAvailableSubjects currentlySelected={subjects} onSelect={selectSubject} />
          </div>
          <div className="col-xs-9">
            <DisplaySelectedSubjects currentlySelected={subjects} onRemove={removeSubject} />
          </div>

          <div className="col-xs-6">
            <div className="checkbox">
              <label>
                <input type="checkbox" ref={childSubEl} defaultChecked={!!searchState.searchChildSubjects} /> Also search child subjects
              </label>
            </div>
          </div>

          <div className="col-xs-12">
            <FlexRow>
              {loading ? (
                <button style={{ minWidth: "5ch" }} disabled={true} className="btn btn-default">
                  <i className="fa fa-fw fa-spin fa-spinner" />
                </button>
              ) : (
                <SubmitIconButton key={1} className="btn btn-default">
                  <i className="fal fa-search" />
                </SubmitIconButton>
              )}

              <CSSTransition in={noAvailableBooks} key={2} classNames="bl-animate" timeout={300}>
                <div className="bl-fade alert alert-info alert-slimmer">You've added all of the books from these results</div>
              </CSSTransition>
            </FlexRow>
          </div>

          <div className="col-xs-12">
            <div>
              {resultCount ? (
                <>
                  <FlowItems tightest={true} containerStyle={{ alignItems: "center", fontSize: "14px" }}>
                    <button onClick={pageOne} disabled={!canPageDown} className="btn btn-default">
                      <i className="fal fa-angle-double-left" />
                    </button>
                    <button onClick={pageDown} disabled={!canPageDown} className="btn btn-default">
                      <i className="fal fa-angle-left" />
                    </button>
                    <span style={{ paddingLeft: "3px", paddingRight: "3px" }}>
                      {page} of {totalPages}
                    </span>
                    <button onClick={pageUp} disabled={!canPageUp} className="btn btn-default">
                      <i className="fal fa-angle-right" />
                    </button>
                    <button onClick={pageLast} disabled={!canPageUp} className="btn btn-default">
                      <i className="fal fa-angle-double-right" />
                    </button>
                  </FlowItems>
                  <hr />
                </>
              ) : null}
            </div>
            <SearchResults {...{ dispatch, loaded, loading, data, error, currentQuery, selectedBooksSet, active }} />
          </div>
        </FlexRow>
      </Form>
    </Modal>
  );
};

export default SearchModal;

const SearchResults = props => {
  const books = props?.data?.allBooks?.Books;
  const { loading, selectedBooksSet, currentQuery, active } = props;
  const availableBooks = books?.filter(b => !selectedBooksSet.has(b._id));
  const currentBooksRef = useRef<any>();
  currentBooksRef.current = availableBooks;

  return (
    <div className="animate-height animate-fast" style={{ maxHeight: "300px", overflowY: "auto", marginTop: "5px", position: "relative" }}>
      <div className="overlay-holder">
        <TransitionGroup component={null}>
          {books == null || !active ? null : books?.length ? (
            <SlideInContents className="search-modal-result-set" animateMountingOnly={true} key={currentQuery}>
              <ul>
                <TransitionGroup component={null}>
                  {availableBooks.map(book => (
                    <SlideInContents key={book._id} component="li" className="bl-no-animate-in animate-fast bl-fade-out bl-slide-out">
                      <SearchResult key={book._id} book={book} dispatch={props.dispatch} />
                    </SlideInContents>
                  ))}
                </TransitionGroup>
              </ul>
            </SlideInContents>
          ) : (
            <CSSTransition key={3} classNames="bl-animate" timeout={300}>
              <div style={{ alignSelf: "start" }} className="animate-fast bl-fade alert alert-warning">
                No results
              </div>
            </CSSTransition>
          )}
        </TransitionGroup>
      </div>
    </div>
  );
};

const SearchResult = props => {
  const [adding, setAdding] = useState(false);

  const selectBook = () => {
    setAdding(true);
    props.dispatch(["selectBook", props.book]);
  };

  let { book } = props;
  return (
    <Stack className={props.className}>
      <FlowItems>
        <div style={{ minWidth: "70px" }}>
          <CoverSmall url={book.smallImage} />
        </div>

        <Stack style={{ flex: 1 }}>
          {book.title}
          {book.authors && book.authors.length ? <span style={{ fontStyle: "italic", fontSize: "14px" }}>{book.authors.join(", ")}</span> : null}
          <button
            disabled={adding}
            onClick={selectBook}
            style={{ cursor: "pointer", marginTop: "auto", alignSelf: "flex-start" }}
            className="btn btn-primary btn-xs"
          >
            Add to list&nbsp;
            <i className="fal fa-plus" />
          </button>
        </Stack>
      </FlowItems>
      <hr />
    </Stack>
  );
};

// svelte/modules/home/recommendations/SearchModal.svelte
<script context="module" lang="ts">
  const PAGE_SIZE = 20;

  const initialReducerState: any = { active: false, page: 1, pageSize: 50, sort: { title: 1 }, tags: [], subjects: [] };
  const searchStateReducer = (_oldState, payload) => (payload ? { active: true, page: 1, pageSize: PAGE_SIZE, ...payload } : initialReducerState);
</script>

<script lang="ts">
  import { quadIn, quadOut, quintIn, quintOut } from "svelte/easing";
  import { springIn } from "svelte-helpers/spring-transitions";

  import BooksQuery from "graphQL/home/searchBooks.graphql";

  import Modal from "app/components/ui/Modal.svelte";
  import ActionIconButton from "app/components/buttons/ActionIconButton.svelte";
  import FlexRow from "app/components/layout/FlexRow.svelte";
  import Stack from "app/components/layout/Stack.svelte";
  import FlowItems from "app/components/layout/FlowItems.svelte";
  import SelectAvailableTags from "app/components/subjectsAndTags/tags/SelectAvailableTags.svelte";
  import SelectAvailableSubjects from "app/components/subjectsAndTags/subjects/SelectAvailableSubjects.svelte";
  import DisplaySelectedTags from "app/components/subjectsAndTags/tags/DisplaySelectedTags.svelte";
  import DisplaySelectedSubjects from "app/components/subjectsAndTags/subjects/DisplaySelectedSubjects.svelte";
  import SearchResults from "./SearchResults.svelte";
  import useReducer from "util/useReducer";
  import { query } from "micro-graphql-svelte";
  import { Queries, QueryOf } from "graphql-typings";
  import { appState } from "app/state/appState";

  export let isOpen;
  export let onHide;
  export let dispatch;
  export let selectedBooksSet;

  const { publicUserId } = $appState;

  const [reducerState, searchDispatch] = useReducer(searchStateReducer, initialReducerState);
  $: ({ active, ...searchState } = $reducerState);

  $: variables = { ...searchState, publicUserId };
  $: ({ page } = variables);

  const { queryState, sync } = query<QueryOf<Queries["allBooks"]>>(BooksQuery);
  $: {
    if (active) {
      sync(variables);
    }
  }

  let titleEl;
  let searchChild = false;
  let isRead = "null";
  let title = "";
  let subjects = [];
  let tags = [];

  $: ({ loaded, loading, data, error, currentQuery } = $queryState);

  $: booksObj = data?.allBooks as { Books: any[] };
  $: books = data?.allBooks?.Books;

  $: noResults = active && books != null && !books?.length;

  $: resultCount = data?.allBooks?.Meta?.count ?? 0;
  $: totalPages = Math.ceil(resultCount / PAGE_SIZE);

  const pageUp = () => searchDispatch({ page: page + 1 });
  const pageDown = () => searchDispatch({ page: page - 1 });
  const pageOne = () => searchDispatch({ page: 1 });
  const pageLast = () => searchDispatch({ page: totalPages });

  $: canPageUp = !loading && page < totalPages;
  $: canPageDown = !loading && page > 1;

  $: allBooks = data?.allBooks?.Books;
  $: noAvailableBooks = allBooks?.length && !allBooks.find(b => !selectedBooksSet.has(b._id));

  const selectSubject = subject => (subjects = subjects.concat(subject._id));
  const selectTag = tag => (tags = tags.concat(tag._id));
  const removeSubject = subject => (subjects = subjects.filter(_id => _id != subject._id));
  const removeTag = tag => (tags = tags.filter(_id => _id != tag._id));

  const applyFilters = () => {
    searchDispatch({
      title,
      isRead: isRead == "null" ? void 0 : isRead == "0" ? false : true,
      subjects: subjects.length ? subjects : null,
      tags: tags.length ? tags : null,
      searchChildSubjects: searchChild
    });
  };

  const NO_RESULTS_SPRING = { stiffness: 0.2, damping: 0.5 };
  const resultsMessageIn: any = () => {
    const { duration, tickToValue } = springIn(30, 0, NO_RESULTS_SPRING);
    return {
      duration,
      css: t => `transform: translate3d(${tickToValue(t)}px, 0, 0); opacity: ${quintOut(t)}`
    };
  };
  const resultsMessageOut: any = () => {
    return {
      duration: 150,
      css: t => `position: absolute; opacity: ${quadIn(t)}`
    };
  };
</script>

<style>
  .msg-holder {
    display: flex;
    position: relative;
    flex: 1;
    align-self: stretch;
  }

  .msg-holder > div {
    /* prevent shift after in transition */
    transform: translate3d(0, 0, 0);
  }
</style>

<Modal onModalMount={() => titleEl.focus()} standardFooter={false} {isOpen} {onHide} headerCaption="Search your books">
  <form
    on:submit={evt => {
      evt.preventDefault();
      applyFilters();
    }}
  >
    <FlexRow>
      <div class="col-xs-6">
        <div class="form-group">
          <label>Title</label>
          <input bind:this={titleEl} bind:value={title} placeholder="Search title" class="form-control" />
        </div>
      </div>

      <div class="col-xs-6">
        <Stack>
          <label class="form-label">Is read?</label>
          <FlowItems class="radio">
            <FlowItems tightest={true} vCenter={true}>
              <input type="radio" bind:group={isRead} value="null" name="isRead" id="isReadE" />
              <label for="isReadE">Either</label>
            </FlowItems>
            <FlowItems tightest={true} vCenter={true}>
              <input type="radio" bind:group={isRead} value="1" name="isRead" id="isReadY" />
              <label for="isReadY">Yes</label>
            </FlowItems>
            <FlowItems tightest={true} vCenter={true}>
              <input type="radio" bind:group={isRead} value="0" name="isRead" id="isReadN" />
              <label for="isReadN">No</label>
            </FlowItems>
          </FlowItems>
        </Stack>
      </div>

      <div class="col-xs-3">
        <SelectAvailableTags currentlySelected={tags} onSelect={selectTag} />
      </div>
      <div class="col-xs-9">
        <DisplaySelectedTags currentlySelected={tags} onRemove={removeTag} />
      </div>

      <div class="col-xs-3">
        <SelectAvailableSubjects currentlySelected={subjects} onSelect={selectSubject} />
      </div>
      <div class="col-xs-9">
        <DisplaySelectedSubjects currentlySelected={subjects} onRemove={removeSubject} />
      </div>

      <div class="col-xs-6">
        <div class="checkbox"><label> <input type="checkbox" bind:checked={searchChild} /> Also search child subjects </label></div>
      </div>

      <div class="col-xs-12">
        <FlexRow>
          <ActionIconButton class="btn btn-default" onClick={applyFilters} disabled={loading}>
            <i class:fa-spin={loading} class:fa-spinner={loading} class:fa-search={!loading} class="fal fa-fw" />
          </ActionIconButton>

          <div class="msg-holder">
            {#if noAvailableBooks}
              <div in:resultsMessageIn out:resultsMessageOut class="alert alert-info alert-slimmer">You've added all of the books from this page</div>
            {/if}

            {#if noResults}
              <div in:resultsMessageIn out:resultsMessageOut class="alert alert-warning alert-slimmer">No results</div>
            {/if}
          </div>
        </FlexRow>
      </div>

      <div class="col-xs-12">
        <div>
          {#if resultCount}
            <FlowItems tightest={true} containerStyle="align-items: center; font-size: 14px">
              <button on:click={pageOne} disabled={!canPageDown} class="btn btn-default"> <i class="fal fa-angle-double-left" /> </button>
              <button on:click={pageDown} disabled={!canPageDown} class="btn btn-default"> <i class="fal fa-angle-left" /> </button>
              <span style="padding-left: 3px; padding-right: 3px"> {page} of {totalPages} </span>
              <button on:click={pageUp} disabled={!canPageUp} class="btn btn-default"> <i class="fal fa-angle-right" /> </button>
              <button on:click={pageLast} disabled={!canPageUp} class="btn btn-default"> <i class="fal fa-angle-double-right" /> </button>
            </FlowItems>
            <hr />
          {/if}
        </div>
        <SearchResults {dispatch} {booksObj} {selectedBooksSet} />
      </div>
    </FlexRow>
  </form>
</Modal>
