// svelte-kit/src/routes/(core-data)/(home)/data-vis/barChart/axis/Axis.svelte
<script lang="ts">
  import { spring } from "svelte/motion";
  import Tick from "./Tick.svelte";

  export let transform: any;
  export let data: any[];
  export let graphWidth: any;
  export let scaleX: any;
  export let masterTransformX: any;
  export let masterTransformY: any;

  let axisSpring = spring({ width: graphWidth, masterTransformX, masterTransformY }, { stiffness: 0.1, damping: 0.4 });
  $: axisSpring.update(state => ({ ...state, width: graphWidth, masterTransformX, masterTransformY }));
</script>

<g transform={`translate(${$axisSpring.masterTransformX}, ${$axisSpring.masterTransformY})`}>
  <g {transform}>
    <path fill="none" stroke="black" d="M50.5,6 V0.5 H{$axisSpring.width - 1} V 6" />
    {#each data as d (d)}
      <Tick {scaleX} {d} />
    {/each}
  </g>
</g>

// react/modules/home/components/axis.tsx
import React, { Component } from "react";

const Axis = props => {
  let { children, scale, graphWidth, data, scaleX, ...rest } = props;
  return (
    <g fontSize="10" {...rest} transform={props.transform}>
      <path fill="none" stroke="black" d={`M0.5,6 V0.5 H${props.graphWidth + 0.5} V 6`} />
      {data.map(d => {
        let x = scaleX(d.display);
        let width = scaleX.bandwidth();
        let translateX = x + width / 2;

        return (
          <g transform={`translate(${translateX}, 0)`}>
            <line stroke="#000" y1="0" y2="6" x1="0" x2="0"></line>
            <text fill="#000" style={{ textAnchor: "end" }} transform="translate(0, 10) rotate(300)">
              {d.display}
            </text>
          </g>
        );
      })}
    </g>
  );
};

export default Axis;
