// svelte/modules/settings/PasswordReset.svelte
<script lang="ts">
  import ajaxUtil from "util/ajaxUtil";

  import ActionButton from "app/components/buttons/ActionButton.svelte";
  import FlexRow from "app/components/layout/FlexRow.svelte";
  import Stack from "app/components/layout/Stack.svelte";
  import { appState } from "app/state/appState";

  const exectueResetPassword = (oldPassword, newPassword) => {
    return ajaxUtil.postAuth("/resetPassword", { oldPassword, newPassword }, resp => {});
  };

  $: ({ online } = $appState);
  let saving = false;

  let mismatch = false;
  let wrongPassword = false;
  let saved = false;

  let currentPassword = "";
  let newPassword = "";
  let confirmPassword = "";

  const resetPassword = evt => {
    evt?.preventDefault();
    if (newPassword != confirmPassword) {
      mismatch = true;
      return;
    }

    mismatch = false;
    wrongPassword = false;
    saving = true;

    return Promise.resolve(exectueResetPassword(currentPassword, newPassword)).then((res: any) => {
      if (res.error == 1) {
        wrongPassword = true;
      } else if (res.success) {
        currentPassword = "";
        newPassword = "";
        confirmPassword = "";

        saved = true;

        setTimeout(() => (saved = false), 2000);
      }
      saving = false;
    });
  };
</script>

<form on:submit={resetPassword}>
  <FlexRow>
    <div class="col-md-6 col-sm-12">
      <Stack>
        <div class="form-group">
          <label for="existingPasswordInput">Current password</label>
          <input bind:value={currentPassword} type="password" class="form-control" id="existingPasswordInput" />
        </div>
        <div class="form-group">
          <label for="newPasswordInput">New password</label>
          <input bind:value={newPassword} type="password" class="form-control" id="newPasswordInput" />
        </div>
        <div class="form-group">
          <label for="confirmNewPasswordInput">Confirm new password</label>
          <input bind:value={confirmPassword} type="password" class="form-control" id="confirmNewPasswordInput" />
        </div>
        <ActionButton
          style="align-self: flex-start; min-width: 10ch;"
          onClick={resetPassword}
          text="Save"
          disabled={saved}
          runningText="Saving"
          preset="primary"
        />

        {#if mismatch}
          <div>
            <br />
            <div class="alert alert-danger">Passwords must match</div>
          </div>
        {/if}
        {#if wrongPassword}
          <div>
            <br />
            <div class="alert alert-danger">Your existing password does not match</div>
          </div>
        {/if}
        {#if saved}
          <div>
            <br />
            <div class="alert alert-success">Your password has been updated</div>
          </div>
        {/if}
      </Stack>
    </div>
  </FlexRow>
</form>

// react/modules/settings/components/passwordReset/main.tsx
import React, { useState, useRef, useContext } from "react";
import { ActionButton } from "app/components/ui/Button";
import ajaxUtil from "util/ajaxUtil";
import { AppContext } from "app/state/appState";
import FlexRow from "app/components/layout/FlexRow";
import Stack from "app/components/layout/Stack";

import { Form } from "app/components/ui/Form";

const exectueResetPassword = (oldPassword, newPassword) => {
  return ajaxUtil.postAuth("/resetPassword", { oldPassword, newPassword }, resp => {});
};

const PublicUserSettings = props => {
  const [{ online }] = useContext(AppContext);
  const newPasswordEl = useRef(null);
  const confirmPasswordEl = useRef(null);
  const currentPasswordEl = useRef(null);
  const [saving, setSaving] = useState(false);
  const [mismatch, setMismatch] = useState(false);
  const [wrongPassword, setWrongPassword] = useState(false);
  const [saved, setSaved] = useState(false);

  const resetPassword = () => {
    if (newPasswordEl.current.value != confirmPasswordEl.current.value) {
      setMismatch(true);
      return;
    }

    setMismatch(false);
    setSaving(true);
    setWrongPassword(false);

    return Promise.resolve(exectueResetPassword(currentPasswordEl.current.value, newPasswordEl.current.value)).then((res: any) => {
      if (res.error == 1) {
        setWrongPassword(true);
      } else if (res.success) {
        currentPasswordEl.current.value = "";
        newPasswordEl.current.value = "";
        confirmPasswordEl.current.value = "";
        setSaved(true);
        setTimeout(() => setSaved(false), 2000);
      }
      setSaving(false);
    });
  };

  if (!online) {
    return <h1>Offline</h1>;
  }

  return (
    <Form submit={resetPassword}>
      <FlexRow>
        <div className="col-md-6 col-sm-12">
          <Stack>
            <div className="form-group">
              <label htmlFor="existingPasswordInput">Current password</label>
              <input ref={currentPasswordEl} type="password" className="form-control" id="existingPasswordInput" />
            </div>
            <div className="form-group">
              <label htmlFor="newPasswordInput">New password</label>
              <input ref={newPasswordEl} type="password" className="form-control" id="newPasswordInput" />
            </div>
            <div className="form-group">
              <label htmlFor="confirmNewPasswordInput">Confirm new password</label>
              <input ref={confirmPasswordEl} type="password" className="form-control" id="confirmNewPasswordInput" />
            </div>
            <ActionButton
              style={{ alignSelf: "flex-start", minWidth: "10ch" }}
              onClick={resetPassword}
              text="Save"
              disabled={saved}
              runningText="Saving"
              preset="primary"
            />

            {mismatch ? (
              <div>
                <br />
                <div className="alert alert-danger">Passwords must match</div>
              </div>
            ) : null}
            {wrongPassword ? (
              <div>
                <br />
                <div className="alert alert-danger">Your existing password does not match</div>
              </div>
            ) : null}
            {saved ? (
              <div>
                <br />
                <div className="alert alert-success">Your password has been updated</div>
              </div>
            ) : null}
          </Stack>
        </div>
      </FlexRow>
    </Form>
  );
};

export default PublicUserSettings;
