// svelte/modules/books/menuBar/MenuBar.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import cn from "classnames";
  import "./menu-bar-styles.scss";

  import measureHeight from "util/measureHeight";

  import ActiveSearchFilters from "./ActiveSearchFilters.svelte";
  import { currentSearch as bookSearchState } from "../booksSearchState";
  import { getBookSearchUiView } from "../booksUiState";
  import PagingButtons from "./PagingButtons.svelte";
  import MenuOptions from "./MenuOptions.svelte";
  import { quickSearch } from "../setBookFilters";
  import { BookResultsPacket } from "../booksState";

  import MobileMenu from "app/components/navigation/MobileMenu.svelte";

  export let setMenuBarHeight;
  export let bookResultsPacket: BookResultsPacket;
  $: ({ totalPages = null, resultsCount = null, booksLoaded } = bookResultsPacket);

  const booksModuleContext: any = getContext("books-module-context");
  const { booksUiState } = booksModuleContext;

  export let uiView: ReturnType<typeof getBookSearchUiView>;

  $: ({ selectedBooks } = $booksUiState);
  $: selectedBooksIds = Object.keys(selectedBooks).filter(k => selectedBooks[k]);
  $: selectedBooksCount = selectedBooksIds.length;

  let quickSearchEl;
  $: {
    quickSearchEl && (quickSearchEl.value = $bookSearchState.search);
  }

  const resetSearch = () => {
    quickSearchEl.value = $bookSearchState.search;
  };
  const quickSearchType = evt => {
    if (evt.keyCode == 13) {
      quickSearch(evt.currentTarget.value);
    }
  };

  let mobileMenuOpen = false;
  //<!-- {isPublic ? <PublicBooksHeader /> : null} -->
</script>

<div class="books-menu-bar" use:measureHeight={setMenuBarHeight}>
  <MobileMenu title="Book Options" onClose={() => (mobileMenuOpen = false)} open={mobileMenuOpen}>
    <div class="button-container" style="display: flex; flex-direction: column">
      <MenuOptions {uiView} {bookResultsPacket} />
    </div>
  </MobileMenu>

  <div style="font-size: 11pt; position: relative">
    <div style="display: flex; flex-wrap: wrap; margin-bottom: 5px">
      <a style="font-size: 1.4rem; align-self: center" class="mobile-menu-button margin-right" on:click={() => (mobileMenuOpen = true)}>
        <i class="far fa-bars" />
      </a>
      <PagingButtons {...{ selectedBooksCount, totalPages, resultsCount, booksLoaded }} />
      <div style="margin-right: 5px">
        <div class="menu-bar-desktop btn-group">
          <input
            autocomplete="off"
            bind:this={quickSearchEl}
            value={$bookSearchState.search}
            on:blur={resetSearch}
            name="search"
            class="form-control search-input tiny-orphan"
            placeholder="Title search"
            on:keydown={quickSearchType}
          />
          <MenuOptions {uiView} {bookResultsPacket} />
        </div>
      </div>

      <ActiveSearchFilters {resultsCount} />
    </div>
  </div>
</div>

// react/modules/books/components/menuBar/menuBar.tsx
import React, { useContext, useRef, useEffect, useMemo, useCallback, FunctionComponent, useState } from "react";
import cn from "classnames";

import "./book-menu-bar-styles.scss";

import { AppContext } from "app/renderUI";

import PagingButtons from "./pagingButtons";
import MenuOptions from "./menuOptions";
import CurrentSearchFilters from "./currentSearchFilters";

import { useCurrentSearch } from "../../booksSearchState";
import { quickSearch } from "../../setBookFilters";
import PublicBooksHeader from "../publicBooksHeader";
import { BooksModuleContext } from "../../books";
import { MobileMenu } from "app/components/mainNavigation";

interface IAddedMenuProps {
  disabled?: boolean;
  uiView: any;
  uiDispatch: any;
  bookResultsPacket: {
    books: any;
    totalPages: any;
    resultsCount: any;
    booksLoaded?: any;
    reload?: any;
  };
  measureRef?: any;
}

export const BooksMenuBarDisabled: FunctionComponent<{ totalPages: number; resultsCount: number; measureRef: any }> = ({
  totalPages,
  resultsCount,
  measureRef
}) => {
  const bookResultsPacket = {
    books: [],
    totalPages,
    resultsCount
  };
  return <BooksMenuBar measureRef={measureRef} disabled={true} uiView={{}} uiDispatch={() => {}} bookResultsPacket={bookResultsPacket} />;
};
const BooksMenuBar: FunctionComponent<IAddedMenuProps> = props => {
  const { uiView, uiDispatch, disabled, measureRef, bookResultsPacket } = props;
  const { books = [], totalPages = null, resultsCount = null, booksLoaded } = bookResultsPacket || {};
  const quickSearchEl = useRef(null);
  const [appState] = useContext(AppContext);

  const { booksUiState } = useContext(BooksModuleContext);

  const { selectedBooks } = booksUiState;
  const selectedBooksCount = useMemo(() => Object.keys(selectedBooks).filter(k => selectedBooks[k]).length, [selectedBooks]);

  const bookSearchState = useCurrentSearch();

  useEffect(() => {
    quickSearchEl.current.value = bookSearchState.search;
  }, [bookSearchState.search]);

  const resetSearch = () => {
    quickSearchEl.current.value = bookSearchState.search;
  };
  const quickSearchType = evt => {
    if (evt.keyCode == 13) {
      quickSearch(evt.currentTarget.value);
    }
  };

  let { isPublic } = appState;

  const Button = useCallback(
    ({ children, ...rest }) => (
      <button {...rest} disabled={disabled || rest.disabled}>
        {children}
      </button>
    ),
    [disabled]
  );

  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <div className="books-menu-bar" ref={measureRef}>
      <MobileMenu title="Book Options" open={mobileMenuOpen} onClose={() => setMobileMenuOpen(false)}>
        <div className="button-container" style={{ display: "flex", flexDirection: "column" }}>
          <MenuOptions {...{ Button, selectedBooksCount, uiView, uiDispatch, bookResultsPacket }} />
        </div>
      </MobileMenu>

      <div style={{ fontSize: "11pt", position: "relative" }}>
        <div style={{ display: "flex", flexWrap: "wrap", marginBottom: "5px" }}>
          <a style={{ fontSize: "1.4rem", alignSelf: "center" }} className="mobile-menu-button margin-right" onClick={() => setMobileMenuOpen(true)}>
            <i className="far fa-bars"></i>
          </a>
          {isPublic ? <PublicBooksHeader /> : null}
          <PagingButtons {...{ selectedBooksCount, totalPages, resultsCount, booksLoaded, Button, disabled }} />
          <div style={{ marginRight: "5px" }}>
            <div className="menu-bar-desktop btn-group">
              <input
                ref={quickSearchEl}
                defaultValue={bookSearchState.search}
                onBlur={resetSearch}
                name="search"
                className={`form-control search-input tiny-orphan`}
                placeholder="Title search"
                onKeyDown={quickSearchType}
                disabled={disabled}
              />
              <MenuOptions {...{ Button, selectedBooksCount, uiView, uiDispatch, bookResultsPacket }} />
            </div>
          </div>

          <CurrentSearchFilters resultsCount={resultsCount} disabled={disabled} />
        </div>
      </div>
    </div>
  );
};

type BookSearchFilters = {
  resultsCount: number;
};

export default BooksMenuBar;
