// svelte-kit/src/routes/(logged-in)/books/menuBar/PagingButtons.svelte
<script lang="ts">
  //import { appState } from "app/state/appState";
  //import { currentSearch } from "../booksSearchState";
  //import { pageOne, setPage } from "../setBookFilters";

  export let totalPages: number;
  export let resultsCount: number | string;
  export let booksLoaded: boolean;

  const online = true;
  const page = 1;
  const pageSize = 50;
  const setPage = (page: number) => {};
  const pageOne = () => {};
  //$: ({ online } = $appState);

  //$: ({ page, pageSize } = $currentSearch);

  $: canPageUp = online ? page < totalPages : resultsCount == pageSize;
  $: canPageDown = page > 1;
  $: canPageOne = page > 1;
  $: canPageLast = page < totalPages;

  let pageUp = () => setPage(+page + 1);
  let pageDown = () => setPage(+page - 1);
  let pageLast = () => setPage(totalPages);
</script>

<div style="display: flex; margin-right: 5px; align-items: center">
  <div class="btn-group">
    <button on:click={pageOne} disabled={!canPageOne} class="btn btn-default page-edge"><i class="fal fa-angle-double-left" /></button>
    <button on:click={pageDown} disabled={!canPageDown} class="btn btn-default page" style="margin-right: 5px">
      <i class="fal fa-angle-left" />
    </button>
  </div>
  {#if online}
    <div class="results-holder overlay-holder">
      <span style="display: inline;">
        {#if booksLoaded}
          {#if totalPages}<span><span class="page-label">Page </span>{page} of {totalPages}</span>{:else}<span>No results</span>{/if}
        {:else}<span>Loading...</span>{/if}
      </span>
      <span style="visibility: hidden">
        <span class="page-label">Page </span>1 of 10
      </span>
    </div>
  {/if}
  <div class="btn-group">
    <button on:click={pageUp} disabled={!canPageUp} class="btn btn-default page" style="margin-left: 5px"> <i class="fal fa-angle-right" /> </button>
    {#if online}
      <button on:click={pageLast} disabled={!canPageLast} class="btn btn-default page-edge"><i class="fal fa-angle-double-right" /></button>
    {/if}
  </div>
</div>

// react/modules/books/components/menuBar/pagingButtons.tsx
import React, { useContext, FunctionComponent } from "react";
import cn from "classnames";
import { AppContext } from "app/state/appState";

import { setPage, pageOne } from "../../setBookFilters";
import { useCurrentSearch } from "../../booksSearchState";

const PagingButtons: FunctionComponent<{
  selectedBooksCount: number;
  totalPages: number;
  resultsCount: number;
  Button: any;
  disabled: boolean;
  booksLoaded: boolean;
}> = props => {
  const { totalPages, resultsCount, booksLoaded, Button, disabled } = props;

  const [appState] = useContext(AppContext);
  const { online } = appState;

  const bookSearchState = useCurrentSearch();
  const { page, pageSize } = bookSearchState;

  let canPageUp = online ? page < totalPages : resultsCount == pageSize;
  let canPageDown = page > 1;
  let canPageOne = page > 1;
  let canPageLast = page < totalPages;

  let pageUp = () => setPage(+page + 1);
  let pageDown = () => setPage(+page - 1);
  let pageLast = () => setPage(totalPages);

  return (
    <>
      <div style={{ display: "flex", marginRight: "5px", alignItems: "center" }}>
        <div className="btn-group">
          <Button onClick={pageOne} disabled={!canPageOne} className="btn btn-default page-edge">
            <i className="fal fa-angle-double-left" />
          </Button>
          <Button onClick={pageDown} disabled={!canPageDown} className="btn btn-default page" style={{ marginRight: "5px" }}>
            <i className="fal fa-angle-left" />
          </Button>
        </div>
        {online ? (
          <span className={cn({ disabled })} style={{ display: "inline" }}>
            <div className="results-holder overlay-holder">
              {!booksLoaded ? (
                <span>Loading...</span>
              ) : resultsCount ? (
                <span>
                  <span className="page-label">Page </span>
                  {page} of {totalPages}
                </span>
              ) : (
                <span>No results</span>
              )}
              <span style={{ visibility: "hidden" }}>
                <span className="page-label">Page </span>1 of 10
              </span>
            </div>
          </span>
        ) : null}
        <div className="btn-group">
          <Button onClick={pageUp} disabled={!canPageUp} className="btn btn-default page" style={{ marginLeft: "5px" }}>
            <i className="fal fa-angle-right" />
          </Button>
          {online ? (
            <Button onClick={pageLast} disabled={!canPageLast} className="btn btn-default page-edge">
              <i className="fal fa-angle-double-right" />
            </Button>
          ) : null}
        </div>
      </div>
    </>
  );
};

export default PagingButtons;
