// react-redux/modules/activate/activateComponent.tsx
import { isLoggedIn, history, getCurrentHistoryState } from 'reactStartup';
import React, {Component} from 'react';

const MainActivatePane = props =>
    <div className="row" style={{margin: 0}}>
        <div className="hidden-xs hidden-sm col-md-1 col-lg-3"></div>
        <div style={{ marginLeft: 10, marginRight: 10 }} className="col-md-10 col-lg-6">
            <div className="panel panel-default">
                <div className="panel-body">
                    {props.children}
                </div>
            </div>
        </div>
        <div className="hidden-xs hidden-sm col-md-1 col-lg-3"></div>
    </div>

class ActivateIfLoggedIn extends Component<any, any>{
    _timeoutToken: any
    constructor(){
        super();
        this._timeoutToken = setTimeout(() => history.replace('/home'), 5000);
    }
    componentWillUnmount(){
        clearTimeout(this._timeoutToken);
    }
    render(){
        return (
            <div>
                <MainActivatePane>
                    <div className="alert alert-success">
                        Your account is activated!  Redirecting you automatically, or use the menu above if you don't care to wait :-)
                    </div>
                </MainActivatePane>
            </div>
        )
    }
}

const ActivateIfNotLoggedIn = props => {
    let alreadyActivated = !!getCurrentHistoryState().searchState.alreadyActivated;
    return (
        <div>
            <MainActivatePane>
                {alreadyActivated ?
                    <div className="alert alert-warning">
                        This activation link has already been used.  Use the login link above to log back in.
                    </div>
                    :
                    <div className="alert alert-danger">
                        Sorry - it looks like something went wrong. The activation link you clicked appears to be invalid.
                    </div>
                }
            </MainActivatePane>
        </div>
    );
}

export default props => (
    <div>
        { isLoggedIn() ? <ActivateIfLoggedIn /> : <ActivateIfNotLoggedIn /> }
    </div>
);

// svelte/modules/activate/Activate.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import FlexRow from "app/components/layout/FlexRow.svelte";
  import { appState } from "app/state/appState";

  const { isLoggedIn, urlState } = $appState;
  const alreadyActivated = !!urlState.searchState.alreadyActivated;

  let _timeoutToken;
  if (isLoggedIn) {
    _timeoutToken = setTimeout(() => window.location.replace("/home"), 4000);
  }

  onMount(() => () => {
    clearTimeout(_timeoutToken);
  });
</script>

<style>
  .root {
    margin-left: auto;
    margin-right: auto;
    margin-top: 40px;
  }

  .alert-holder {
    display: flex;
  }

  .alert {
    margin-left: auto;
    margin-right: auto;
  }
</style>

<section>
  <FlexRow>
    <div class="root col-xs-11 col-md-10 col-lg-6 alert-holder">
      {#if isLoggedIn}
        <div class="alert alert-success">
          Your account is activated! Redirecting you automatically, or use the menu above if you don't care to wait :-)
        </div>
      {:else if alreadyActivated}
        <div class="alert alert-warning">This activation link has already been used. Use the login link above to log back in.</div>
      {:else}
        <div class="alert alert-danger">Sorry - it looks like something went wrong. The activation link you clicked appears to be invalid.</div>
      {/if}
    </div>
  </FlexRow>
</section>
