// react-redux/modules/books/components/booksMenuBar.tsx
import React, { SFC, useContext, useRef, useEffect, useMemo } from "react";
import { RemovableLabelDisplay } from "applicationRoot/components/labelDisplay";

import {
  useCurrentSearch,
  useBookSearchUiView,
  removeFilters,
  removeFilterSubject,
  removeFilterTag,
  pageOne,
  clearAllFilters,
  quickSearch as quickTitleSearch,
  setPage
} from "../booksSearchState";
import { BooksContext } from "../booksState";
import { BooksSearchContext } from "./bookViewList";
import { AppContext } from "applicationRoot/renderUI";

interface IAddedMenuProps {
  editTags: any;
  editSubjects: any;
  startSubjectModification: any;
  startTagModification: any;
  beginEditFilters: any;
  booksUiState: any;
  setRead: any;
}

const filterDisplayStyles = { flex: "0 0 auto", alignSelf: "center", marginRight: "5px", marginTop: "4px", marginBottom: "4px" };

const BooksMenuBar: SFC<IAddedMenuProps> = props => {
  const quickSearchEl = useRef(null);

  const [appState] = useContext(AppContext);
  const { totalPages, resultsCount } = useContext(BooksContext);
  const [{}, { setViewDesktop, setViewBasicList, setCoversList }] = useContext(BooksSearchContext);

  const { booksUiState, setRead } = props;
  const { selectedBooks } = booksUiState;
  const selectedBooksCount = useMemo(() => Object.keys(selectedBooks).filter(k => selectedBooks[k]).length, [selectedBooks]);
  const selectedBooksIds = useMemo(() => Object.keys(selectedBooks).filter(k => selectedBooks[k]), [selectedBooks]);

  const bookSearchUiView = useBookSearchUiView();
  const bookSearchState = useCurrentSearch();

  useEffect(() => void (quickSearchEl.current.value = bookSearchState.search), [bookSearchState.search]);

  const resetSearch = () => {
    quickSearchEl.current.value = bookSearchState.search;
  };
  const quickSearchType = evt => {
    if (evt.keyCode == 13) {
      evt.preventDefault();
      quickTitleSearch(evt.currentTarget.value);
    }
  };

  let { page, pageSize, activeFilterCount } = bookSearchState;
  let { isPublic, publicBooksHeader, publicName, online } = appState;
  let booksHeader = isPublic ? publicBooksHeader || `${publicName}'s Books` : "Your Books";

  let canPageUp = online ? page < totalPages : resultsCount == pageSize;
  let canPageDown = page > 1;
  let canPageOne = page > 1;
  let canPageLast = page < totalPages;

  let resultsDisplay = resultsCount ? `${resultsCount} book${resultsCount === 1 ? "" : "s"}` : "";
  let removeAllFiltersLabel = {
    backgroundColor: "red",
    textColor: "white",
    name: "Remove all filters"
  };

  let pageUp = () => setPage(+page + 1);
  let pageDown = () => setPage(+page - 1);
  let pageLast = () => setPage(totalPages);

  return (
    <div>
      <div className="booksMenuBar" style={{ fontSize: "11pt", paddingBottom: "5px" }}>
        <div style={{ display: "flex", flexWrap: "wrap", marginBottom: "5px" }}>
          {isPublic ? <h4 style={{ marginRight: "5px", marginBottom: 0, alignSelf: "center" }}>{booksHeader}</h4> : null}
          {!selectedBooksCount ? (
            <div className="visible-tiny" style={{ marginRight: "5px" }}>
              <div className="btn-group">
                <button onClick={pageDown} disabled={!canPageDown} className="btn btn-default">
                  <i className="fal fa-angle-left" />
                </button>
                <button onClick={pageUp} disabled={!canPageUp} className="btn btn-default">
                  <i className="fal fa-angle-right" />
                </button>
              </div>
            </div>
          ) : null}
          <div className="hidden-tiny" style={{ display: "flex", marginRight: "5px", alignItems: "center" }}>
            <div className="btn-group">
              <button onClick={pageOne} disabled={!canPageOne} className="btn btn-default">
                <i className="fal fa-angle-double-left" />
              </button>
              <button onClick={pageDown} disabled={!canPageDown} className="btn btn-default" style={{ marginRight: "5px" }}>
                <i className="fal fa-angle-left" />
              </button>
            </div>
            {online && resultsCount ? (
              <span style={{ display: "inline" }}>
                <span className="hidden-xs">Page</span> {page}
                <span className="hidden-xs"> of {totalPages}</span>
              </span>
            ) : null}
            <div className="btn-group">
              <button onClick={pageUp} disabled={!canPageUp} className="btn btn-default" style={{ marginLeft: "5px" }}>
                <i className="fal fa-angle-right" />
              </button>
              {/* TODO: pageLast */}
              {online ? (
                <button onClick={pageLast} disabled={!canPageLast} className="btn btn-default">
                  <i className="fal fa-angle-double-right" />
                </button>
              ) : null}
            </div>
          </div>
          <div style={{ marginRight: "5px" }}>
            <div className="btn-group">
              <input
                ref={quickSearchEl}
                defaultValue={bookSearchState.search}
                onBlur={resetSearch}
                name="search"
                className="form-control hidden-tiny"
                placeholder="Title search"
                onKeyDown={quickSearchType}
                style={{
                  float: "left",
                  display: "inline-block",
                  width: "100px"
                }}
              />
              {!selectedBooksCount ? (
                <>
                  {online ? (
                    <>
                      <button
                        title="Filter search"
                        style={{ borderTopLeftRadius: 0, borderBottomLeftRadius: 0 }}
                        onClick={props.beginEditFilters}
                        className="btn btn-default btn-first-tiny"
                      >
                        <i className="fal fa-filter" />
                      </button>
                      {!isPublic ? (
                        <>
                          <button title="Edit subjects" onClick={props.editSubjects} className="btn btn-default ">
                            <i className="fal fa-sitemap" />
                          </button>
                          <button title="Edit tags" onClick={props.editTags} className="btn btn-default ">
                            <i className="fal fa-tags" />
                          </button>
                        </>
                      ) : null}
                    </>
                  ) : null}
                  <button
                    style={{ position: "static" }}
                    onClick={setViewDesktop}
                    className={"btn btn-default " + (bookSearchUiView.isGridView ? "active" : "")}
                  >
                    <i className="fal fa-table" />
                  </button>
                  <button
                    style={{ position: "static" }}
                    onClick={setCoversList}
                    className={"btn btn-default " + (bookSearchUiView.isCoversList ? "active" : "")}
                  >
                    <i className="fas fa-th" />
                  </button>
                  <button
                    style={{ position: "static" }}
                    onClick={setViewBasicList}
                    className={"btn btn-default " + (bookSearchUiView.isBasicList ? "active" : "")}
                  >
                    <i className="fal fa-list" />
                  </button>
                </>
              ) : !isPublic ? (
                <>
                  <button title="Add/remove subjects" onClick={props.startSubjectModification} className={"btn btn-default btn-first-tiny"}>
                    <i className="fal fa-sitemap" />
                  </button>
                  <button title="Add/remove tags" onClick={props.startTagModification} className="btn btn-default">
                    <i className="fal fa-tags" />
                  </button>
                  <button title="Set read" onClick={() => setRead(selectedBooksIds, true)} className={"btn btn-default"}>
                    <i className="fal fa-eye" />
                  </button>
                  <button title="Set un-read" onClick={() => setRead(selectedBooksIds, false)} className="btn btn-default put-line-through">
                    <i className="fal fa-eye-slash" />
                  </button>
                </>
              ) : null}
            </div>
          </div>

          <div style={{ display: "flex", alignItems: "flex-start", alignContent: "center", flexWrap: "wrap" }}>
            {online && resultsCount ? (
              <div style={{ flex: "0 0 auto", marginRight: "5px", alignSelf: "center" }}>
                <span className="visible-tiny">
                  Page {page} of {totalPages}&nbsp;&nbsp;—&nbsp;&nbsp;
                </span>
                {resultsDisplay}
              </div>
            ) : null}

            {bookSearchState.search ? (
              <RemovableLabelDisplay
                style={{ flex: "0 0 auto", alignSelf: "center", marginRight: "5px", marginTop: "4px", marginBottom: "4px" }}
                item={{ name: `"${bookSearchState.search}"` }}
                doRemove={() => removeFilters("search")}
              />
            ) : null}
            {bookSearchState.isRead == "1" || bookSearchState.isRead == "0" ? (
              <RemovableLabelDisplay
                style={{ flex: "0 0 auto", alignSelf: "center", marginRight: "5px", marginTop: "4px", marginBottom: "4px" }}
                item={{ backgroundColor: `${bookSearchState.isRead == "1" ? "green" : "red"}` }}
                doRemove={() => removeFilters("isRead")}
              >
                <span>
                  {bookSearchState.isRead == "1" ? "Is Read" : "Not Read"}
                  &nbsp;
                  {bookSearchState.isRead == "1" ? <i className="far fa-check" /> : null}
                </span>
              </RemovableLabelDisplay>
            ) : null}
            {bookSearchState.publisher ? (
              <RemovableLabelDisplay
                style={filterDisplayStyles}
                item={{ name: `publisher: "${bookSearchState.publisher}"` }}
                doRemove={() => removeFilters("publisher")}
              />
            ) : null}
            {bookSearchState.author ? (
              <RemovableLabelDisplay
                style={filterDisplayStyles}
                item={{ name: `author: "${bookSearchState.author}"` }}
                doRemove={() => removeFilters("author")}
              />
            ) : null}
            {bookSearchState.pages || bookSearchState.pages == "0" ? (
              <RemovableLabelDisplay
                style={filterDisplayStyles}
                item={{ name: `pages: ${bookSearchState.pagesOperator == "lt" ? "<" : ">"} ${bookSearchState.pages}` }}
                doRemove={() => removeFilters("pages", "pagesOperator")}
              />
            ) : null}
            {bookSearchState.noSubjects ? (
              <RemovableLabelDisplay style={filterDisplayStyles} item={{ name: `No subjects` }} doRemove={() => removeFilters("noSubjects")} />
            ) : null}

            {bookSearchState.selectedSubjects.map(s => (
              <RemovableLabelDisplay style={filterDisplayStyles} item={s} doRemove={() => removeFilterSubject(s._id)} />
            ))}
            {bookSearchState.selectedTags.map(t => (
              <RemovableLabelDisplay style={filterDisplayStyles} item={t} doRemove={() => removeFilterTag(t._id)} />
            ))}
            {activeFilterCount > 1 ? (
              <RemovableLabelDisplay style={filterDisplayStyles} item={removeAllFiltersLabel} doRemove={clearAllFilters} />
            ) : null}
          </div>
        </div>
      </div>
    </div>
  );
};

export default BooksMenuBar;

// svelte/modules/books/BooksMenuBar.svelte
<script lang="ts">
  import { appState } from "app/state/appState";

  import measureHeight from "util/measureHeight";

  import { currentSearch as bookSearchState } from "./booksSearchState";
  import { getBookSearchUiView } from "./booksUiState";
  import PagingButtons from "./PagingButtons.svelte";
  import { quickSearch } from "./setBookFilters";

  interface BookResultsPacket {
    books: any[];
    totalPages: number;
    resultsCount: string | number;
    reload?: () => void;
    booksLoading?: boolean;
    booksLoaded?: boolean;
  }

  export let setMenuBarHeight;
  export let bookResultsPacket: BookResultsPacket;
  $: ({ books = [], totalPages = null, resultsCount = null, reload, booksLoading, booksLoaded } = bookResultsPacket);

  // const { actions, booksUiState } = useContext(BooksModuleContext);
  // const { setRead } = actions;

  export let uiView: ReturnType<typeof getBookSearchUiView>;
  const uiDispatch = $uiView.dispatch;

  //const { selectedBooks } = booksUiState;
  //const selectedBooksCount = useMemo(() => Object.keys(selectedBooks).filter(k => selectedBooks[k]).length, [selectedBooks]);
  //const selectedBooksIds = useMemo(() => Object.keys(selectedBooks).filter(k => selectedBooks[k]), [selectedBooks]);

  //const editSubjectsForSelectedBooks = () => actions.openBookSubModal(books.filter(b => booksUiState.selectedBooks[b._id]));
  //const editTagsForSelectedBooks = () => actions.openBookTagModal(books.filter(b => booksUiState.selectedBooks[b._id]));

  $: {
    quickSearchEl && (quickSearchEl.value = $bookSearchState.search);
  }

  const resetSearch = () => {
    quickSearchEl.value = $bookSearchState.search;
  };
  const quickSearchType = evt => {
    if (evt.keyCode == 13) {
      quickSearch(evt.currentTarget.value);
    }
  };

  $: ({ isPublic, online } = $appState);

  //let resetSearch = () => {};
  //let quickSearchType = () => {};
  // let uiDispatch = () => {};
  let editSubjectsForSelectedBooks = () => {};
  let editTagsForSelectedBooks = () => {};
  let setRead = () => {};
  let searchInput = "";
  let selectedBooksCount = 0;
  //let online = true;
  let actions = {};
  //let uiView = {};
  let selectedBooksIds = {};
  //let isPublic = false;
  //
  let quickSearchEl;
</script>

<style>
  .root {
    position: sticky;
    top: 0;
    margin-top: -2px;
    padding-top: 2px;
    background-color: white;
    z-index: 1;
  }
</style>

<div class="root" use:measureHeight={setMenuBarHeight}>
  <div class="booksMenuBar" style="font-size: 11pt; padding-bottom: 5px; position: relative">
    <div style="display: flex; flex-wrap: wrap; margin-bottom: 5px">
      <!-- {isPublic ? <PublicBooksHeader /> : null} -->
      <PagingButtons {...{ selectedBooksCount, totalPages, resultsCount, booksLoaded }} />
      <div style="margin-right: 5px">
        <div class="btn-group">
          <input
            autocomplete="off"
            bind:this={quickSearchEl}
            value={$bookSearchState.search}
            on:blur={resetSearch}
            name="search"
            class={`form-control ${searchInput} tiny-orphan`}
            placeholder="Title search"
            on:keydown={quickSearchType}
          />
          {#if !selectedBooksCount}
            {#if online}
              <button
                title="Filter search"
                style="border-top-left-radius: 0; border-bottom-left-radius: 0"
                on:click={actions.beginEditFilters}
                class="btn btn-default hidden-tiny"
              >
                <i class="fal fa-filter" />
              </button>
              {#if !isPublic}
                <button title="Edit subjects" onClick={actions.editSubjects} class="btn btn-default hidden-xs"><i class="fal fa-sitemap" /></button>
                <button title="Edit tags" onClick={actions.editTags} class="btn btn-default hidden-xs"><i class="fal fa-tags" /></button>
              {/if}
            {/if}
            <button class="btn btn-default hidden-tiny" on:click={reload} disabled={booksLoading}><i class="fal fa-sync" /></button>
            <button
              on:click={() => uiDispatch({ type: 'SET_GRID_VIEW' })}
              class={'btn btn-default hidden-tiny ' + ($uiView.isGridView ? 'active' : '')}
            >
              <i class="fal fa-table" />
            </button>
            <button
              on:click={() => uiDispatch({ type: 'SET_COVERS_LIST_VIEW' })}
              class={'btn btn-default hidden-tiny ' + ($uiView.isCoversList ? 'active' : '')}
            >
              <i class="fas fa-th" />
            </button>
            <button
              on:click={() => uiDispatch({ type: 'SET_BASIC_LIST_VIEW' })}
              class={'btn btn-default hidden-tiny ' + ($uiView.isBasicList ? 'active' : '')}
            >
              <i class="fal fa-list" />
            </button>
          {:else if !isPublic}
            <button title="Add/remove subjects" on:click={editSubjectsForSelectedBooks} class={'btn btn-default hidden-tiny'}>
              <i class="fal fa-sitemap" />
            </button>
            <button title="Add/remove tags" on:click={editTagsForSelectedBooks} class="btn btn-default hidden-tiny"><i class="fal fa-tags" /></button>
            <button title="Set read" on:click={() => setRead(selectedBooksIds, true)} class={'btn btn-default hidden-tiny'}>
              <i class="fal fa-eye" />
            </button>
            <button title="Set un-read" on:click={() => setRead(selectedBooksIds, false)} class="btn btn-default put-line-through hidden-tiny">
              <i class="fal fa-eye-slash" />
            </button>
          {/if}
        </div>
      </div>

      <!-- <BookSearchFilters {resultsCount} {disabled} /> -->
    </div>
  </div>
</div>
