// react-redux/modules/books/components/tagSubjectSetter/bookTagSetter.tsx
import React, {Component} from 'react';
import { connect } from 'react-redux';

import BootstrapButton, { AjaxButton } from 'applicationRoot/components/bootstrapButton';
import { Modal } from 'simple-react-bootstrap';
import GenericLabelSelect from 'applicationRoot/components/genericLabelSelect';
import SelectAvailable from './selectAvailable';

import {setBooksTags} from 'modules/books/reducers/books/actionCreators'; 
import {filterTags} from 'modules/books/reducers/tags/reducer'; 
import {selectEntireTagsState, TagsStateType} from 'modules/books/reducers/tags/reducer'; 
const {createSelector} = require('reselect');

interface ILocalProps {
    modifyingBooks: any[];
    onDone: any;
}

@connect(selectEntireTagsState, {setBooksTags})
export default class BookTagSetterDesktopUnConnected extends Component<TagsStateType & {setBooksTags} & ILocalProps, any> {
    state = { 
        currentTab: 'tags',
        addingTags: [],
        removingTags: [],
        addingTagSearch: '',
        removingTagSearch: '',
        saving: false
    };

    setBooksTags = () => {
        this.setState({saving: true});
        Promise.resolve(
            this.props.setBooksTags(
                this.props.modifyingBooks.map(b => b._id),
                this.state.addingTags,
                this.state.removingTags
            )
        ).then(() => {
            this.setState({saving: false});
            this.props.onDone();
        });
    }
    addingTagSet = (adding, {_id}) => {
        this.setState({
            addingTags: adding ? this.state.addingTags.concat(_id) : this.state.addingTags.filter(x => x != _id),
            addingTagSearch: adding ? '' : this.state.addingTagSearch
        });
    }
    tagSelectedToAdd = this.addingTagSet.bind(null, true);
    removingTagSet = (adding, {_id}) => {
        this.setState({
            removingTags: adding ? this.state.removingTags.concat(_id) : this.state.removingTags.filter(x => x != _id),
            removingTagSearch: adding ? '' : this.state.removingTagSearch
        });
    }
    tagSelectedToRemove = this.removingTagSet.bind(null, true);
    resetTags = () => {
        this.setState({
            addingTags: [],
            removingTags: []
        });
    }
    setAddingSearchVal = val => this.setState({addingTagSearch: val});
    setRemovingSearchVal = val => this.setState({removingTagSearch: val + ''});

    render(){
        let dontAddTag = this.addingTagSet.bind(null, false),
            dontRemoveTag = this.removingTagSet.bind(null, false);

        return (
            <Modal className="fade" show={!!this.props.modifyingBooks.length} onHide={this.props.onDone}>
                <Modal.Header>
                    <button type="button" className="close" onClick={this.props.onDone} aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 className="modal-title">Add / Remove Tags:</h4>
                </Modal.Header>
                <Modal.Body>
                    <ul className="nav nav-tabs">
                        <li className={this.state.currentTab == 'tags' ? 'active' : ''}>
                            <a onClick={() => this.setState({currentTab: 'tags'})}>Choose tags</a>
                        </li>
                        <li className={this.state.currentTab == 'books' ? 'active' : ''}>
                            <a onClick={() => this.setState({currentTab: 'books'})}>For books</a>
                        </li>
                    </ul>
                    <div className="tab-content">
                        <div style={{ minHeight: '150px' }} className={'tab-pane ' + (this.state.currentTab == 'tags' ? 'active in' : '')}>
                            <br />
                            <div style={{ position: 'relative' }} className="row">
                                <div className="col-xs-3">
                                    <SelectAvailable 
                                        placeholder="Adding"
                                        search={this.state.addingTagSearch}
                                        onSearchChange={this.setAddingSearchVal}
                                        items={this.props.allTagsSorted}
                                        currentlySelected={this.state.addingTags}
                                        onSelect={this.tagSelectedToAdd}
                                        filter={filterTags} />
                                </div>
                                <div className="col-xs-9">
                                    <div>
                                        {this.state.addingTags.map(_id => this.props.tagHash[_id]).map((s : any, i) =>
                                            <span key={i} style={{ color: s.textColor || 'white', backgroundColor: s.backgroundColor, display: 'inline-table' }} className="label label-default margin-left">
                                                <a onClick={() => dontAddTag(s)} style={{ color: s.textColor || 'white', paddingRight: '5px', marginRight: '5px' }}>X</a>{s.name}
                                            </span>
                                        )}
                                    </div>
                                </div>
                            </div>

                            <br />

                            <div style={{ position: 'relative' }} className="row">
                                <div className="col-xs-3">
                                    <SelectAvailable 
                                        placeholder="Removing"
                                        search={this.state.removingTagSearch}
                                        onSearchChange={this.setRemovingSearchVal}
                                        items={this.props.allTagsSorted}
                                        currentlySelected={this.state.removingTags}
                                        onSelect={this.tagSelectedToRemove}
                                        filter={filterTags} />
                                </div>
                                <div className="col-xs-9">
                                    <div>
                                        {this.state.removingTags.map(_id => this.props.tagHash[_id]).map((s : any, i) =>
                                            <span key={i} style={{ color: s.textColor || 'white', backgroundColor: s.backgroundColor, display: 'inline-table' }} className="label label-default margin-left">
                                                <a onClick={() => dontRemoveTag(s)} style={{ color: s.textColor || 'white', paddingRight: '5px', marginRight: '5px' }}>X</a>{s.name}
                                            </span>
                                        )}
                                    </div>
                                </div>
                            </div>

                            <br />
                            <BootstrapButton onClick={this.resetTags} className="pull-right" preset="default-xs">Reset tags</BootstrapButton>
                            <br />
                        </div>
                        <div style={{ minHeight: '150px' }} className={'tab-pane ' + (this.state.currentTab == 'books' ? 'active in' : '')}>
                            <br />
                            <ul className="list-unstyled">
                                { this.props.modifyingBooks.map(book => <li key={book._id}>{book.title}</li>) }
                            </ul>
                            <br />
                        </div>
                    </div>
                </Modal.Body>
                <Modal.Footer>
                    <AjaxButton preset="primary" running={this.state.saving} runningText='Setting' onClick={() => this.setBooksTags()}>Set</AjaxButton>
                    <BootstrapButton preset="" onClick={this.props.onDone}>Cancel</BootstrapButton>
                </Modal.Footer>
            </Modal>
        );
    }
}

// svelte/modules/books/BookTagSetter.svelte
<script lang="ts">
  import { mutation } from "micro-graphql-svelte";
  import { MutationOf, Mutations } from "graphQL/graphql-typings";

  import updateBookTags from "graphQL/books/updateBookTags.graphql";

  import SelectAvailableTags from "app/components/subjectsAndTags/tags/SelectAvailableTags.svelte";
  import DisplaySelectedTags from "app/components/subjectsAndTags/tags/DisplaySelectedTags.svelte";

  import Modal from "app/components/ui/Modal.svelte";
  import StandardModalFooter from "app/components/ui/StandardModalFooter.svelte";
  import Button from "app/components/buttons/Button.svelte";
  import ActionButton from "app/components/buttons/ActionButton.svelte";
  import Tabs from "app/components/layout/tabs/Tabs.svelte";
  import TabHeaders from "app/components/layout/tabs/TabHeaders.svelte";
  import TabHeader from "app/components/layout/tabs/TabHeader.svelte";
  import TabContents from "app/components/layout/tabs/TabContents.svelte";
  import TabContent from "app/components/layout/tabs/TabContent.svelte";

  import FlexRow from "app/components/layout/FlexRow.svelte";
  import Stack from "app/components/layout/Stack.svelte";
  import FlowItems from "app/components/layout/FlowItems.svelte";

  export let modifyingBooks: any[];
  export let isOpen;
  export let onHide;

  interface ILocalProps {
    modifyingBooks: any[];
    onDone: any;
  }

  let addingTags = [];
  let removingTags = [];

  const resetTags = () => {
    addingTags = [];
    removingTags = [];
  };

  const { mutationState } = mutation<MutationOf<Mutations["updateBooks"]>>(updateBookTags);
  $: ({ runMutation, running } = $mutationState);

  const save = () => {
    let args = { books: modifyingBooks.map(b => b._id), add: addingTags, remove: removingTags };
    return Promise.resolve(runMutation(args)).then(() => {
      onHide();
    });
  };
  const addingTagSet = (adding, { _id }) => (addingTags = adding ? addingTags.concat(_id) : addingTags.filter(x => x != _id));
  const tagSelectedToAdd = addingTagSet.bind(null, true);

  const removingTagSet = (adding, { _id }) => (removingTags = adding ? removingTags.concat(_id) : removingTags.filter(x => x != _id));
  const tagSelectedToRemove = removingTagSet.bind(null, true);

  const dontAddTag = addingTagSet.bind(null, false);
  const dontRemoveTag = removingTagSet.bind(null, false);

  let closeModal;
</script>

<Modal {isOpen} {onHide} headerCaption="Add / Remove Tags" deferStateChangeOnClose={true} standardFooter={false}>
  <Tabs defaultTab="tags">
    <TabHeaders>
      <TabHeader tabName="tags"><a>Choose tags</a></TabHeader>
      <TabHeader tabName="books"><a>For books</a></TabHeader>
    </TabHeaders>
    <TabContents>
      <TabContent tabName="tags">
        <FlexRow>
          <div class="col-xs-3">
            <SelectAvailableTags placeholder="Adding" currentlySelected={addingTags} onSelect={tagSelectedToAdd} />
          </div>
          <div class="col-xs-9" style="display: flex; flex-wrap: wrap">
            <DisplaySelectedTags currentlySelected={addingTags} onRemove={dontAddTag} />
          </div>

          <div class="col-xs-3">
            <SelectAvailableTags placeholder="Removing" currentlySelected={removingTags} onSelect={tagSelectedToRemove} />
          </div>
          <div class="col-xs-9" style="display: flex; flex-wrap: wrap">
            <DisplaySelectedTags currentlySelected={removingTags} onRemove={dontRemoveTag} />
          </div>

          <div class="col-xs-12">
            <Button onClick={resetTags} preset="default-xs">Reset tags</Button>
          </div>
        </FlexRow>
      </TabContent>
      <TabContent tabName="books">
        <Stack style="font-size: 14px">
          {#each modifyingBooks as book (book._id)}
            <div>{book.title}</div>
          {/each}
        </Stack>
      </TabContent>
    </TabContents>
  </Tabs>
  <StandardModalFooter bind:closeModal>
    <FlowItems pushLast={true}>
      <ActionButton style="min-width: 10ch" preset="primary" text="Save" runningText="Saving" finishedText="Saved" onClick={save} />

      <Button style="min-width: 10ch" preset="" onClick={closeModal}>Cancel</Button>
    </FlowItems>
  </StandardModalFooter>
</Modal>
