// react/modules/books/components/menuBar/pagingButtons.tsx
import React, { useContext, FunctionComponent } from "react";
import cn from "classnames";
import { AppContext } from "app/state/appState";

import { setPage, pageOne } from "../../setBookFilters";
import { useCurrentSearch } from "../../booksSearchState";

const PagingButtons: FunctionComponent<{
  selectedBooksCount: number;
  totalPages: number;
  resultsCount: number;
  Button: any;
  disabled: boolean;
  booksLoaded: boolean;
}> = props => {
  const { totalPages, resultsCount, booksLoaded, Button, disabled } = props;

  const [appState] = useContext(AppContext);
  const { online } = appState;

  const bookSearchState = useCurrentSearch();
  const { page, pageSize } = bookSearchState;

  let canPageUp = online ? page < totalPages : resultsCount == pageSize;
  let canPageDown = page > 1;
  let canPageOne = page > 1;
  let canPageLast = page < totalPages;

  let pageUp = () => setPage(+page + 1);
  let pageDown = () => setPage(+page - 1);
  let pageLast = () => setPage(totalPages);

  return (
    <>
      <div style={{ display: "flex", marginRight: "5px", alignItems: "center" }}>
        <div className="btn-group">
          <Button onClick={pageOne} disabled={!canPageOne} className="btn btn-default page-edge">
            <i className="fal fa-angle-double-left" />
          </Button>
          <Button onClick={pageDown} disabled={!canPageDown} className="btn btn-default page" style={{ marginRight: "5px" }}>
            <i className="fal fa-angle-left" />
          </Button>
        </div>
        {online ? (
          <span className={cn({ disabled })} style={{ display: "inline" }}>
            <div className="results-holder overlay-holder">
              {!booksLoaded ? (
                <span>Loading...</span>
              ) : resultsCount ? (
                <span>
                  <span className="page-label">Page </span>
                  {page} of {totalPages}
                </span>
              ) : (
                <span>No results</span>
              )}
              <span style={{ visibility: "hidden" }}>
                <span className="page-label">Page </span>1 of 10
              </span>
            </div>
          </span>
        ) : null}
        <div className="btn-group">
          <Button onClick={pageUp} disabled={!canPageUp} className="btn btn-default page" style={{ marginLeft: "5px" }}>
            <i className="fal fa-angle-right" />
          </Button>
          {online ? (
            <Button onClick={pageLast} disabled={!canPageLast} className="btn btn-default page-edge">
              <i className="fal fa-angle-double-right" />
            </Button>
          ) : null}
        </div>
      </div>
    </>
  );
};

export default PagingButtons;

// svelte/modules/books/PagingButtons.svelte
<script lang="ts">
  import { appState } from "app/state/appState";
  import { currentSearch } from "./booksSearchState";
  import { pageOne, setPage } from "./setBookFilters";

  export let selectedBooksCount: number;
  export let totalPages: number;
  export let resultsCount: number | string;
  export let booksLoaded: boolean;

  $: ({ online } = $appState);

  $: ({ page, pageSize } = $currentSearch);

  $: canPageUp = online ? page < totalPages : resultsCount == pageSize;
  $: canPageDown = page > 1;
  $: canPageOne = page > 1;
  $: canPageLast = page < totalPages;

  let pageUp = () => setPage(+page + 1);
  let pageDown = () => setPage(+page - 1);
  let pageLast = () => setPage(totalPages);
</script>

{#if !selectedBooksCount}
  <div class="visible-xs" style="margin-right: 5px">
    <div>
      <button onClick={pageDown} disabled={!canPageDown} class="btn btn-default btn-group-size"><i class="fal fa-angle-left" /></button>
      <span style="padding-left: 3px; padding-right: 3px"> {page} of {totalPages} </span>
      <button onClick={pageUp} disabled={!canPageUp} class="btn btn-default btn-group-size"><i class="fal fa-angle-right" /></button>
    </div>
  </div>
{/if}
<div class="hidden-xs" style="display: flex; margin-right: 5px; align-items: center">
  <div class="btn-group">
    <button onClick={pageOne} disabled={!canPageOne} class="btn btn-default"><i class="fal fa-angle-double-left" /></button>
    <button onClick={pageDown} disabled={!canPageDown} class="btn btn-default" style="margin-right: 5px"> <i class="fal fa-angle-left" /> </button>
  </div>
  {#if online}
    <span style="display: inline; min-width: 7ch">
      {#if booksLoaded}
        {#if totalPages}<span> Page {page} of {totalPages} </span>{:else}<span>No results</span>{/if}
      {:else}<span>Loading...</span>{/if}
    </span>
  {/if}
  <div class="btn-group">
    <button onClick={pageUp} disabled={!canPageUp} class="btn btn-default" style="margin-left: 5px"> <i class="fal fa-angle-right" /> </button>

    {#if online}<button onClick={pageLast} disabled={!canPageLast} class="btn btn-default"><i class="fal fa-angle-double-right" /></button>{/if}
  </div>
</div>
