// react-redux/modules/books/components/bookSubjectSetter.tsx
import React, { Component } from "react";
import { connect } from "react-redux";

import BootstrapButton, { AjaxButton } from "applicationRoot/components/bootstrapButton";
import Modal from "simple-react-bootstrap/lib/modal";
import SelectAvailable from "./availableTagsOrSubjects";

import { filterSubjects } from "modules/books/reducers/subjects/reducer";
import { selectStackedSubjects, StackedSubjectsType } from "modules/books/reducers/subjects/reducer";

import { mutation } from "micro-graphql-react";

import { SET_BOOKS_SUBJECTS } from "../reducers/books/actionNames";

interface ILocalProps {
  modifyingBooks: any[];
  onDone: any;
}

@mutation(
  `mutation updateBooksSubjects($books: [String], $add: [String], $remove: [String]) {
    remove: updateBooks(
      _ids: $books,
      Updates: { subjects_PULL: $remove }
    ) { success }

    add: updateBooks(
      _ids: $books,
      Updates: { subjects_ADDTOSET: $add }
    ) { success }          
  }`
)
@connect(selectStackedSubjects)
export default class BookSubjectSetter extends Component<StackedSubjectsType & ILocalProps & { runMutation: any; dispatch: any; running: any }, any> {
  state = {
    currentTab: "subjects",
    addingSubjects: [],
    removingSubjects: [],
    addingSubjectSearch: "",
    removingSubjectSearch: ""
  };

  setBooksSubjects = () => {
    let args = { books: this.props.modifyingBooks.map(b => b._id), add: this.state.addingSubjects, remove: this.state.removingSubjects };
    Promise.resolve(this.props.runMutation(args)).then(() => {
      this.props.dispatch({ type: SET_BOOKS_SUBJECTS, ...args });
      this.props.onDone();
    });
  };
  addingSubjectSet = (adding, { _id }) => {
    this.setState({
      addingSubjects: adding ? this.state.addingSubjects.concat(_id) : this.state.addingSubjects.filter(x => x != _id),
      addingSubjectSearch: adding ? "" : this.state.addingSubjectSearch
    });
  };
  subjectSelectedToAdd = this.addingSubjectSet.bind(null, true);

  removingSubjectSet = (adding, { _id }) => {
    this.setState({
      removingSubjects: adding ? this.state.removingSubjects.concat(_id) : this.state.removingSubjects.filter(x => x != _id),
      removingSubjectSearch: adding ? "" : this.state.removingSubjectSearch
    });
  };
  subjectSelectedToRemove = this.removingSubjectSet.bind(null, true);
  resetSubjects = () => {
    this.setState({
      addingSubjects: [],
      removingSubjects: []
    });
  };
  setAddingSearchVal = val => this.setState({ addingSubjectSearch: val });
  setRemovingSearchVal = val => this.setState({ removingSubjectSearch: val + "" });

  render() {
    let dontAddSubject = this.addingSubjectSet.bind(null, false),
      dontRemoveSubject = this.removingSubjectSet.bind(null, false);

    return (
      <Modal className="fade" show={!!this.props.modifyingBooks.length} onHide={this.props.onDone}>
        <Modal.Header>
          <button type="button" className="close" onClick={this.props.onDone} aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 className="modal-title">Add / Remove Subjects:</h4>
        </Modal.Header>
        <Modal.Body>
          <ul className="nav nav-tabs">
            <li className={this.state.currentTab == "subjects" ? "active" : ""}>
              <a onClick={() => this.setState({ currentTab: "subjects" })}>Choose subjects</a>
            </li>
            <li className={this.state.currentTab == "books" ? "active" : ""}>
              <a onClick={() => this.setState({ currentTab: "books" })}>For books</a>
            </li>
          </ul>
          <div className="tab-content">
            <div style={{ minHeight: "150px" }} className={"tab-pane " + (this.state.currentTab == "subjects" ? "active in" : "")}>
              <br />
              <div style={{ position: "relative" }} className="row">
                <div className="col-xs-3">
                  <SelectAvailable
                    placeholder="Adding"
                    search={this.state.addingSubjectSearch}
                    onSearchChange={this.setAddingSearchVal}
                    items={this.props.subjectsUnwound}
                    currentlySelected={this.state.addingSubjects}
                    onSelect={this.subjectSelectedToAdd}
                    filter={filterSubjects}
                  />
                </div>
                <div className="col-xs-9">
                  <div>
                    {this.state.addingSubjects.map(_id => this.props.subjectHash[_id]).map((s: any, i) => (
                      <span
                        key={i}
                        style={{ color: s.textColor || "white", backgroundColor: s.backgroundColor, display: "inline-table" }}
                        className="label label-default margin-left"
                      >
                        <a onClick={() => dontAddSubject(s)} style={{ color: s.textColor || "white", paddingRight: "5px", marginRight: "5px" }}>
                          X
                        </a>
                        {s.name}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              <br />

              <div style={{ position: "relative" }} className="row">
                <div className="col-xs-3">
                  <SelectAvailable
                    placeholder="Removing"
                    search={this.state.removingSubjectSearch}
                    onSearchChange={this.setRemovingSearchVal}
                    items={this.props.subjectsUnwound}
                    currentlySelected={this.state.removingSubjects}
                    onSelect={this.subjectSelectedToRemove}
                    filter={filterSubjects}
                  />
                </div>
                <div className="col-xs-9">
                  <div>
                    {this.state.removingSubjects.map(_id => this.props.subjectHash[_id]).map((s: any, i) => (
                      <span
                        key={i}
                        style={{ color: s.textColor || "white", backgroundColor: s.backgroundColor, display: "inline-table" }}
                        className="label label-default margin-left"
                      >
                        <a onClick={() => dontRemoveSubject(s)} style={{ color: s.textColor || "white", paddingRight: "5px", marginRight: "5px" }}>
                          X
                        </a>
                        {s.name}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              <br />
              <BootstrapButton onClick={this.resetSubjects} className="pull-right" preset="default-xs">
                Reset subjects
              </BootstrapButton>
              <br style={{ clear: "both" }} />
            </div>
            <div style={{ minHeight: "150px" }} className={"tab-pane " + (this.state.currentTab == "books" ? "active in" : "")}>
              <br />
              <ul className="list-unstyled" style={{ marginLeft: "10px" }}>
                {this.props.modifyingBooks.map(book => <li key={book._id}>{book.title}</li>)}
              </ul>
              <br />
            </div>
          </div>
        </Modal.Body>
        <Modal.Footer>
          <AjaxButton preset="primary" running={this.props.running} runningText="Setting" onClick={this.setBooksSubjects}>
            Set
          </AjaxButton>
          <BootstrapButton preset="" onClick={this.props.onDone}>
            Cancel
          </BootstrapButton>
        </Modal.Footer>
      </Modal>
    );
  }
}

// svelte-kit/src/routes/(logged-in)/books/BookSubjectSetter.svelte
<script lang="ts">
  // import { mutation } from "micro-graphql-svelte";
  // import { MutationOf, Mutations } from "gql/graphql-typings";

  //import updateBookSubjects from "gql/books/updateBookSubjects.graphql";

  import { page } from "$app/stores";
  import type { Subject } from "$data/types";
  import DisplaySelectedSubjects from "$lib/components/subjectsAndTags/subjects/DisplaySelectedSubjects.svelte";
  import SelectAvailableSubjects from "$lib/components/subjectsAndTags/subjects/SelectAvailableSubjects.svelte";

  import Modal from "$lib/components/ui/Modal.svelte";
  import StandardModalFooter from "$lib/components/ui/StandardModalFooter.svelte";
  import Button from "$lib/components/buttons/Button.svelte";
  import ActionButton from "$lib/components/buttons/ActionButton.svelte";

  import { Tabs, TabHeaders, TabHeader, TabContents, TabContent } from "$lib/components/layout/tabs/index";

  import FlexRow from "$lib/components/layout/FlexRow.svelte";
  import Stack from "$lib/components/layout/Stack.svelte";
  import FlowItems from "$lib/components/layout/FlowItems.svelte";
  import { enhance } from "$app/forms";

  $: subjects = $page.data.subjects;
  export let modifyingBooks: any[];
  export let isOpen: boolean;
  export let onHide: () => void;

  interface ILocalProps {
    modifyingBooks: any[];
    onDone: any;
  }

  let addingSubjects: string[] = [];
  let removingSubjects: string[] = [];

  const resetSubjects = () => {
    addingSubjects = [];
    removingSubjects = [];
  };

  //const { mutationState } = mutation<MutationOf<Mutations["updateBooks"]>>(updateBookSubjects);
  //$: ({ runMutation, running } = $mutationState);

  let saving = false;
  const save = () => {
    //let args = { books: modifyingBooks.map(b => b._id), add: addingSubjects, remove: removingSubjects };
    //return Promise.resolve(runMutation(args)).then(() => {
    //onHide();
    //});
    saving = true;
    return async ({ result }: any) => {
      //onBookUpdated(_id, result.data.updates);
      onHide();
      saving = false;
    };
  };
  const addingSubjectSet = (adding: boolean, { _id }: Subject) =>
    (addingSubjects = adding ? addingSubjects.concat(_id) : addingSubjects.filter(x => x != _id));
  const subjectSelectedToAdd = addingSubjectSet.bind(null, true);

  const removingSubjectSet = (adding: boolean, { _id }: Subject) =>
    (removingSubjects = adding ? removingSubjects.concat(_id) : removingSubjects.filter(x => x != _id));
  const subjectSelectedToRemove = removingSubjectSet.bind(null, true);

  const dontAddSubject = addingSubjectSet.bind(null, false);
  const dontRemoveSubject = removingSubjectSet.bind(null, false);

  let closeModal: () => void;
</script>

<Modal {isOpen} {onHide} headerCaption="Add / Remove Subjects" standardFooter={false}>
  <form method="post" action="?/setBooksSubjects" use:enhance={save}>
    <Tabs defaultTab="subjects">
      <TabHeaders>
        <TabHeader tabName="subjects" text="Choose subjects" />
        <TabHeader tabName="books" text="For books" />
      </TabHeaders>
      <TabContents>
        <TabContent tabName="subjects">
          <input type="hidden" name="_ids" value={modifyingBooks.map(b => b._id)} />
          {#each addingSubjects as s}
            <input type="hidden" name="add" value={s} />
          {/each}
          {#each addingSubjects as s}
            <input type="hidden" name="remove" value={s} />
          {/each}
          <FlexRow>
            <div class="col-xs-3">
              <SelectAvailableSubjects {subjects} placeholder="Adding" currentlySelected={addingSubjects} onSelect={subjectSelectedToAdd} />
            </div>
            <div class="col-xs-9" style="display: flex; flex-wrap: wrap">
              <DisplaySelectedSubjects {subjects} currentlySelected={addingSubjects} onRemove={dontAddSubject} />
            </div>

            <div class="col-xs-3">
              <SelectAvailableSubjects {subjects} placeholder="Removing" currentlySelected={removingSubjects} onSelect={subjectSelectedToRemove} />
            </div>
            <div class="col-xs-9" style="display: flex; flex-wrap: wrap">
              <DisplaySelectedSubjects {subjects} currentlySelected={removingSubjects} onRemove={dontRemoveSubject} />
            </div>

            <div class="col-xs-12">
              <Button onClick={resetSubjects} preset="default-xs">Reset subjects</Button>
            </div>
          </FlexRow>
        </TabContent>
        <TabContent tabName="books">
          <Stack style="font-size: 14px">
            {#each modifyingBooks as book (book._id)}
              <div>{book.title}</div>
            {/each}
          </Stack>
        </TabContent>
      </TabContents>
    </Tabs>
    <StandardModalFooter bind:closeModal>
      <FlowItems pushLast={true}>
        <ActionButton isRunning={saving} style="min-width: 10ch" preset="primary" text="Save" runningText="Saving" finishedText="Saved" />

        <Button type="button" style="min-width: 10ch" preset="" onClick={closeModal}>Cancel</Button>
      </FlowItems>
    </StandardModalFooter>
  </form>
</Modal>
