// react/modules/books/components/subjectEditModal.tsx
import React, { FunctionComponent, useState } from "react";
import {Button} from "app/components/ui/Button";

import Modal from "app/components/ui/Modal";

import EditSubject from "app/components/subjectsAndTags/subjects/EditSubject";
import FlowItems from "app/components/layout/FlowItems";
import Stack from "app/components/layout/Stack";
import SelectAvailableSubjects from "app/components/subjectsAndTags/subjects/SelectAvailableSubjects";

interface ILocalProps {
  editModalOpen: boolean;
  stopEditing: any;
}

const SubjectEditModal: FunctionComponent<ILocalProps> = props => {
  const [editingSubject, setEditingSubject] = useState(null);

  const newSubject = () => startEditing({ name: "" });
  const editSubject = subject => {
    startEditing(subject);
  };
  const startEditing = subject => setEditingSubject(subject);
  const cancelEdit = () => setEditingSubject(null);

  return (
    <Modal isOpen={props.editModalOpen} onHide={props.stopEditing} headerCaption="Edit Subjects">
      <Stack>
        <FlowItems pushLast={true} xsFlowReverse={true}>
          <SelectAvailableSubjects placeholder="Edit subject" currentlySelected={[]} onSelect={item => editSubject(item)} />

          <Button onClick={newSubject} preset="info-xs">
            <span className="visible-xs">Add new subject </span>
            <i className="fa fa-fw fa-plus-square" />
          </Button>
        </FlowItems>

        {editingSubject ? <EditSubject subject={editingSubject} onCancelEdit={cancelEdit} /> : null}
        <hr />
      </Stack>
      <Button onClick={props.stopEditing}>Close</Button>
    </Modal>
  );
};

export default SubjectEditModal;

// svelte-kit/src/routes/(logged-in)/books/SubjectEditModal.svelte
<script lang="ts">
  import Button from "$lib/components/buttons/Button.svelte";
  import Modal from "$lib/components/ui/Modal.svelte";

  import EditSubject from "$lib/components/subjectsAndTags/subjects/EditSubject.svelte";
  import FlowItems from "$lib/components/layout/FlowItems.svelte";
  import Stack from "$lib/components/layout/Stack.svelte";
  import SelectAvailableSubjects from "$lib/components/subjectsAndTags/subjects/SelectAvailableSubjects.svelte";
  import type { Subject } from "$data/types";

  export let isOpen = false;
  export let onHide = () => {};

  const emptySubject = {
    _id: "",
    name: "",
    textColor: "",
    backgroundColor: "",
    path: ""
  };

  interface ILocalProps {
    editModalOpen: boolean;
    stopEditing: any;
  }
  let editingSubject: Subject | null = null;

  const cancelEdit = () => (editingSubject = null);
  const newSubject = () => (editingSubject = emptySubject);
  const editSubject = (subject: Subject) => (editingSubject = subject);

  let deleteShowing: boolean = false;

  export let subjects: Subject[];
</script>

<Modal {isOpen} {onHide} headerCaption="Edit Subjects" deferStateChangeOnClose={true}>
  <Stack>
    {#if !deleteShowing}
      <FlowItems pushLast={true} xsFlowReverse={true}>
        <SelectAvailableSubjects {subjects} placeholder="Edit subject" currentlySelected={[]} onSelect={item => editSubject(item)} />

        <Button onClick={newSubject} preset="info-xs">
          <span class="visible-xs">Add new subject </span>
          <i class="far fa-fw fa-plus-square" />
        </Button>
      </FlowItems>
    {/if}

    {#if editingSubject}
      <EditSubject bind:deleteShowing subject={editingSubject} onCancelEdit={cancelEdit} />
    {/if}
  </Stack>
</Modal>
