// react/app/components/subjectsAndTags/subjects/DisplaySelectedSubjects.tsx
import React, { FunctionComponent, useContext } from "react";
import { RemovableLabelDisplay, LabelDisplay } from "../LabelDisplay";
import { useSubjectsState } from "app/state/subjectsState";
import FlowItems from "../../layout/FlowItems";

type LocalProps = { currentlySelected: string[]; onRemove?: any };

const DisplaySelectedSubjects: FunctionComponent<LocalProps> = props => {
  const { subjectHash } = useSubjectsState();
  const { currentlySelected, onRemove } = props;

  return (
    <FlowItems tightest={true}>
      {currentlySelected
        .filter(_id => subjectHash[_id])
        .map(_id => subjectHash[_id])
        .map(t => (onRemove ? <RemovableLabelDisplay key={t._id} item={t} doRemove={() => onRemove(t)} /> : <LabelDisplay key={t._id} item={t} />))}
    </FlowItems>
  );
};

export default DisplaySelectedSubjects;

// svelte-kit/src/lib/components/subjectsAndTags/subjects/DisplaySelectedSubjects.svelte
<script lang="ts">
  import type { Subject } from "$data/types";

  import RemovableLabelDisplay from "../RemovableLabelDisplay.svelte";
  import LabelDisplay from "../LabelDisplay.svelte";
  import FlowItems from "../../layout/FlowItems.svelte";
  import { toHash } from "$lib/state/helpers";

  export let currentlySelected: any[];
  export let onRemove: ((s: Subject) => void) | null = null;

  export let subjects: Subject[];

  $: subjectHash = toHash(subjects);
</script>

<FlowItems tightest={true}>
  {#each currentlySelected.filter(_id => subjectHash[_id]).map(_id => subjectHash[_id]) as t}
    {#if onRemove}
      <RemovableLabelDisplay item={t} doRemove={() => onRemove?.(t)} />
    {:else}
      <LabelDisplay item={t} />
    {/if}
  {/each}
</FlowItems>
