// svelte-kit/src/lib/components/layout/FlexRow.svelte
<script>
  import cn from "classnames";

  let className = "";
  export { className as class };

  export let style = "";
  export let containerStyle = "";
  export let tighter = false;
  export let tightest = false;
  export let xsFlowReverse = false;
</script>

<div {style} class={cn("old-flex-row", className || "", { tighter, tightest, ["xs-pull-reverse"]: xsFlowReverse })}>
  <div style={containerStyle}>
    <slot />
  </div>
</div>

// react/app/components/layout/FlexRow.tsx
import React from "react";
import cn from "classnames";

export default ({ className = "", tighter = false, tightest = false, xsFlowReverse = false, children }) => (
  <div className={cn("flex-row", className, { tighter, tightest, ["xs-pull-reverse"]: xsFlowReverse })}>
    <div>{children}</div>
  </div>
);
