// svelte-kit/src/lib/components/layout/FlowItems.svelte
<script>
  import cn from "classnames";

  let className = $$props["class"];
  export let style = "";
  export let containerStyle = "";
  export let xsFlowReverse = false;
  export let tighter = false;
  export let tightest = false;
  export let vCenter = false;
  export let pushLast = false;

  const cssClasses = {
    tighter,
    tightest,
    ["v-center"]: vCenter,
    ["push-last"]: pushLast,
    ["xs-pull-reverse"]: xsFlowReverse
  };
</script>

<div class={cn('flow-items', className, cssClasses)} style={style}>
  <div style={containerStyle}>
    <slot />
  </div>
</div>

// react/app/components/layout/FlowItems.tsx
import React, { SFC, FC } from "react";
import cn from "classnames";

type Props = {
  className?: string;
  xsFlowReverse?: boolean;
  tighter?: boolean;
  tightest?: boolean;
  vCenter?: boolean;
  pushLast?: boolean;
};

const FlowItems: FC<Props> = ({ className = "", xsFlowReverse, tighter, tightest, vCenter, pushLast, children }) => {
  const cssClasses = {
    tighter,
    tightest,
    ["v-center"]: vCenter,
    ["push-last"]: pushLast,
    ["xs-pull-reverse"]: xsFlowReverse
  };

  return (
    <div className={cn("flow-items", className, cssClasses)}>
      <div>{children}</div>
    </div>
  );
};

export default FlowItems;
