// svelte/app/components/layout/Stack.svelte
<script>
  import cn from "classnames";

  let className = "";
  export { className as class };
  export let style = "";
  export let tighter = false;
  export let tightest = false;
  export let looser = false;
  export let loosest = false;
</script>

<div {style} class={cn('stack', className, { tighter, tightest, looser, loosest })} {...$$restProps}>
  <slot />
</div>

// react/app/components/layout/Stack.tsx
import React from "react";
import cn from "classnames";

export default ({ className = "", style = {}, tighter = false, tightest = false, looser = false, loosest = false, children }) => (
  <div style={style} className={cn("stack", className, { tighter, tightest, looser, loosest })}>{children}</div>
);
