// svelte/app/components/subjectsAndTags/subjects/DisplaySelectedSubjects.svelte
<script lang="ts">
  import RemovableLabelDisplay from "../RemovableLabelDisplay.svelte";
  import LabelDisplay from "../LabelDisplay.svelte";
  import { subjectsState } from "app/state/subjectsState";
  import FlowItems from "../../layout/FlowItems.svelte";

  export let currentlySelected: any[];
  export let onRemove: any;

  $: ({ subjectHash } = $subjectsState);
</script>

<FlowItems tightest={true}>
  {#each currentlySelected.filter(_id => subjectHash[_id]).map(_id => subjectHash[_id]) as t}
    {#if onRemove}
      <RemovableLabelDisplay item={t} doRemove={() => onRemove(t)} />
    {:else}
      <LabelDisplay item={t} />
    {/if}
  {/each}
</FlowItems>

// react/app/components/displaySelectedSubjects.tsx
import React, { FunctionComponent, useContext } from "react";
import { RemovableLabelDisplay } from "./labelDisplay";
import { useSubjectsState } from "app/subjectsState";
import FlowItems from "./layout/FlowItems";

type LocalProps = { currentlySelected: string[]; onRemove: any };

const DisplaySelectedSubjects: FunctionComponent<LocalProps> = props => {
  const { subjectHash } = useSubjectsState();

  return (
    <FlowItems tightest={true}>
      {props.currentlySelected
        .filter(_id => subjectHash[_id])
        .map(_id => subjectHash[_id])
        .map(t => (
          <RemovableLabelDisplay key={t._id} item={t} doRemove={() => props.onRemove(t)} />
        ))}
    </FlowItems>
  );
};

export default DisplaySelectedSubjects;
