// svelte-kit/src/lib/components/navigation/MainNavigation.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { signIn, signOut } from "@auth/sveltekit/client";

  import NavBarItem from "./NavBarItem.svelte";
  import ModuleLink from "./ModuleLink.svelte";

  import BookSvg from "./BookSvg.svelte";

  import "$styles/navbar.scss";
  import "./mobile-menu.scss";
  import { onMount } from "svelte";
  import { invalidateAll } from "$app/navigation";
  import { publicUserIdPersist } from "$lib/state/urlHelpers";

  $: ({ loggedIn, isPublic } = $page.data);

  $: pathname = $page.url.pathname;
  $: isSettings = /\/settings/.test(pathname);

  let isAdminUser = false;

  const homeModules = new Set(["/", "/discover", "/recent-scans"]);
  $: isHome = homeModules.has(pathname);

  let pendingCount = 0;

  function handleWsPendingCountUpdate(evt: any) {
    const detail = evt?.detail || {};

    if (typeof detail.pendingCount === "number") {
      pendingCount = detail.pendingCount;
    }
  }

  onMount(() => {
    window.addEventListener("ws-info", handleWsPendingCountUpdate);
  });
</script>

<header class="master-nav">
  <nav class="nav">
    <div class={`nav-header hidden-xs ${isHome && loggedIn ? "active" : ""}`}>
      <ModuleLink href="/">
        <BookSvg height="18" style="margin-right: 10px; color: white; fill: var(--primary-10);" />
        <span>My Library</span>
      </ModuleLink>
    </div>

    <ul class="nav-items">
      <NavBarItem class="visible-xs" disabled={isPublic} href="/" style="margin-top: '2px';" label={"Home"}>
        <i class="fal fa-fw fa-home visible-xs" />
      </NavBarItem>
      {#if loggedIn || isPublic}
        <NavBarItem disabled={isPublic} href="/scan" style="position: relative;" label={"Scan books"}>
          <span class="hidden-xs">Book entry</span>
          <i class="visible-xs fal fa-fw fa-scanner" />
          {#if pendingCount}
            <span class={`number-badge ${pendingCount > 9 ? "big-count" : ""}`}>
              <span class="overlay-holder">
                <i class="fas fa-badge" />
                <span>{pendingCount}</span>
              </span>
            </span>
          {/if}
        </NavBarItem>
      {/if}
      {#if loggedIn || isPublic}
        <NavBarItem href={$publicUserIdPersist.urlTo("/books")} label={"View books"}>
          <span class="hidden-xs">Books</span>
          <i class="visible-xs fal fa-fw fa-books" />
        </NavBarItem>
      {/if}
      {#if loggedIn || isPublic}
        <NavBarItem disabled={isPublic} href="/subjects" label={"Manage subjects"}>
          <span class="hidden-xs">Subjects</span>
          <i class="visible-xs fal fa-fw fa-sitemap" />
        </NavBarItem>
      {/if}
      {#if loggedIn || isPublic}
        <NavBarItem active={isSettings} href={$publicUserIdPersist.urlTo("/settings/theme")} label={"Settings"}>
          <span class="hidden-xs">Settings</span>
          <i class="visible-xs fal fa-fw fa-cogs" />
        </NavBarItem>
      {/if}
      {#if loggedIn && isAdminUser}
        <NavBarItem href="/admin" label={"Admin"}>
          <span class="hidden-xs">Admin</span>
          <i class="visible-xs fal fa-fw fa-users-cog" />
        </NavBarItem>
      {/if}
    </ul>
    <ul class="nav-items-right">
      {#if !loggedIn}
        <NavBarItem
          onClick={() =>
            signIn("google", {
              callbackUrl: "/books"
            })}
          label={"Login"}
        >
          <span class="hidden-xs">Login</span>
          <i class="visible-xs fal fa-fw fa-sign-in" />
        </NavBarItem>
      {/if}
    </ul>
    {#if loggedIn}
      <ul class="nav-items-right">
        <NavBarItem onClick={() => signOut().then(() => invalidateAll())} label={"Logout"}>
          <span class="hidden-xs">Logout</span>
          <i class="visible-xs fal fa-fw fa-sign-out" />
        </NavBarItem>
      </ul>
    {/if}
  </nav>
  <div id="main-mobile-menu" class="main-mobile-menu" />
</header>

<style>
  header :global(a) {
    text-decoration: none;
  }
</style>

// react/app/components/mainNavigation.tsx
import React, { memo, FunctionComponent, useContext, useState, useEffect, useLayoutEffect } from "react";
import { createPortal } from "react-dom";

import { goto } from "util/urlHelpers";
import ajaxUtil from "util/ajaxUtil";
import { AppContext } from "app/state/appState";

import { isAdmin } from "util/loginStatus";
import BookSvg from "./bookSvg";

import "css/navbar.scss";
import "css/main-mobile-menu.scss";

const spreadClassNames = (baseCssClasses = "", ...userClasses) => `${baseCssClasses} ${userClasses.join(" ")}`;

const NavBarItem = props => {
  let { disabled, className, active, href, onClick, children, aStyle = {}, ...rest } = props;

  return (
    <li className={spreadClassNames(className, !!disabled ? "disabled" : "", active ? "active" : "")} {...rest}>
      <a style={aStyle} onClick={onClick}>
        {children}
      </a>
    </li>
  );
};

const MainNavigationBar: FunctionComponent<{}> = props => {
  const logout = () => {
    ajaxUtil.postAuth("/logout", {}, () => ((window as any).location = "/"));
  };

  let isAdminUser = isAdmin();

  let [{ isPublic, module, isLoggedIn }] = useContext(AppContext);
  let isHome = module == "home";
  let isBookEntry = module == "scan";
  let isBookList = module == "books" || module == "view";
  let isSubjects = module == "subjects";
  let isLoginModule = module == "authenticate";
  let isSettings = module == "settings";
  let isSettingsSection = module == "admin";

  let [pendingCount, setPendingCount] = useState(0);

  function handleWsPendingCountUpdate(evt) {
    if (typeof evt?.detail?.pendingCount === "number") {
      setPendingCount(evt.detail.pendingCount);
    }
  }
  useEffect(() => {
    window.addEventListener("ws-info", handleWsPendingCountUpdate);
    return () => window.removeEventListener("ws-info", handleWsPendingCountUpdate);
  }, []);

  return (
    <header className="master-nav">
      <nav className="nav">
        <div className={`nav-header hidden-xs ${isHome && isLoggedIn ? "active" : ""}`}>
          <a onClick={() => goto("home")}>
            <BookSvg height="18" style={{ marginRight: "10px", color: "white", fill: "var(--primary-10)" }} />
            <span>My Library</span>
          </a>
        </div>

        <ul className="nav-items">
          <NavBarItem className="visible-xs" disabled={isPublic} onClick={() => goto("home")} active={isHome} aStyle={{ marginTop: "2px" }}>
            <i className="fal fa-home visible-xs" />
          </NavBarItem>
          {isLoggedIn || isPublic ? (
            <NavBarItem disabled={isPublic} onClick={isPublic ? null : () => goto("scan")} active={isBookEntry} style={{ position: "relative" }}>
              <span className="hidden-xs">Book entry</span>
              <i className="visible-xs fal fa-scanner" />
              {pendingCount ? (
                <span className={`number-badge ${pendingCount > 9 ? "big-count" : ""}`}>
                  <span className="overlay-holder">
                    <i className="fas fa-badge"></i>
                    <span>{pendingCount}</span>
                  </span>
                </span>
              ) : null}
            </NavBarItem>
          ) : null}
          {isLoggedIn || isPublic ? (
            <NavBarItem active={isBookList} onClick={() => goto(isPublic ? "view" : "books")}>
              <span className="hidden-xs">Books</span>
              <i className="visible-xs fal fa-books" />
            </NavBarItem>
          ) : null}
          {isLoggedIn || isPublic ? (
            <NavBarItem disabled={isPublic} onClick={isPublic ? null : () => goto("subjects")} active={isSubjects}>
              <span className="hidden-xs">Subjects</span>
              <i className="visible-xs fal fa-sitemap" />
            </NavBarItem>
          ) : null}
          {isLoggedIn || isPublic ? (
            <NavBarItem onClick={() => goto("settings")} active={isSettings}>
              <span className="hidden-xs">Settings</span>
              <i className="visible-xs fal fa-cogs" />
            </NavBarItem>
          ) : null}
          {isLoggedIn && isAdminUser ? (
            <NavBarItem onClick={() => goto("admin")} active={isSettingsSection}>
              <span className="hidden-xs">Admin</span>
              <i className="visible-xs fal fa-users-cog" />
            </NavBarItem>
          ) : null}
        </ul>
        <ul className="nav-items-right">
          {!isLoggedIn && !isLoginModule ? (
            <NavBarItem onClick={() => goto("login")}>
              <span className="hidden-xs">Login</span>
              <i className="visible-xs fal fa-sign-in" />
            </NavBarItem>
          ) : null}
        </ul>
        {isLoggedIn ? (
          <ul className="nav-items-right">
            <NavBarItem onClick={logout}>
              <span className="hidden-xs">Logout</span>
              <i className="visible-xs fal fa-sign-out" />
            </NavBarItem>
          </ul>
        ) : null}
      </nav>
      <div id="main-mobile-menu" className="main-mobile-menu"></div>
    </header>
  );
};

export default MainNavigationBar;

const _MobileMenu = ({ title, open, onClose, children }) => {
  const [el] = useState(() => document.getElementById("main-mobile-menu"));
  useLayoutEffect(() => el.classList[open ? "add" : "remove"]("open"), [open]);

  return createPortal(
    <div className="mobile-menu-content">
      <div>
        <div className="header">
          <a style={{ fontSize: "1.4rem", alignSelf: "start" }} onClick={onClose}>
            <i className="far fa-bars"></i>
          </a>
          <h3 style={{ margin: "0 0 0 10px", alignSelf: "center" }}>{title}</h3>
        </div>
        {children}
      </div>
    </div>,
    el
  );
};

export const MobileMenu = memo(_MobileMenu);
