// svelte/app/components/subjectsAndTags/tags/SelectAvailableTags.svelte
<script lang="ts">
  import { filterTags, tagsState } from "app/state/tagsState";
  import GenericLabelSelect from "../GenericLabelSelect.svelte";

  export let onSelect;
  export let placeholder = "Tags";
  export let currentlySelected = [];

  $: ({ tags } = $tagsState);
  let search = "";

  const doSelect = item => {
    onSelect(item);
    search = "";
  };

  $: itemHash = currentlySelected.reduce((hash, _idOrObj) => ((hash[_idOrObj] = true), hash), {});
  $: eligible = filterTags(
    tags.filter(s => !itemHash[s._id]),
    search
  );
</script>

<GenericLabelSelect {placeholder} bind:search inputProps={{ tabIndex: -1 }} options={eligible} onItemSelected={doSelect} />

// react/app/components/selectAvailableTags.tsx
import React, { FunctionComponent, useContext } from "react";
import SelectAvailableItems from "./availableTagsOrSubjects";
import { filterTags, TagsContext } from "app/tagsState";

type LocalProps = { currentlySelected: string[]; onSelect: any };

const SelectAvailableTags: FunctionComponent<LocalProps> = props => {
  const { tags } = useContext(TagsContext);
  return (
    <SelectAvailableItems placeholder="Tags" items={tags} currentlySelected={props.currentlySelected} onSelect={props.onSelect} filter={filterTags} />
  );
};

export default SelectAvailableTags;
