// react-redux/app/components/labelDisplay.tsx
import React from "react";

export const LabelDisplay = props => {
  let item = props.item,
    extraStyles = props.style || {},
    extraClasses = props.className || "";

  return (
    <span
      style={{ backgroundColor: item.backgroundColor, color: item.textColor || "white", ...extraStyles }}
      className={"label label-default noselect " + extraClasses}
    >
      {props.children || item.name}
    </span>
  );
};

export const RemovableLabelDisplay = props => {
  let item = props.item;
  let extraStyles = props.style || {};
  let extraClasses = props.className || "";

  return (
    <span
      style={{ backgroundColor: item.backgroundColor, color: item.textColor || "white", ...extraStyles }}
      className={"label label-default noselect " + extraClasses}
    >
      <a onClick={props.doRemove} style={{ color: item.textColor || "white", cursor: "pointer" }}>
        X
      </a>
      <span style={{ marginLeft: 5, paddingLeft: 5, borderLeft: "1px solid white" }}>{props.name}</span>
      {props.children || item.name}
    </span>
  );
};

// svelte-kit/src/lib/components/subjectsAndTags/LabelDisplay.svelte
<script lang="ts">
  export let onClick = null;
  export let item;
  export let extraStyles = "";
  export let disabled = false;
  let className = "";
  export { className as class };

  let extraClasses = className || "";
  let disabledStyles = "opacity: 0.4;";

  let stylesToAdd = extraStyles;
  if (disabled) {
    stylesToAdd = disabledStyles + stylesToAdd;
  }
</script>

<span
  on:click={onClick ? () => onClick(item) : e => (e.cancelBubble = false)}
  style="cursor: {onClick ? 'pointer' : 'default'}; background-color: {item.backgroundColor}; color: {item.textColor || 'white'}; {stylesToAdd}"
  class={"label label-default noselect " + extraClasses}
>
  {#if $$slots.default}
    <slot />
  {:else}{item.name}{/if}
</span>
