// svelte-kit/src/routes/(core-data)/(home)/recent-scans/+page.svelte
<script lang="ts">
  import Alert from "$lib/components/Alert.svelte";
  import ActionButton from "$lib/components/Button/ActionButton.svelte";
  import BookCover from "$lib/components/BookCover.svelte";

  export let data;

  $: ({ scans, nextPageKey } = data);

  let loading: boolean;

  function loadNextScans() {
    loading = true;

    fetch(`/api/recent-scans?next-page-key=${$nextPageKey}`)
      .then(resp => resp.json())
      .then(resp => {
        scans.update(current => current.concat(resp.scans));
        nextPageKey.set(resp.nextPageKey);

        loading = false;
      });
  }

  let noResultsMessage: string;

  $: noResultsMessage = $scans.length ? "No more recent scans" : "No recent scans";
</script>

<div class="recent-scans-module">
  <div class="overlay-holder">
    <div class="grid grid-cols-[75px_1fr] gap-4">
      {#each $scans as item}
        {#if item.success}
          <BookCover size="small" book={item} />

          <div>{item.title ?? `${item.isbn} Failure`}</div>
        {:else}
          <div />
          <div>
            <Alert type="error" class="w-[40ch] inline-flex">
              Failed to lookup isbn {item.isbn}
            </Alert>
          </div>
        {/if}
      {/each}

      {#if $nextPageKey}
        <div />
        <ActionButton class="w-[40ch]" theme="primary" running={loading} on:click={loadNextScans}>Load More</ActionButton>
      {/if}
    </div>
  </div>
  {#if !$nextPageKey}
    <div>
      {#if $scans.length}
        <hr class="my-3" />
      {/if}
      <Alert type="info">
        {noResultsMessage}
      </Alert>
    </div>
  {/if}
</div>

// react/modules/home/recent-scans/index.tsx
import React, { FunctionComponent, useEffect, useState } from "react";
const { useTransition } = React as any;

import { Queries, QueryOf } from "graphql-typings";
import "./styles.scss";

import RecentScansQuery from "../../../graphQL/recent-scans/recentScans.graphql";
import { Button } from "app/components/ui/Button";
import { SuspenseImg } from "app/components/suspenseImage";
import { graphqlClient } from "util/graphql";

const RecentScans: FunctionComponent = () => {
  const [loading, startTransition] = useTransition();

  const [currentNextPageKeys, setCurrentNextPageKeys] = useState<any>([null]);
  const [nextNextPageKey, setNextNextPageKey] = useState<any>(null);

  const recentScans = currentNextPageKeys.flatMap(lastKey => {
    const result = graphqlClient.read<QueryOf<Queries["recentScanResults"]>>(RecentScansQuery, { lastKey });
    return result.data?.recentScanResults?.ScanResults ?? [];
  });
  const latestKey = currentNextPageKeys[currentNextPageKeys.length - 1];
  const latestKeyData = graphqlClient.read<QueryOf<Queries["recentScanResults"]>>(RecentScansQuery, { lastKey: latestKey });
  const newLastKey = latestKeyData.data?.recentScanResults?.LastEvaluatedKey;

  useEffect(() => {
    setNextNextPageKey(newLastKey);
  }, [newLastKey]);

  const loadNextScans = () => {
    startTransition(() => {
      setCurrentNextPageKeys(arr => arr.concat(nextNextPageKey));
    });
  };

  return (
    <div className="recent-scans-module">
      <div className="overlay-holder">
        <div className="results">
          {recentScans.map((item, i) => (item.success ? <ScanDisplay key={i} item={item} /> : <ScanFailureDisplay item={item} key={i} />))}
          {nextNextPageKey ? (
            <>
              <div></div>
              <Button preset="info" disabled={loading} onClick={loadNextScans}>
                Load More
              </Button>
            </>
          ) : (
            <NoMoreResults />
          )}
        </div>
      </div>
    </div>
  );
};

const ScanDisplay = ({ item }) => {
  return (
    <>
      <SuspenseImg src={item.smallImage} />
      <div>{item.title ?? `${item.isbn} Failure`}</div>
    </>
  );
};

const ScanFailureDisplay = ({ item }) => {
  return (
    <>
      <div></div>
      <div>
        <div className="alert alert-danger inline-flex">Failed to lookup isbn {item.isbn}</div>
      </div>
    </>
  );
};

const NoMoreResults = () => {
  return (
    <>
      <div></div>
      <div>
        <hr />
        <div className="alert alert-info">No more recent scans</div>
      </div>
    </>
  );
};

export default RecentScans;
