// svelte/modules/books/BookTagSetter.svelte
<script lang="ts">
  import { mutation } from "micro-graphql-svelte";
  import { MutationOf, Mutations } from "graphQL/graphql-typings";

  import updateBookTags from "graphQL/books/updateBookTags.graphql";

  import SelectAvailableTags from "app/components/subjectsAndTags/tags/SelectAvailableTags.svelte";
  import DisplaySelectedTags from "app/components/subjectsAndTags/tags/DisplaySelectedTags.svelte";

  import Modal from "app/components/ui/Modal.svelte";
  import StandardModalFooter from "app/components/ui/StandardModalFooter.svelte";
  import Button from "app/components/buttons/Button.svelte";
  import ActionButton from "app/components/buttons/ActionButton.svelte";
  import Tabs from "app/components/layout/tabs/Tabs.svelte";
  import TabHeaders from "app/components/layout/tabs/TabHeaders.svelte";
  import TabHeader from "app/components/layout/tabs/TabHeader.svelte";
  import TabContents from "app/components/layout/tabs/TabContents.svelte";
  import TabContent from "app/components/layout/tabs/TabContent.svelte";

  import FlexRow from "app/components/layout/FlexRow.svelte";
  import Stack from "app/components/layout/Stack.svelte";
  import FlowItems from "app/components/layout/FlowItems.svelte";

  export let modifyingBooks: any[];
  export let isOpen;
  export let onHide;

  interface ILocalProps {
    modifyingBooks: any[];
    onDone: any;
  }

  let addingTags = [];
  let removingTags = [];

  const resetTags = () => {
    addingTags = [];
    removingTags = [];
  };

  const { mutationState } = mutation<MutationOf<Mutations["updateBooks"]>>(updateBookTags);
  $: ({ runMutation, running } = $mutationState);

  const save = () => {
    let args = { books: modifyingBooks.map(b => b._id), add: addingTags, remove: removingTags };
    return Promise.resolve(runMutation(args)).then(() => {
      onHide();
    });
  };
  const addingTagSet = (adding, { _id }) => (addingTags = adding ? addingTags.concat(_id) : addingTags.filter(x => x != _id));
  const tagSelectedToAdd = addingTagSet.bind(null, true);

  const removingTagSet = (adding, { _id }) => (removingTags = adding ? removingTags.concat(_id) : removingTags.filter(x => x != _id));
  const tagSelectedToRemove = removingTagSet.bind(null, true);

  const dontAddTag = addingTagSet.bind(null, false);
  const dontRemoveTag = removingTagSet.bind(null, false);

  let closeModal;
</script>

<Modal {isOpen} {onHide} headerCaption="Add / Remove Tags" deferStateChangeOnClose={true} standardFooter={false}>
  <Tabs defaultTab="tags">
    <TabHeaders>
      <TabHeader tabName="tags"><a>Choose tags</a></TabHeader>
      <TabHeader tabName="books"><a>For books</a></TabHeader>
    </TabHeaders>
    <TabContents>
      <TabContent tabName="tags">
        <FlexRow>
          <div class="col-xs-3">
            <SelectAvailableTags placeholder="Adding" currentlySelected={addingTags} onSelect={tagSelectedToAdd} />
          </div>
          <div class="col-xs-9" style="display: flex; flex-wrap: wrap">
            <DisplaySelectedTags currentlySelected={addingTags} onRemove={dontAddTag} />
          </div>

          <div class="col-xs-3">
            <SelectAvailableTags placeholder="Removing" currentlySelected={removingTags} onSelect={tagSelectedToRemove} />
          </div>
          <div class="col-xs-9" style="display: flex; flex-wrap: wrap">
            <DisplaySelectedTags currentlySelected={removingTags} onRemove={dontRemoveTag} />
          </div>

          <div class="col-xs-12">
            <Button onClick={resetTags} preset="default-xs">Reset tags</Button>
          </div>
        </FlexRow>
      </TabContent>
      <TabContent tabName="books">
        <Stack style="font-size: 14px">
          {#each modifyingBooks as book (book._id)}
            <div>{book.title}</div>
          {/each}
        </Stack>
      </TabContent>
    </TabContents>
  </Tabs>
  <StandardModalFooter bind:closeModal>
    <FlowItems pushLast={true}>
      <ActionButton style="min-width: 10ch" preset="primary" text="Save" runningText="Saving" finishedText="Saved" onClick={save} />

      <Button style="min-width: 10ch" preset="" onClick={closeModal}>Cancel</Button>
    </FlowItems>
  </StandardModalFooter>
</Modal>

// react-redux/modules/books/components/bookTagSetter.tsx
import React, { SFC, useState, useLayoutEffect, useContext } from 'react';

import BootstrapButton, { AjaxButton } from 'applicationRoot/components/bootstrapButton';
import SelectAvailable from 'applicationRoot/components/availableTagsOrSubjects';

import { useMutation, buildMutation } from 'micro-graphql-react';
import updateBookSubjects from 'graphQL/books/updateBookTags.graphql';

import Modal from 'applicationRoot/components/modal';
import { filterTags, TagsContext } from 'applicationRoot/tagsState';

const BookTagSetterDesktop: SFC<{ modifyingBooks: any[]; onDone: any }> = props => {
  const { tagHash, tags } = useContext(TagsContext);
  const [currentTab, setTab] = useState('tags');
  const [addingTags, setAddingTags] = useState([]);
  const [removingTags, setRemovingTags] = useState([]);
  const resetTags = () => {
    setRemovingTags([]);
    setAddingTags([]);
  };

  useLayoutEffect(() => {
    if (props.modifyingBooks.length) {
      resetTags();
    }
  }, [props.modifyingBooks.length]);
  const { runMutation, running } = useMutation(buildMutation(updateBookSubjects));

  const setBooksTags = () => {
    let args = { books: props.modifyingBooks.map(b => b._id), add: addingTags, remove: removingTags };
    Promise.resolve(runMutation(args)).then(() => {
      props.onDone();
    });
  };
  const addingTagSet = (adding, { _id }) => setAddingTags(adding ? addingTags.concat(_id) : addingTags.filter(x => x != _id));
  const tagSelectedToAdd = addingTagSet.bind(null, true);

  const removingTagSet = (adding, { _id }) => setRemovingTags(adding ? removingTags.concat(_id) : removingTags.filter(x => x != _id));
  const tagSelectedToRemove = removingTagSet.bind(null, true);

  const dontAddTag = addingTagSet.bind(null, false);
  const dontRemoveTag = removingTagSet.bind(null, false);
  const modifyingBooks = props.modifyingBooks || [];

  return (
    <Modal className="fade" isOpen={!!modifyingBooks.length} onHide={props.onDone} headerCaption="Add / Remove Tags:">
      <ul className="nav nav-tabs">
        <li className={currentTab == 'tags' ? 'active' : ''}>
          <a onClick={() => setTab('tags')}>Choose tags</a>
        </li>
        <li className={currentTab == 'books' ? 'active' : ''}>
          <a onClick={() => setTab('books')}>For books</a>
        </li>
      </ul>
      <div className="tab-content">
        <div style={{ minHeight: '150px' }} className={'tab-pane ' + (currentTab == 'tags' ? 'active in' : '')}>
          <br />
          <div style={{ position: 'relative' }} className="row">
            <div className="col-xs-3">
              <SelectAvailable placeholder="Adding" items={tags} currentlySelected={addingTags} onSelect={tagSelectedToAdd} filter={filterTags} />
            </div>
            <div className="col-xs-9">
              <div>
                {addingTags
                  .map(_id => tagHash[_id])
                  .map((s: any, i) => (
                    <span
                      key={i}
                      style={{ color: s.textColor || 'white', backgroundColor: s.backgroundColor, display: 'inline-table' }}
                      className="label label-default margin-left"
                    >
                      <a onClick={() => dontAddTag(s)} style={{ color: s.textColor || 'white', paddingRight: '5px', marginRight: '5px' }}>
                        X
                      </a>
                      {s.name}
                    </span>
                  ))}
              </div>
            </div>
          </div>

          <br />

          <div style={{ position: 'relative' }} className="row">
            <div className="col-xs-3">
              <SelectAvailable
                placeholder="Removing"
                items={tags}
                currentlySelected={removingTags}
                onSelect={tagSelectedToRemove}
                filter={filterTags}
              />
            </div>
            <div className="col-xs-9">
              <div>
                {removingTags
                  .map(_id => tagHash[_id])
                  .map((s: any, i) => (
                    <span
                      key={i}
                      style={{ color: s.textColor || 'white', backgroundColor: s.backgroundColor, display: 'inline-table' }}
                      className="label label-default margin-left"
                    >
                      <a onClick={() => dontRemoveTag(s)} style={{ color: s.textColor || 'white', paddingRight: '5px', marginRight: '5px' }}>
                        X
                      </a>
                      {s.name}
                    </span>
                  ))}
              </div>
            </div>
          </div>

          <br />
          <BootstrapButton onClick={resetTags} className="pull-right" preset="default-xs">
            Reset tags
          </BootstrapButton>
          <br />
        </div>
        <div style={{ minHeight: '150px' }} className={'tab-pane ' + (currentTab == 'books' ? 'active in' : '')}>
          <br />
          <ul className="list-unstyled">
            {modifyingBooks.map(book => (
              <li key={book._id}>{book.title}</li>
            ))}
          </ul>
          <br />
        </div>
      </div>
      <AjaxButton preset="primary" running={running} runningText="Setting" onClick={setBooksTags}>
        Set
      </AjaxButton>
      &nbsp;
      <BootstrapButton preset="" onClick={props.onDone}>
        Cancel
      </BootstrapButton>
    </Modal>
  );
};

export default BookTagSetterDesktop;
