// react/modules/books/components/menuBar/menuOptions.tsx
import React, { useContext, FunctionComponent, useMemo } from "react";
import { AppContext, ModuleUpdateContext } from "app/state/appState";

import { BooksModuleContext } from "../../booksState";

const MenuOptions: FunctionComponent<{
  Button: any;
  selectedBooksCount: number;
  uiView: any;
  uiDispatch: any;
  bookResultsPacket: any;
}> = props => {
  const [appState] = useContext(AppContext);
  const { Button, selectedBooksCount, uiView, uiDispatch, bookResultsPacket } = props;

  let { isPublic, online } = appState;
  const { actions, booksUiState } = useContext(BooksModuleContext);
  const { setRead } = actions;

  const { selectedBooks } = booksUiState;
  const selectedBooksIds = useMemo(() => Object.keys(selectedBooks).filter(k => selectedBooks[k]), [selectedBooks]);

  const { books = [], reload } = bookResultsPacket || {};

  const editSubjectsForSelectedBooks = () => actions.openBookSubModal(books.filter(b => booksUiState.selectedBooks[b._id]));
  const editTagsForSelectedBooks = () => actions.openBookTagModal(books.filter(b => booksUiState.selectedBooks[b._id]));

  const { isPending: booksLoading, startTransition } = useContext(ModuleUpdateContext);
  const reloadBooks = () => {
    startTransition(reload);
  };

  return !selectedBooksCount ? (
    <>
      <hr />
      {online ? (
        <>
          <Button title="Filter search" onClick={actions.beginEditFilters} className="btn btn-default">
            <span>Set Filters</span>
            <i className="fal fa-filter" />
          </Button>
          <hr />
          {!isPublic ? (
            <>
              <Button title="Edit subjects" onClick={actions.editSubjects} className="btn btn-default">
                <span>Edit Subjects</span>
                <i className="fal fa-sitemap" />
              </Button>
              <Button title="Edit tags" onClick={actions.editTags} className="btn btn-default">
                <span>Edit Tags</span>
                <i className="fal fa-tags" />
              </Button>
              <hr />
            </>
          ) : null}
        </>
      ) : null}
      <Button className="btn btn-default" onClick={reloadBooks} disabled={booksLoading}>
        <span>Reload Books</span>
        <i className="fal fa-sync"></i>
      </Button>
      <hr />
      <Button onClick={() => uiDispatch({ type: "SET_GRID_VIEW" })} className={"btn btn-default " + (uiView.isGridView ? "active" : "")}>
        <span>Grid View</span>
        <i className="fal fa-table" />
      </Button>
      <Button onClick={() => uiDispatch({ type: "SET_COVERS_LIST_VIEW" })} className={"btn btn-default " + (uiView.isCoversList ? "active" : "")}>
        <span>Covers View</span>
        <i className="fas fa-th" />
      </Button>
      <Button onClick={() => uiDispatch({ type: "SET_BASIC_LIST_VIEW" })} className={"btn btn-default " + (uiView.isBasicList ? "active" : "")}>
        <span>Mobile View</span>
        <i className="fal fa-list" />
      </Button>
      <hr />
    </>
  ) : !isPublic ? (
    <>
      <hr />
      <Button title="Add/remove subjects" onClick={editSubjectsForSelectedBooks} className={"btn btn-default hidden-tiny"}>
        <span>Add / Remove Subjects</span>
        <i className="fal fa-sitemap" />
      </Button>
      <Button title="Add/remove tags" onClick={editTagsForSelectedBooks} className="btn btn-default hidden-tiny">
        <span>Add / Remove Tags</span>
        <i className="fal fa-tags" />
      </Button>
      <Button title="Set read" onClick={() => setRead(selectedBooksIds, true)} className={"btn btn-default hidden-tiny"}>
        <span>Set Read</span>
        <i className="fal fa-eye" />
      </Button>
      <Button title="Set un-read" onClick={() => setRead(selectedBooksIds, false)} className="btn btn-default put-line-through hidden-tiny">
        <span>Set Un-Read</span>
        <i className="fal fa-eye-slash" />
      </Button>
      <hr />
    </>
  ) : null;
};

export default MenuOptions;

// svelte/modules/books/menuBar/MenuOptions.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { appState } from "app/state/appState";
  import { BookResultsPacket } from "../booksState";
  import { getBookSearchUiView, BASIC_LIST_VIEW, COVERS_LIST, GRID_VIEW } from "../booksUiState";

  export let uiView: ReturnType<typeof getBookSearchUiView>;

  export let bookResultsPacket: BookResultsPacket;
  $: ({ books = [], reload, booksLoading } = bookResultsPacket);

  const uiDispatch = view => $uiView.requestState({ type: "SET_PENDING_VIEW", value: view }, books);

  $: ({ isPublic, online } = $appState);

  const booksModuleContext: any = getContext("books-module-context");
  const { booksUiState, openFilterModal, editSubjects, editTags, setRead, editBooksSubjects, editBooksTags } = booksModuleContext;

  $: ({ selectedBooks } = $booksUiState);
  $: selectedBooksIds = Object.keys(selectedBooks).filter(k => selectedBooks[k]);
  $: selectedBooksCount = selectedBooksIds.length;

  const editSubjectsForSelectedBooks = () => editBooksSubjects(books.filter(b => selectedBooks[b._id]));
  const editTagsForSelectedBooks = () => editBooksTags(books.filter(b => selectedBooks[b._id]));
</script>

{#if !selectedBooksCount}
  <hr />
  {#if online}
    <button title="Filter search" on:click={openFilterModal} class="btn btn-default hidden-tiny">
      <span>Set Filters</span>
      <i class="fal fa-filter" />
    </button>
    <hr />
    {#if !isPublic}
      <button title="Edit subjects" on:click={editSubjects} class="btn btn-default hidden-xs">
        <span>Edit Subjects</span>
        <i class="fal fa-sitemap" />
      </button>
      <button title="Edit tags" on:click={editTags} class="btn btn-default hidden-xs">
        <span>Edit Tags</span>
        <i class="fal fa-tags" />
      </button>
      <hr />
    {/if}
  {/if}
  <button class="btn btn-default hidden-tiny" on:click={reload} disabled={booksLoading}>
    <span>Reload Books</span>
    <i class="fal fa-sync" />
  </button>
  <hr />
  <button on:click={() => uiDispatch(GRID_VIEW)} class={"btn btn-default hidden-tiny " + ($uiView.pendingView == GRID_VIEW ? "active" : "")}>
    <span>Grid View</span>
    <i class="fal fa-table" />
  </button>
  <button on:click={() => uiDispatch(COVERS_LIST)} class={"btn btn-default hidden-tiny " + ($uiView.pendingView == COVERS_LIST ? "active" : "")}>
    <span>Covers View</span>
    <i class="fas fa-th" />
  </button>
  <button
    on:click={() => uiDispatch(BASIC_LIST_VIEW)}
    class={"btn btn-default hidden-tiny " + ($uiView.pendingView == BASIC_LIST_VIEW ? "active" : "")}
  >
    <span>Mobile View</span>
    <i class="fal fa-list" />
  </button>
  <hr />
{:else if !isPublic}
  <hr />
  <button title="Add/remove subjects" on:click={editSubjectsForSelectedBooks} class={"btn btn-default hidden-tiny"}>
    <span>Add / Remove Subjects</span>
    <i class="fal fa-sitemap" />
  </button>
  <button title="Add/remove tags" on:click={editTagsForSelectedBooks} class="btn btn-default hidden-tiny">
    <span>Add / Remove Tags</span>
    <i class="fal fa-tags" />
  </button>
  <button title="Set read" on:click={() => setRead(selectedBooksIds, true)} class={"btn btn-default hidden-tiny"}>
    <span>Set Read</span>
    <i class="fal fa-eye" />
  </button>
  <button title="Set un-read" on:click={() => setRead(selectedBooksIds, false)} class="btn btn-default put-line-through hidden-tiny">
    <span>Set Un-Read</span>
    <i class="fal fa-eye-slash" />
  </button>
  <hr />
{/if}
