// react/app/components/subjectsAndTags/tags/SelectAvailableTags.tsx
import React, { FunctionComponent, useContext, useState } from "react";
import { filterTags, useTagsState } from "app/state/tagsState";
import GenericLabelSelect from "../genericLabelSelect";

type LocalProps = { currentlySelected: string[]; onSelect: any; placeholder?: string };

const SelectAvailableTags: FunctionComponent<LocalProps> = props => {
  const { tags } = useTagsState();
  const [search, setSearchValue] = useState("");

  const setSearch = evt => setSearchValue(evt.target.value);

  const onSelect = item => {
    props.onSelect(item);
    setSearchValue("");
  };

  let { placeholder = "Tags", currentlySelected } = props;
  let itemHash = currentlySelected.reduce((hash, _idOrObj) => ((hash[_idOrObj] = true), hash), {});
  let eligible = filterTags(
    tags.filter(s => !itemHash[s._id]),
    search
  );

  return (
    <GenericLabelSelect
      inputProps={{ tabIndex: -1, placeholder, value: search, onChange: setSearch }}
      suggestions={eligible}
      onSuggestionSelected={onSelect}
    />
  );
};

export default SelectAvailableTags;

// svelte/app/components/subjectsAndTags/tags/SelectAvailableTags.svelte
<script lang="ts">
  import { filterTags, tagsState } from "app/state/tagsState";
  import GenericLabelSelect from "../GenericLabelSelect.svelte";

  export let onSelect;
  export let placeholder = "Tags";
  export let currentlySelected = [];

  $: ({ tags } = $tagsState);
  let search = "";

  const doSelect = item => {
    onSelect(item);
    search = "";
  };

  $: itemHash = currentlySelected.reduce((hash, _idOrObj) => ((hash[_idOrObj] = true), hash), {});
  $: eligible = filterTags(
    tags.filter(s => !itemHash[s._id]),
    search
  );
</script>

<GenericLabelSelect {placeholder} bind:search inputProps={{ tabIndex: -1 }} options={eligible} onItemSelected={doSelect} />
