// react/modules/books/components/bookSubjectSetter.tsx
import React, { SFC, useState, useLayoutEffect, useContext, useRef, FunctionComponent } from "react";
import { useMutation } from "micro-graphql-react";

import updateBookSubjects from "graphQL/books/updateBookSubjects.graphql";

import { Button, ActionButton } from "app/components/ui/Button";

import Modal from "app/components/ui/Modal";
import { useStackedSubjects } from "app/state/subjectsState";
import { MutationOf, Mutations } from "graphql-typings";
import FlexRow from "app/components/layout/FlexRow";
import Stack from "app/components/layout/Stack";
import FlowItems from "app/components/layout/FlowItems";
import { Tabs, TabHeaders, TabHeader, TabContents, TabContent } from "app/components/layout/Tabs";
import DisplaySelectedSubjects from "app/components/subjectsAndTags/subjects/DisplaySelectedSubjects";
import SelectAvailableSubjects from "app/components/subjectsAndTags/subjects/SelectAvailableSubjects";

interface ILocalProps {
  modifyingBooks: any[];
  onDone: any;
}

const BookSubjectSetter: FunctionComponent<ILocalProps> = props => {
  const [addingSubjects, setAddingSubjects] = useState([]);
  const [removingSubjects, setRemovingSubjects] = useState([]);
  const resetSubjects = () => {
    setRemovingSubjects([]);
    setAddingSubjects([]);
  };

  useLayoutEffect(() => {
    if (props.modifyingBooks.length) {
      resetSubjects();
    }
  }, [props.modifyingBooks.length]);

  const { runMutation, running } = useMutation<MutationOf<Mutations["updateBooks"]>>(updateBookSubjects);

  const save = () => {
    let args = { books: props.modifyingBooks.map(b => b._id), add: addingSubjects, remove: removingSubjects };
    return Promise.resolve(runMutation(args)).then(() => {
      props.onDone();
    });
  };
  const addingSubjectSet = (adding, { _id }) => setAddingSubjects(adding ? addingSubjects.concat(_id) : addingSubjects.filter(x => x != _id));
  const subjectSelectedToAdd = addingSubjectSet.bind(null, true);

  const removingSubjectSet = (adding, { _id }) => setRemovingSubjects(adding ? removingSubjects.concat(_id) : removingSubjects.filter(x => x != _id));
  const subjectSelectedToRemove = removingSubjectSet.bind(null, true);

  const dontAddSubject = addingSubjectSet.bind(null, false);
  const dontRemoveSubject = removingSubjectSet.bind(null, false);
  const modifyingBooks = props.modifyingBooks || [];
  const selectRef = useRef(null);

  return (
    <Modal
      className="fade"
      isOpen={!!modifyingBooks.length}
      onHide={() => {
        props.onDone();
      }}
      headerCaption="Add / Remove Subjects:"
      focusRef={selectRef}
    >
      <Tabs defaultTab="subjects">
        <TabHeaders>
          <TabHeader tabName="subjects">
            <a ref={selectRef}>Choose subjects</a>
          </TabHeader>
          <TabHeader tabName="books">
            <a>For books</a>
          </TabHeader>
        </TabHeaders>
        <TabContents>
          <TabContent tabName="subjects">
            <FlexRow>
              <div className="col-xs-3">
                <SelectAvailableSubjects placeholder="Adding" currentlySelected={addingSubjects} onSelect={subjectSelectedToAdd} />
              </div>
              <div className="col-xs-9" style={{ display: "flex", flexWrap: "wrap" }}>
                <DisplaySelectedSubjects currentlySelected={addingSubjects} onRemove={dontAddSubject} />
              </div>

              <div className="col-xs-3">
                <SelectAvailableSubjects placeholder="Removing" currentlySelected={removingSubjects} onSelect={subjectSelectedToRemove} />
              </div>
              <div className="col-xs-9" style={{ display: "flex", flexWrap: "wrap" }}>
                <DisplaySelectedSubjects currentlySelected={removingSubjects} onRemove={dontRemoveSubject} />
              </div>

              <div className="col-xs-12">
                <Button onClick={resetSubjects} preset="default-xs">
                  Reset subjects
                </Button>
              </div>
            </FlexRow>
          </TabContent>
          <TabContent tabName="books">
            <Stack style={{ fontSize: "14px" }}>
              {modifyingBooks.map(book => (
                <div key={book._id}>{book.title}</div>
              ))}
            </Stack>
          </TabContent>
        </TabContents>
      </Tabs>
      <hr />
      <div className="standard-modal-footer">
        <FlowItems>
          <ActionButton style={{ minWidth: "10ch" }} preset="primary" text="Save" runningText="Saving" finishedText="Saved" onClick={save} />

          <Button style={{ minWidth: "10ch" }} preset="" onClick={props.onDone}>
            Cancel
          </Button>
        </FlowItems>
      </div>
    </Modal>
  );
};

export default BookSubjectSetter;

// svelte-kit/src/routes/(core-data)/books/BookSubjectSetter.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import type { Book, Subject } from "$data/types";
  import DisplaySelectedSubjects from "$lib/components/subjectsAndTags/subjects/DisplaySelectedSubjects.svelte";
  import SelectAvailableSubjects from "$lib/components/subjectsAndTags/subjects/SelectAvailableSubjects.svelte";

  import Modal from "$lib/components/ui/Modal.svelte";
  import StandardModalFooter from "$lib/components/ui/StandardModalFooter.svelte";
  import Button from "$lib/components/buttons/Button.svelte";
  import ActionButton from "$lib/components/buttons/ActionButton.svelte";

  import { Tabs, TabHeaders, TabHeader, TabContents, TabContent } from "$lib/components/layout/tabs/index";

  import FlexRow from "$lib/components/layout/FlexRow.svelte";
  import Stack from "$lib/components/layout/Stack.svelte";
  import FlowItems from "$lib/components/layout/FlowItems.svelte";
  import { enhance } from "$app/forms";
  import type { UpdatesTo } from "$lib/state/dataUpdates";

  $: subjects = $page.data.subjects;
  export let modifyingBooks: any[];
  export let isOpen: boolean;
  export let onSave: (_id: string | string[], updates: UpdatesTo<Book>) => void;
  export let onHide: () => void;

  let addingSubjects: string[] = [];
  let removingSubjects: string[] = [];

  const resetSubjects = () => {
    addingSubjects = [];
    removingSubjects = [];
  };

  $: {
    if (isOpen) {
      resetSubjects();
    }
  }

  let saving = false;
  const save = () => {
    saving = true;
    const updates = {
      arraySync: {
        subjects: {
          push: addingSubjects,
          pull: removingSubjects
        }
      }
    };
    return async ({}) => {
      onSave(
        modifyingBooks.map(b => b._id),
        updates
      );
      saving = false;
      onHide();
    };
  };
  const addingSubjectSet = (adding: boolean, { _id }: Subject) =>
    (addingSubjects = adding ? addingSubjects.concat(_id) : addingSubjects.filter(x => x != _id));
  const subjectSelectedToAdd = addingSubjectSet.bind(null, true);

  const removingSubjectSet = (adding: boolean, { _id }: Subject) =>
    (removingSubjects = adding ? removingSubjects.concat(_id) : removingSubjects.filter(x => x != _id));
  const subjectSelectedToRemove = removingSubjectSet.bind(null, true);

  const dontAddSubject = addingSubjectSet.bind(null, false);
  const dontRemoveSubject = removingSubjectSet.bind(null, false);

  let closeModal: () => void;
</script>

<Modal {isOpen} {onHide} headerCaption="Add / Remove Subjects" standardFooter={false}>
  <form method="post" action="?/setBooksSubjects" use:enhance={save}>
    <Tabs defaultTab="subjects">
      <TabHeaders>
        <TabHeader tabName="subjects">Choose subjects</TabHeader>
        <TabHeader tabName="books">For books</TabHeader>
      </TabHeaders>
      <TabContents>
        <TabContent tabName="subjects">
          {#each modifyingBooks as b}
            <input type="hidden" name="_ids" value={b._id} />
          {/each}
          {#each addingSubjects as s}
            <input type="hidden" name="add" value={s} />
          {/each}
          {#each removingSubjects as s}
            <input type="hidden" name="remove" value={s} />
          {/each}
          <FlexRow>
            <div class="col-xs-3">
              <SelectAvailableSubjects {subjects} placeholder="Adding" currentlySelected={addingSubjects} onSelect={subjectSelectedToAdd} />
            </div>
            <div class="col-xs-9" style="display: flex; flex-wrap: wrap">
              <DisplaySelectedSubjects {subjects} currentlySelected={addingSubjects} onRemove={dontAddSubject} />
            </div>

            <div class="col-xs-3">
              <SelectAvailableSubjects {subjects} placeholder="Removing" currentlySelected={removingSubjects} onSelect={subjectSelectedToRemove} />
            </div>
            <div class="col-xs-9" style="display: flex; flex-wrap: wrap">
              <DisplaySelectedSubjects {subjects} currentlySelected={removingSubjects} onRemove={dontRemoveSubject} />
            </div>

            <div class="col-xs-12">
              <Button type="button" onClick={resetSubjects} preset="default-xs">Reset subjects</Button>
            </div>
          </FlexRow>
        </TabContent>
        <TabContent tabName="books">
          <Stack style="font-size: 14px">
            {#each modifyingBooks as book (book._id)}
              <div>{book.title}</div>
            {/each}
          </Stack>
        </TabContent>
      </TabContents>
    </Tabs>
    <StandardModalFooter bind:closeModal>
      <FlowItems pushLast={true}>
        <ActionButton isRunning={saving} style="min-width: 10ch" preset="primary" text="Save" runningText="Saving" finishedText="Saved" />

        <Button type="button" style="min-width: 10ch" preset="" onClick={closeModal}>Cancel</Button>
      </FlowItems>
    </StandardModalFooter>
  </form>
</Modal>
