// svelte-kit/src/lib/components/subjectsAndTags/subjects/SelectAvailableSubjects.svelte
<script lang="ts">
  import type { Subject } from "$data/types";
  import type { Label } from "../types";
  import { filterSubjects, subjectState } from "$lib/state/subjectsState";

  import GenericLabelSelect from "../GenericLabelSelect.svelte";

  export let onSelect: (item: Label) => void;
  export let placeholder = "Subjects";
  export let currentlySelected: string[] = [];

  export let subjects: Subject[];

  let search = "";

  const doSelect = (item: Label) => {
    onSelect(item);
    search = "";
  };

  type LookupHash = { [_id: string]: true };
  $: itemHash = currentlySelected.reduce<LookupHash>((hash, _idOrObj) => ((hash[_idOrObj] = true), hash), {});

  $: subjectsPacket = subjectState(subjects);

  $: eligible = filterSubjects(subjectsPacket.subjectsUnwound, search, subjectsPacket.subjectHash, itemHash);
</script>

<GenericLabelSelect {placeholder} noFiltering={true} bind:search options={eligible} onItemSelected={doSelect} />

// react/app/components/subjectsAndTags/subjects/SelectAvailableSubjects.tsx
import React, { FunctionComponent, useState } from "react";
import { useStackedSubjects, filterSubjects, useSubjectsState } from "app/state/subjectsState";
import GenericLabelSelect from "../genericLabelSelect";

type LocalProps = { currentlySelected: string[]; onSelect: any; placeholder?: string };

const SelectAvailableSubjects: FunctionComponent<LocalProps> = props => {
  const { subjectsUnwound } = useStackedSubjects();
  const { subjectHash } = useSubjectsState();

  const [search, setSearchValue] = useState("");
  const setSearch = evt => setSearchValue(evt.target.value);

  const onSelect = item => {
    props.onSelect(item);
    setSearchValue("");
  };

  let itemHash = props.currentlySelected.reduce((hash, _idOrObj) => ((hash[_idOrObj] = true), hash), {});

  const eligible = filterSubjects(subjectsUnwound, search, subjectHash, itemHash);

  return (
    <GenericLabelSelect
      inputProps={{ placeholder: props.placeholder || "Subjects", value: search, onChange: setSearch }}
      suggestions={eligible}
      onSuggestionSelected={onSelect}
    />
  );
};

export default SelectAvailableSubjects;
