// svelte-kit/src/lib/components/CustomColorPicker.svelte
<script context="module">
  let uniqueIdCounter = 0;
</script>

<script lang="ts">
  import "./ui/jscolor";
  import { onMount } from "svelte";

  export let onColorChosen: (color: string) => void;
  export let currentColor: string | null;
  export let labelStyle: string;

  let uniqueId = `customColorPickerId${++uniqueIdCounter}`;
  let _colorChosen: any;

  let jscolorInstance: any;
  let rootElement: HTMLElement;
  let valueElementId = `${uniqueId}_value`;
  let styleElementId = `${uniqueId}_style`;

  $: {
    if (jscolorInstance && currentColor) {
      jscolorInstance.fromString(currentColor);
    }
  }

  onMount(() => {
    _colorChosen = function (this: any) {
      let hexColor = this.rgb
        .map((n: any) => (~~n).toString(16))
        .map((n: any) => (n.length == 1 ? `0${n}` : n))
        .join("");
      onColorChosen("#" + hexColor);
    };

    jscolorInstance = new (window as any).jscolor(rootElement, {
      valueElement: valueElementId,
      styleElement: styleElementId,
      onFineChange: _colorChosen
    });
  });
</script>

<div>
  <a id={uniqueId} bind:this={rootElement} style="height: 20px; {labelStyle}"> Custom </a>
  <input style="display: none;" id={valueElementId} value={currentColor} />
  <input style="display: none" id={styleElementId} />
</div>

// react-redux/applicationRoot/components/customColorPicker.tsx
import React, { Component } from "react";
import "jscolor";

declare var jscolor: any;

let uniqueIdCounter = 0;

class CustomColorPicker extends Component<any, any> {
  uniqueId = `customColorPickerId${++uniqueIdCounter}`;
  _colorChosen: () => any;
  jscolorInstance: any;
  rootElement: any;
  valueElement: any;
  get valueElementId() {
    return `${this.uniqueId}_value`;
  }
  get styleElementId() {
    return `${this.uniqueId}_style`;
  }
  componentDidMount() {
    let onColorChosen = this.props.onColorChosen;

    this._colorChosen = function() {
      let hexColor = this.rgb
        .map(n => (~~n).toString(16))
        .map(n => (n.length == 1 ? `0${n}` : n))
        .join("");
      onColorChosen("#" + hexColor);
    };
    this.jscolorInstance = new jscolor(this.rootElement, {
      valueElement: this.valueElementId,
      styleElement: this.styleElementId,
      onFineChange: this._colorChosen
    });
  }
  shouldComponentUpdate(props) {
    if (props.currentColor) {
      this.jscolorInstance.fromString(props.currentColor);
    }
    return false;
  }
  render() {
    return (
      <div>
        <a id={`${this.uniqueId}`} ref={el => (this.rootElement = el)} style={{ height: "20px", ...(this.props.labelStyle || {}) }}>
          Custom
        </a>
        <input style={{ display: "none" }} ref={el => (this.valueElement = el)} id={this.valueElementId} defaultValue={this.props.currentColor} />
        <input style={{ display: "none" }} id={this.styleElementId} />
      </div>
    );
  }
}

export default CustomColorPicker;
