// svelte-kit/src/lib/components/ui/Loading.svelte
<script>
  export let style = "";
</script>

<div><i {style} class="far fa-5x fa-spin fa-spinner" /></div>

<style>
  div {
    position: fixed;
    left: 50%;
    top: 30%;
    transform: translateX(-50%) translateY(-50%);
    z-index: 99999;
  }
  i {
    opacity: 0.5;
    color: var(--primary-3);
  }
</style>

// react-redux/applicationRoot/components/loading.tsx
import React from 'react';

export default ({...rest}) => (
    <div {...rest} className="wait-for-loading">
        <i className="fa fa-5x fa-spin fa-spinner"></i>
    </div>
);

export const SectionLoading = ({style = {}, ...rest}) => (
    <i style={{ position: 'absolute', top: '50%', left: '50%', opacity: 0.2, transform: 'translate(-50%,-50%)', ...style }} className="fa fa-5x fa-spin fa-spinner"></i>
)
