// react/app/components/editBook/editBookCovers.tsx
import React, { useState, FunctionComponent } from "react";
import Toggle from "react-toggle";
import { useMutation } from "micro-graphql-react";
import type { MutationOf, Mutations, BookMutationInput } from "graphql-typings";
import type { IBookRaw } from "modules/books/booksState";

import ManageBookCover from "./manageBookCover";

import Stack from "../layout/Stack";
import FlowItems from "../layout/FlowItems";
import { CoverMobile, CoverSmall, CoverMedium } from "../bookCoverComponent";
import UpdateBook from "graphQL/books/updateBook.graphql";

import { Button, ActionButton } from "../ui/Button";

type Props = {
  book: IBookRaw;
  updateBook(updater: (book: IBookRaw) => IBookRaw): void;
};

type IndividualCover = { STATUS: "success" | "invalid-size" | "error"; image?: { url: string; preview: string } };
type UploadResultsType = { success: boolean; status?: string; mobile: IndividualCover; small: IndividualCover; medium: IndividualCover };

export const EditBookCovers: FunctionComponent<Props> = ({ book, updateBook }) => {
  const { runMutation: runBookMutation } = useMutation<MutationOf<Mutations["updateBook"]>>(UpdateBook);

  const [saveEligible, setSaveEligible] = useState(false);
  const [coverProcessingResult, setCoverProcessingResult] = useState<UploadResultsType>(null);
  const [useNewMobile, setUseNewMobile] = useState(false);
  const [useNewSmall, setUseNewSmall] = useState(false);
  const [useNewMedium, setUseNewMedium] = useState(false);

  const isNew = () => !book?._id;

  const runSave = () => {
    let { _id } = book;

    const updateObject: Partial<
      Pick<BookMutationInput, "mobileImage" | "mobileImagePreview" | "smallImage" | "smallImagePreview" | "mediumImage" | "mediumImagePreview">
    > = {};
    if (useNewMobile) {
      updateObject.mobileImage = coverProcessingResult.mobile.image.url;
      updateObject.mobileImagePreview = coverProcessingResult.mobile.image.preview;
    }
    if (useNewSmall) {
      updateObject.smallImage = coverProcessingResult.small.image.url;
      updateObject.smallImagePreview = coverProcessingResult.small.image.preview;
    }
    if (useNewMedium) {
      updateObject.mediumImage = coverProcessingResult.medium.image.url;
      updateObject.mediumImagePreview = coverProcessingResult.medium.image.preview;
    }

    if (_id) {
      return runBookMutation({ _id, book: updateObject });
    } else {
      updateBook(b => ({ ...b, ...updateObject }));
    }
  };

  const [coverProcessingError, setCoverProcessingError] = useState(false);
  const onCoverError = () => {
    setCoverProcessingError(true);
    setCoverProcessingResult(null);
    setSaveEligible(false);
  };
  const clearCoverError = () => setCoverProcessingError(false);

  const onCoverResults = (obj: UploadResultsType) => {
    clearCoverError();
    setCoverProcessingResult(obj);
    if (obj.success) {
      setSaveEligible(true);
      setUseNewMobile(obj.mobile.STATUS === "success");
      setUseNewSmall(obj.small.STATUS === "success");
      setUseNewMedium(obj.medium.STATUS === "success");
    } else {
      setSaveEligible(false);
      setUseNewMobile(false);
      setUseNewSmall(false);
      setUseNewMedium(false);
    }
  };

  return (
    <div>
      <CurrentCovers book={book} />
      <hr />

      <ManageBookCover onError={onCoverError} onResults={onCoverResults} />
      {coverProcessingError ? <div className="alert alert-danger">Error processing this cover</div> : null}
      {coverProcessingResult ? (
        <UploadResults {...{ ...coverProcessingResult, useNewMobile, setUseNewMobile, useNewSmall, setUseNewSmall, useNewMedium, setUseNewMedium }} />
      ) : null}
      {saveEligible && isNew() ? (
        <Button className="margin-top" preset="primary" onClick={runSave}>
          Set image info
        </Button>
      ) : null}
      {saveEligible && !isNew() ? (
        <ActionButton className="margin-top" preset="primary" onClick={runSave} finishedText="Saved" text="Save" runningText="Saving" />
      ) : null}
    </div>
  );
};

type UploadResultAdditionalTypes = { size: "mobile" | "small" | "medium"; useNewImage: boolean; setUseNewImage: (val: boolean) => void };

const UploadResult: FunctionComponent<IndividualCover & UploadResultAdditionalTypes> = props => {
  const success = props.STATUS === "success";
  const { image, useNewImage, setUseNewImage, size } = props;
  const ImgComponent = size === "mobile" ? CoverMobile : size === "small" ? CoverSmall : CoverMedium;

  return (
    <div style={{ flex: 1 }}>
      {success ? (
        <Stack inline={true} style={{ alignItems: "center", height: "100%" }}>
          <div className="margin-bottom">
            <ImgComponent url={image.url} preview={image.preview} />
          </div>
          <div style={{ marginTop: "auto" }}>
            <Toggle checked={useNewImage} onChange={e => setUseNewImage(e.target.checked)} icons={{ unchecked: null }} />
          </div>
        </Stack>
      ) : null}
    </div>
  );
};

type UseCoversState = {
  useNewMobile: boolean;
  useNewSmall: boolean;
  useNewMedium: boolean;

  setUseNewMobile: (val: boolean) => void;
  setUseNewSmall: (val: boolean) => void;
  setUseNewMedium: (val: boolean) => void;
};
const UploadResults: FunctionComponent<UploadResultsType & UseCoversState> = props => {
  const { success, status, mobile, small, medium, useNewMobile, setUseNewMobile, useNewSmall, setUseNewSmall, useNewMedium, setUseNewMedium } = props;

  if (!success) {
    if (status === "invalid-size") {
      return <div className="alert alert-warning margin-top">This image is too small to use</div>;
    } else {
      return <div className="alert alert-danger margin-top">An error occured</div>;
    }
  }

  return (
    <FlowItems>
      <UploadResult {...mobile} useNewImage={useNewMobile} setUseNewImage={setUseNewMobile} size="mobile" />
      <UploadResult {...small} useNewImage={useNewSmall} setUseNewImage={setUseNewSmall} size="small" />
      <UploadResult {...medium} useNewImage={useNewMedium} setUseNewImage={setUseNewMedium} size="medium" />
    </FlowItems>
  );
};

const CurrentCovers: FunctionComponent<{ book: IBookRaw }> = ({ book }) => {
  return (
    <FlowItems>
      <Stack style={{ flex: 1 }} tightest={true}>
        <div>
          <label className="form-label">Mobile</label>
          <CoverMobile url={book.mobileImage} preview={book.mobileImagePreview} />
        </div>
      </Stack>
      <Stack style={{ flex: 1 }} tightest={true}>
        <div>
          <label className="form-label">Standard</label>
          <CoverSmall url={book.smallImage} preview={book.smallImagePreview} />
        </div>
      </Stack>
      <Stack style={{ flex: 1 }} tightest={true}>
        <div>
          <label className="form-label">Full</label>
          <CoverMedium url={book.mediumImage} preview={book.mediumImagePreview} />
        </div>
      </Stack>
    </FlowItems>
  );
};

// svelte-kit/src/lib/components/editBook/EditBookCovers.svelte
<script lang="ts">
  import { enhance } from "$app/forms";

  import type { Book } from "$data/types";

  import ManageBookCover from "./ManageBookCover.svelte";
  import UploadResults from "./UploadResults.svelte";

  import Button from "../buttons/Button.svelte";
  import ActionButton from "../buttons/ActionButton.svelte";
  import CurrentCovers from "./CurrentCovers.svelte";
  import type { UpdatesTo } from "$lib/state/dataUpdates";

  export let book: Book;
  export let onSave: (_id: string, updates: UpdatesTo<Book>) => void;

  type IndividualCover = { STATUS: "success" | "invalid-size" | "error"; image?: { url: string; preview: string } };
  type UploadResultsType = {
    success: boolean;
    status?: "success" | "invalid-size" | "error";
    mobile?: IndividualCover;
    small?: IndividualCover;
    medium?: IndividualCover;
  };

  let coverProcessingResult: UploadResultsType | null = null;

  let useNewMobile = false;
  let useNewSmall = false;
  let useNewMedium = false;

  const setUseNewMobile = (val: any) => (useNewMobile = val);
  const setUseNewSmall = (val: any) => (useNewSmall = val);
  const setUseNewMedium = (val: any) => (useNewMedium = val);

  const onCoverError = () => {
    coverProcessingResult = { success: false, status: "error" };
  };

  const onCoverResults = (obj: UploadResultsType) => {
    coverProcessingResult = obj;
    if (obj.success) {
      useNewMobile = obj.mobile?.STATUS === "success";
      useNewSmall = obj.small?.STATUS === "success";
      useNewMedium = obj.medium?.STATUS === "success";
    } else {
      useNewMobile = false;
      useNewSmall = false;
      useNewMedium = false;
    }
  };

  $: mobileImage = useNewMobile && coverProcessingResult ? coverProcessingResult.mobile?.image?.url : null;
  $: mobileImagePreview = useNewMobile && coverProcessingResult ? coverProcessingResult.mobile?.image?.preview : null;

  $: smallImage = useNewSmall && coverProcessingResult ? coverProcessingResult.small?.image?.url : null;
  $: smallImagePreview = useNewSmall && coverProcessingResult ? coverProcessingResult?.small?.image?.preview : null;

  $: mediumImage = useNewMedium && coverProcessingResult ? coverProcessingResult.medium?.image?.url : null;
  $: mediumImagePreview = useNewMedium && coverProcessingResult ? coverProcessingResult.medium?.image?.preview : null;

  function updateLocalBook() {}

  let saving = false;
  function executeSave() {
    const { _id } = book;

    saving = true;

    return async ({ result }: any) => {
      onSave(_id, result.data.updates);
      saving = false;
      coverProcessingResult = null;
    };
  }

  $: ({ success, status, mobile, small, medium } = coverProcessingResult || ({} as any));

  $: saveEligible = coverProcessingResult?.success && (useNewMobile || useNewSmall || useNewMedium);

  $: isNew = !book?._id;
</script>

<div>
  <CurrentCovers {book} />
  <hr />

  <ManageBookCover onError={onCoverError} onResults={onCoverResults} />

  {#if coverProcessingResult}
    <UploadResults
      {success}
      {status}
      {mobile}
      {small}
      {medium}
      {useNewMobile}
      {setUseNewMobile}
      {useNewSmall}
      {setUseNewSmall}
      {useNewMedium}
      {setUseNewMedium}
    />
  {/if}

  {#if saveEligible && isNew}
    <Button class="margin-top" preset="primary" onClick={updateLocalBook}>Set image info</Button>
  {/if}

  {#if saveEligible && !isNew}
    <form action="/books?/saveBookCovers" method="post" use:enhance={executeSave}>
      <input type="hidden" name="_id" value={book._id} />
      <input type="hidden" name="mobileImage" value={mobileImage} />
      <input type="hidden" name="mobileImagePreview" value={mobileImagePreview} />
      <input type="hidden" name="smallImage" value={smallImage} />
      <input type="hidden" name="smallImagePreview" value={smallImagePreview} />
      <input type="hidden" name="mediumImage" value={mediumImage} />
      <input type="hidden" name="mediumImagePreview" value={mediumImagePreview} />

      <ActionButton class="margin-top" preset="primary" isRunning={saving} finishedText="Saved" text="Save" runningText="Saving" />
    </form>
  {/if}
</div>
