// svelte-kit/src/lib/components/editBook/EditBook.svelte
<script lang="ts">
  import type { Subject, Tag } from "$data/types";
  import { Tabs, TabHeaders, TabHeader, TabContents, TabContent } from "../layout/tabs/index";
  import EditBookCovers from "./EditBookCovers.svelte";

  import EditBookInfo from "./EditBookInfo.svelte";
  //import ManageBookCover from "./ManageBookCover.svelte";

  export let book: any;
  export let cancel: any;
  export let subjects: Subject[];
  export let tags: Tag[];

  export let onBookUpdated: (_id: string, updates: any) => void;
  const updateBook = (fn: any) => (book = fn(book));

  function testCover() {
    fetch("/api/cover-upload", { method: "POST" });
  }
</script>

<Tabs defaultTab="basic">
  <TabHeaders>
    <TabHeader tabName="basic" text="Book info" />
    <TabHeader tabName="covers" text="Covers" />
  </TabHeaders>
  <TabContents>
    <TabContent tabName="basic">
      <!-- <button on:click={testCover}>TEST</button> -->
      {#if book}
        <EditBookInfo {book} {cancel} {subjects} {tags} {onBookUpdated} />
      {/if}
    </TabContent>
    <TabContent tabName="covers">
      {#if book}
        <EditBookCovers {book} {updateBook} />
      {/if}
    </TabContent>
    <TabContent tabName="c">C Content</TabContent>
  </TabContents>
</Tabs>

// react/app/components/editBook/editBook.tsx
import React, { useState, FunctionComponent, useLayoutEffect } from "react";

import ManageBookCover from "./manageBookCover";
import EditBookInfo from "./editBookInfo";

import { Tabs, TabHeaders, TabHeader, TabContents, TabContent } from "../layout/Tabs";

type Props = {
  saveBook: any;
  title: string;
  book: any;
  onCancel: any;
};

const EditBook: FunctionComponent<Props> = ({ book: bookToEdit, onCancel, saveBook, title }) => {
  const [state, setState] = useState({ tab: "basic", bookEditing: null, title: "" });

  const updateBook = updateFn => {
    setState(state => ({ ...state, bookEditing: updateFn(state.bookEditing) }));
  }

  const editBook = (book) =>  {
    setState({
      tab: "basic",
      title,
      bookEditing: { ...book }
    });
  }

  useLayoutEffect(() => {
    editBook(bookToEdit);
  }, [bookToEdit]);

  let { bookEditing } = state;
  let book = bookEditing;

  return (
    <Tabs defaultTab="basic">
      <TabHeaders>
        <TabHeader tabName="basic">
          <a>Book info</a>
        </TabHeader>
        <TabHeader tabName="covers">
          <a>Covers</a>
        </TabHeader>
      </TabHeaders>
      <TabContents>
        <TabContent tabName="basic">{book ? <EditBookInfo {...{ book, onCancel, saveBook }} updateBook={updateBook} /> : null}</TabContent>
        <TabContent tabName="covers">
          {book ? (
            <>
              <div className="form-group">
                <label>Small Cover</label>
                <ManageBookCover _id={book._id} imgKey="smallImage" size="small" img={book.smallImage} updateBook={updateBook} />
              </div>
              <hr />
              <div className="form-group">
                <label>Medium Cover</label>
                <ManageBookCover _id={book._id} imgKey="mediumImage" size="medium" img={book.mediumImage} updateBook={updateBook} />
              </div>
            </>
          ) : null}
        </TabContent>
      </TabContents>
    </Tabs>
  );
};

export default EditBook;
