// svelte-kit/src/lib/components/editBook/EditBookInfo.svelte
<script lang="ts">
  import { enhance } from "$app/forms";

  import type { Book, Subject, Tag } from "$data/types";
  import type { UpdatesTo } from "$lib/state/dataUpdates";

  import ActionButton from "../buttons/ActionButton.svelte";
  import Button from "../buttons/Button.svelte";

  import SelectAvailableTags from "$lib/components/subjectsAndTags/tags/SelectAvailableTags.svelte";
  import SelectAvailableSubjects from "$lib/components/subjectsAndTags/subjects/SelectAvailableSubjects.svelte";

  import DisplaySelectedTags from "$lib/components/subjectsAndTags/tags/DisplaySelectedTags.svelte";
  import DisplaySelectedSubjects from "$lib/components/subjectsAndTags/subjects/DisplaySelectedSubjects.svelte";
  import FlexRow from "../layout/FlexRow.svelte";
  import FlowItems from "../layout/FlowItems.svelte";

  export let book: any;
  export let tags: Tag[];
  export let subjects: Subject[];

  export let onSave: (_id: string, updates: UpdatesTo<Book>) => void;

  let editingBook: any;
  $: bookChanged(book);

  function bookChanged(book: any) {
    editingBook = { ...book };
  }

  const addSubject = (subject: Subject) => (editingBook.subjects = editingBook.subjects.concat(subject._id));
  const removeSubject = (subject: any) => (editingBook.subjects = editingBook.subjects.filter((_id: string) => _id != subject._id));

  const addTag = (tag: any) => (editingBook.tags = editingBook.tags.concat(tag._id));
  const removeTag = (tag: any) => (editingBook.tags = editingBook.tags.filter((_id: string) => _id != tag._id));

  let missingTitle = false;

  export let cancel: any;

  const addAuthor = (evt: any) => {
    editingBook.authors = [...editingBook.authors, ""];
  };

  let saving = false;
  function executeSave({ cancel, data }: any) {
    if (!data.get("title")) {
      missingTitle = true;
      return cancel();
    }
    const _id = data.get("_id");
    missingTitle = false;

    saving = true;
    return async ({ result }: any) => {
      saving = false;
      onSave(_id, result.data.updates);
    };
  }

  function titleKeyDown(evt: any) {
    if (evt.target.value) {
      missingTitle = false;
    }
  }
</script>

<form method="post" action="?/saveBook" use:enhance={executeSave}>
  <fieldset disabled={saving}>
    <input type="hidden" name="_id" value={editingBook._id} />
    <FlexRow>
      <div class="col-xs-6">
        <div class={"form-group"}>
          <label for="book-edit-title">Title</label>
          <input
            id="book-edit-title"
            class="form-control"
            name="title"
            class:error={missingTitle}
            bind:value={editingBook.title}
            on:input={titleKeyDown}
            placeholder="Title (required)"
          />
        </div>
      </div>

      <div class="col-xs-6">
        <div class="form-group">
          <label for="book-edit-isbn">ISBN</label>
          <input id="book-edit-isbn" name="isbn" class="form-control" bind:value={editingBook.isbn} placeholder="ISBN" />
        </div>
      </div>

      <div class="col-xs-6">
        <div class="form-group">
          <label for="book-edit-pages">Pages</label>
          <input id="book-edit-pages" name="pages" class="form-control" bind:value={editingBook.pages} type="number" placeholder="Number of pages" />
        </div>
      </div>

      <div class="col-xs-6">
        <div class="form-group">
          <label for="book-edit-publisher">Publisher</label>
          <input id="book-edit-publisher" name="publisher" class="form-control" bind:value={editingBook.publisher} placeholder="Publisher" />
        </div>
      </div>

      <div class="col-xs-6">
        <div class="form-group">
          <label for="book-edit-published">Published</label>
          <input
            id="book-edit-published"
            name="publicationDate"
            class="form-control"
            bind:value={editingBook.publicationDate}
            placeholder="Publication date"
          />
        </div>
      </div>

      <div class="col-xs-12">
        <FlexRow>
          <div class="col-sm-3 col-xs-12">
            <SelectAvailableTags {tags} currentlySelected={editingBook.tags} onSelect={addTag} />
          </div>
          <div class="col-sm-9 col-xs-12">
            <DisplaySelectedTags {tags} currentlySelected={editingBook.tags} onRemove={removeTag} />
          </div>
        </FlexRow>
      </div>

      <div class="col-xs-12">
        <FlexRow>
          <div class="col-sm-3 col-xs-12">
            <SelectAvailableSubjects {subjects} currentlySelected={editingBook.subjects} onSelect={addSubject} />
          </div>
          <div class="col-sm-9 col-xs-12">
            <DisplaySelectedSubjects {subjects} currentlySelected={editingBook.subjects} onRemove={removeSubject} />
          </div>
        </FlexRow>
      </div>

      {#each editingBook.authors || [] as author, index (index)}
        <div class="col-xs-4">
          <div class="form-group">
            <label for={`book-edit-author-${index}`}>Author</label>
            <input
              id={`book-edit-author-${index}`}
              bind:value={editingBook.authors[index]}
              class="form-control"
              name="authors"
              placeholder={`Author ${index + 1}`}
            />
          </div>
        </div>
      {/each}
      <div class="col-xs-12">
        <Button type="button" disabled={saving} onClick={evt => addAuthor(evt)} preset="default-xs"><i class="far fa-fw fa-plus" />Add author</Button>
      </div>
    </FlexRow>
    <hr />

    <FlowItems>
      <ActionButton type="submit" style="min-width: 10ch" isRunning={saving} finishedText="Saved" text="Save" preset="primary" runningText="Saving" />
      <Button disabled={saving} style="margin-left: auto;" type="button" onClick={cancel}>Cancel</Button>
    </FlowItems>
  </fieldset>
</form>

// react/app/components/editBook/editBookInfo.tsx
import React, { useState } from "react";
import { Button } from "app/components/ui/Button";

import SelectAvailableTags from "app/components/subjectsAndTags/tags/SelectAvailableTags";
import SelectAvailableSubjects from "app/components/subjectsAndTags/subjects/SelectAvailableSubjects";

import DisplaySelectedTags from "app/components/subjectsAndTags/tags/DisplaySelectedTags";
import DisplaySelectedSubjects from "app/components/subjectsAndTags/subjects/DisplaySelectedSubjects";
import FlexRow from "../layout/FlexRow";

import { Form, required, Input, SubmitButton } from "../ui/Form";
import FlowItems from "../layout/FlowItems";

const useSubjectsOrTags = startingItems => {
  const [items, setItems] = useState(startingItems || []);
  const addItem = item => setItems(items.concat(item._id));
  const removeItem = item => setItems(items.filter(_id => _id != item._id));

  return [items, addItem, removeItem];
};

const EditBookInfo = props => {
  const { book, saveBook, onCancel, updateBook } = props;

  const [subjects, selectSubject, removeSubject] = useSubjectsOrTags(book.subjects);
  const [tags, selectTag, removeTag] = useSubjectsOrTags(book.tags);

  const save = () => {
    //trim out empty authors now, so they're not applied in the reducer, and show up as empty entries on subsequent edits
    let bookToSave = { ...book, authors: book.authors.filter(a => a), subjects, tags };
    return Promise.resolve(saveBook(bookToSave)).then(savedBook => {
      savedBook && updateBook(book => ({ ...book, _id: savedBook._id }));
    });
  };

  const syncAuthor = index => evt => {
    let newAuthors = book.authors.concat();
    newAuthors[index] = evt.target.value;
    updateBook(book => ({ ...book, authors: newAuthors }));
  };
  const addAuthor = evt => {
    evt.preventDefault();
    updateBook(book => ({ ...book, authors: book.authors.concat("") }));
  };

  const syncField = name => evt => updateBook(book => ({ ...book, [name]: evt.target.value }));

  return (
    <>
      <Form submit={save}>
        <FlexRow>
          <div className="col-xs-6">
            <div className={"form-group"}>
              <label>Title</label>

              <Input name="title" validate={required} onChange={syncField("title")} value={book.title} placeholder="Title (required)" />
            </div>
          </div>

          <div className="col-xs-6">
            <div className="form-group">
              <label>ISBN</label>
              <input onChange={syncField("isbn")} className="form-control" value={book.isbn} placeholder="ISBN" />
            </div>
          </div>

          <div className="col-xs-6">
            <div className="form-group">
              <label>Pages</label>
              <input onChange={syncField("pages")} className="form-control" value={book.pages} type="number" placeholder="Number of pages" />
            </div>
          </div>

          <div className="col-xs-6">
            <div className="form-group">
              <label>Publisher</label>
              <input onChange={syncField("publisher")} className="form-control" value={book.publisher} placeholder="Publisher" />
            </div>
          </div>

          <div className="col-xs-6">
            <div className="form-group">
              <label>Published</label>
              <input onChange={syncField("publicationDate")} className="form-control" value={book.publicationDate} placeholder="Publication date" />
            </div>
          </div>

          <div className="col-xs-12">
            <FlexRow>
              <div className="col-sm-3 col-xs-12">
                <SelectAvailableTags currentlySelected={tags} onSelect={selectTag} />
              </div>
              <div style={{ display: tags.length ? "" : "none" }} className="col-sm-9 col-xs-12">
                <DisplaySelectedTags currentlySelected={tags} onRemove={removeTag} />
              </div>
            </FlexRow>
          </div>

          <div className="col-xs-12">
            <FlexRow>
              <div className="col-sm-3 col-xs-12">
                <SelectAvailableSubjects currentlySelected={subjects} onSelect={selectSubject} />
              </div>
              <div style={{ display: subjects.length ? "" : "none" }} className="col-sm-9 col-xs-12">
                <DisplaySelectedSubjects currentlySelected={subjects} onRemove={removeSubject} />
              </div>
            </FlexRow>
          </div>

          {(book.authors || []).map((author, $index) => (
            <div key={$index} className="col-xs-4">
              <div className="form-group">
                <label>Author</label>
                <input onChange={syncAuthor($index)} value={author} className="form-control" placeholder={`Author ${$index + 1}`} />
              </div>
            </div>
          ))}
          <div className="col-xs-12">
            <Button type="button" onClick={evt => addAuthor(evt)} preset="default-xs">
              <i className="far fa-fw fa-plus" /> Add author
            </Button>
          </div>
        </FlexRow>
        <hr />

        <FlowItems>
          <SubmitButton style={{ minWidth: "10ch" }} finishedText="Saved" text="Save" className="pull-right" preset="primary" runningText="Saving" />

          <Button style={{ marginLeft: "auto" }} onClick={onCancel}>
            Cancel
          </Button>
        </FlowItems>
      </Form>
    </>
  );
};

export default EditBookInfo;
