// svelte-kit/src/lib/components/editBook/ManageBookCover.svelte
<script lang="ts">
  import { ajaxUtil } from "$lib/util/ajaxUtil";

  import Dropzone from "svelte-file-dropzone";

  import FlowItems from "../layout/FlowItems.svelte";

  export let onResults: (results: any) => void;
  export let onError: () => void;

  let uploadState = { uploadError: "" };

  let uploading = false;

  let dragging = false;
  $: dropAddedStyles = uploading ? "border-color: var(--neutral-6); cursor: wait;" : dragging ? "border-color: var(--primary-8);" : "";

  $: ({ uploadError } = uploadState);

  let remoteUrl = "";

  const doRemoteSave = () => {
    uploading = true;

    ajaxUtil.post(
      "/api/cover-set-url",
      { url: remoteUrl },
      resp => {
        if (!resp.error) {
          onResults(resp);
        }
        uploading = false;
      },
      () => {
        onError();
        uploading = false;
      }
    );
  };

  const onDrop = (evt: any) => {
    const { acceptedFiles } = evt.detail;
    if (!acceptedFiles.length) {
      //TODO: ??
      return;
    }
    let requestData = new FormData();
    const file = acceptedFiles[0];
    requestData.append("fileUploaded", file);
    requestData.append("filename", file.path);

    uploading = true;

    ajaxUtil.post(
      "/api/cover-upload",
      requestData,
      resp => {
        if (resp == null || !resp.error) {
          onResults(resp);
        } else {
          onError();
        }
        uploading = false;
      },
      () => {
        onError();
        uploading = false;
      }
    );
  };
</script>

<FlowItems pushLast={true}>
  <div style="flex: 1; position: relative;">
    {#key uploading ? 1 : 0}
      <Dropzone
        accept={undefined}
        disabled={uploading}
        disableDefaultStyles={true}
        multiple={false}
        on:drop={onDrop}
        on:dragenter={() => (dragging = true)}
        on:dragleave={() => (dragging = false)}
        containerClasses="dropzone-container"
        containerStyles={dropAddedStyles}
      >
        <div style="padding: 15px">Click or drag to upload</div>
      </Dropzone>
    {/key}
    {#if uploadError}
      <div style="display: inline-block; margin-top: 2px; margin-bottom: 2px" class="label label-danger">{uploadError}</div>
    {/if}
  </div>

  <form on:submit|preventDefault={doRemoteSave}>
    <div style="flex: 1">
      <div class="btn-group">
        <input bind:value={remoteUrl} disabled={uploading} style="min-width: 200px" class="form-control" placeholder="New Cover URL" tabIndex={-1} />
        <button class="btn btn-default" disabled={!remoteUrl || uploading}>
          <i class="far fa-cloud-upload-alt" />
        </button>
      </div>
    </div>
  </form>
</FlowItems>

<style>
  :global(.dropzone-container) {
    border: 3px solid var(--primary-9);
    text-align: center;
    background-color: white;
    padding: 5px;
    color: var(--neutral-text);
    outline: none;
    cursor: pointer;
  }
</style>

// react/app/components/editBook/manageBookCover.tsx
import React, { useState, FunctionComponent } from "react";
import Dropzone, { DropzoneState } from "react-dropzone";
import Toggle from "react-toggle";

import ajaxUtil from "util/ajaxUtil";

import UpdateBook from "graphQL/books/updateBook.graphql";
import { useMutation } from "micro-graphql-react";
import { getCrossOriginAttribute } from "util/corsHelpers";
import { MutationOf, Mutations } from "graphQL/graphql-typings";
import FlowItems from "../layout/FlowItems";
import Stack from "../layout/Stack";
import { useAppState } from "app/state/appState";

type ManageBookCoverProps = {
  onResults: (results: any) => void;
  onError: () => void;
};

const RemoteImageUpload: FunctionComponent<ManageBookCoverProps> = ({ onResults, onError }) => {
  const [{ userId, loginToken }] = useAppState();

  const [url, setUrl] = useState("");
  const [saving, setSaving] = useState(false);

  const keyDown = evt => {
    if (evt.keyCode == 13) {
      doSave();
    }
  };

  const doSave = () => {
    setSaving(true);

    const request = { userId, loginToken, url };
    ajaxUtil.postWithCors(process.env.UPLOAD_BOOK_COVER_FROM_URL, request, onResults, onError).then(() => setSaving(false));
  };

  return (
    <div className="btn-group">
      <input
        onKeyDown={keyDown}
        value={url}
        style={{ minWidth: "200px" }}
        onChange={e => setUrl(e.target.value)}
        className="form-control"
        placeholder="Upload from URL"
        tabIndex={-1}
      />
      <button className="btn btn-default" disabled={!url || saving} onClick={doSave}>
        <i className="far fa-cloud-upload-alt" />
      </button>
    </div>
  );
};

const ManageBookCover: FunctionComponent<ManageBookCoverProps> = props => {
  const { onResults, onError } = props;
  const [uploadState, setUploadState] = useState({ pendingImg: "", uploadError: "" });

  const [{ loginToken, userId }] = useAppState();

  const [uploading, setUploading] = useState(false);

  const processCoverResponse = res => {
    if (res.error === true) {
      res.error = "Error uploading";
    }

    if (res.error) {
      setUploadState({ pendingImg: "", uploadError: res.error });
    } else if (!res.url) {
      setUploadState({ pendingImg: "", uploadError: "Error uploading" });
    } else {
      setUploadState({ pendingImg: res.url, uploadError: "Error uploading" });
    }
    setUploading(false);
  };

  const processCoverError = res => {
    setUploadState({ pendingImg: "", uploadError: "Error uploading" });
    setUploading(false);
  };

  const onDrop = files => {
    let request = new FormData();
    request.append("fileUploaded", files[0]);
    request.append("loginToken", loginToken);
    request.append("userId", userId);

    setUploading(true);
    ajaxUtil.postWithFilesCors(process.env.UPLOAD_BOOK_COVER, request, processCoverResponse, processCoverError);
  };

  const { pendingImg, uploadError } = uploadState;

  const getDropzoneStyle = (state: DropzoneState) => {
    if (uploading) {
      return { border: "3px solid var(--neutral-6)", color: "var(--neutral-6)", cursor: "wait" };
    } else if (state.isDragAccept) {
      return { border: "3px solid var(--primary-8)" };
    } else if (state.isDragReject) {
      return { border: "3px solid var(--primary-9)" };
    } else if (state.isDragActive) {
      return { border: "3px solid var(--primary-9)" };
    }

    return { border: "3px solid var(--primary-9)" };
  };

  return (
    <FlowItems pushLast={true}>
      <div style={{ position: "relative", flex: 1 }}>
        <Dropzone disabled={uploading} onDrop={files => onDrop(files)} multiple={false}>
          {state => (
            <div
              {...state.getRootProps()}
              style={{ padding: "5px", fontSize: "14px", textAlign: "center", cursor: "pointer", ...getDropzoneStyle(state) }}
            >
              <input {...state.getInputProps()} />
              <div style={{ fontWeight: "bold", padding: "15px" }}>Click or drag to upload</div>
            </div>
          )}
        </Dropzone>
        {uploadError ? (
          <div style={{ display: "inline-block", marginTop: "2px", marginBottom: "2px" }} className="label label-danger">
            {uploadError}
          </div>
        ) : null}
      </div>

      <div style={{ flex: 1 }}>
        <RemoteImageUpload {...{ onResults, onError }} />
      </div>
    </FlowItems>
  );
};

export default ManageBookCover;
